using System.Collections.Generic;
using System.Text;

namespace FFChat
{
    static partial class FFData
    {
        public static readonly IDictionary<int, byte[]> Completion = new Dictionary<int, byte[]>
        {
            { 100, Encoding.UTF8.GetBytes("【언어】") },
            { 101, Encoding.UTF8.GetBytes("상용구 사전을 사용해주세요.") },
            { 102, Encoding.UTF8.GetBytes("일본어") },
            { 103, Encoding.UTF8.GetBytes("영어") },
            { 104, Encoding.UTF8.GetBytes("프랑스어") },
            { 105, Encoding.UTF8.GetBytes("독일어") },
            { 106, Encoding.UTF8.GetBytes("일본어로 대화해도 될까요?") },
            { 107, Encoding.UTF8.GetBytes("영어로 대화해도 될까요?") },
            { 108, Encoding.UTF8.GetBytes("프랑스어로 대화해도 될까요?") },
            { 109, Encoding.UTF8.GetBytes("독일어로 대화해도 될까요?") },
            { 110, Encoding.UTF8.GetBytes("저는 영어를 못합니다.") },
            { 111, Encoding.UTF8.GetBytes("저는 일본어를 못합니다.") },
            { 112, Encoding.UTF8.GetBytes("저는 프랑스어를 못합니다.") },
            { 113, Encoding.UTF8.GetBytes("저는 독일어를 못합니다.") },
            { 114, Encoding.UTF8.GetBytes("제 말을 들어주세요.") },
            { 115, Encoding.UTF8.GetBytes("들리십니까?") },
            { 116, Encoding.UTF8.GetBytes("간단한 의사소통은 가능합니다.") },
            { 117, Encoding.UTF8.GetBytes("조금은 이해할 수 있습니다.") },
            { 118, Encoding.UTF8.GetBytes("쉬운 단어로 말씀해주세요.") },
            { 119, Encoding.UTF8.GetBytes("줄임말은 사용하지 말아주세요.") },
            { 120, Encoding.UTF8.GetBytes("\"곧 대답하겠습니다, 잠시만 기다려주세요.\"") },
            { 121, Encoding.UTF8.GetBytes("모국어는 무엇입니까?") },
            { 200, Encoding.UTF8.GetBytes("【인사】") },
            { 201, Encoding.UTF8.GetBytes("처음 뵙겠습니다.") },
            { 202, Encoding.UTF8.GetBytes("좋은 아침입니다!") },
            { 203, Encoding.UTF8.GetBytes("안녕하세요.") },
            { 204, Encoding.UTF8.GetBytes("오늘 하루 어떠셨나요?") },
            { 205, Encoding.UTF8.GetBytes("안녕히 주무세요.") },
            { 206, Encoding.UTF8.GetBytes("좋은 하루 보내세요.") },
            { 207, Encoding.UTF8.GetBytes("재미있었어요.") },
            { 208, Encoding.UTF8.GetBytes("또 만나요!") },
            { 209, Encoding.UTF8.GetBytes("또 같이 놀아요.") },
            { 210, Encoding.UTF8.GetBytes("다녀왔습니다.") },
            { 211, Encoding.UTF8.GetBytes("어서 오세요.") },
            { 212, Encoding.UTF8.GetBytes("축하합니다!") },
            { 213, Encoding.UTF8.GetBytes("잘하셨어요!") },
            { 214, Encoding.UTF8.GetBytes("힘 내세요!") },
            { 215, Encoding.UTF8.GetBytes("야호!") },
            { 216, Encoding.UTF8.GetBytes("감사합니다.") },
            { 217, Encoding.UTF8.GetBytes("별말씀을요.") },
            { 218, Encoding.UTF8.GetBytes("조심하세요.") },
            { 219, Encoding.UTF8.GetBytes("죄송합니다.") },
            { 220, Encoding.UTF8.GetBytes("용서해주세요.") },
            { 221, Encoding.UTF8.GetBytes("아쉽네요.") },
            { 222, Encoding.UTF8.GetBytes("잠깐만요.") },
            { 223, Encoding.UTF8.GetBytes("즐거운 모험 하시길!") },
            { 224, Encoding.UTF8.GetBytes("여기는 처음 옵니다.") },
            { 225, Encoding.UTF8.GetBytes("기대되네요!") },
            { 226, Encoding.UTF8.GetBytes("수고하셨습니다.") },
            { 227, Encoding.UTF8.GetBytes("잘 부탁합니다!") },
            { 228, Encoding.UTF8.GetBytes("이만 가봐야겠어요. 실례하겠습니다.") },
            { 229, Encoding.UTF8.GetBytes("편하게 합시다!") },
            { 230, Encoding.UTF8.GetBytes("열심히 하겠습니다!") },
            { 300, Encoding.UTF8.GetBytes("【질문】") },
            { 301, Encoding.UTF8.GetBytes("누구세요?") },
            { 302, Encoding.UTF8.GetBytes("어느 쪽인가요?") },
            { 303, Encoding.UTF8.GetBytes("어떻게 할까요?") },
            { 304, Encoding.UTF8.GetBytes("뭐예요?") },
            { 305, Encoding.UTF8.GetBytes("언제인가요?") },
            { 306, Encoding.UTF8.GetBytes("얼마나요?") },
            { 307, Encoding.UTF8.GetBytes("어디인가요?") },
            { 308, Encoding.UTF8.GetBytes("왜 그러세요?") },
            { 309, Encoding.UTF8.GetBytes("이유를 말씀해주세요.") },
            { 310, Encoding.UTF8.GetBytes("어디 가세요?") },
            { 311, Encoding.UTF8.GetBytes("가능하신가요?") },
            { 312, Encoding.UTF8.GetBytes("도와드릴까요?") },
            { 313, Encoding.UTF8.GetBytes("어떤 임무를 할까요?") },
            { 314, Encoding.UTF8.GetBytes("어떤 임무가 가능하세요?") },
            { 315, Encoding.UTF8.GetBytes("가지고 계신가요?") },
            { 316, Encoding.UTF8.GetBytes("지금 어떤 무기를 가지고 계신가요?") },
            { 317, Encoding.UTF8.GetBytes("다른 클래스는 뭐가 가능하신가요?") },
            { 318, Encoding.UTF8.GetBytes("다른 역할은 뭐가 가능하신가요?") },
            { 319, Encoding.UTF8.GetBytes("준비되어 있나요?") },
            { 320, Encoding.UTF8.GetBytes("어떤 작전으로 싸울까요?") },
            { 321, Encoding.UTF8.GetBytes("친구 신청해도 될까요?") },
            { 322, Encoding.UTF8.GetBytes("잠깐 쉬었다 갈까요?") },
            { 323, Encoding.UTF8.GetBytes("수리합시다.") },
            { 324, Encoding.UTF8.GetBytes("수리해주시면 안 될까요?") },
            { 325, Encoding.UTF8.GetBytes("마테리아 장착할까요?") },
            { 326, Encoding.UTF8.GetBytes("마테리아 장착해주시겠어요?") },
            { 327, Encoding.UTF8.GetBytes("파티에 초대해도 될까요?") },
            { 328, Encoding.UTF8.GetBytes("파티에 초대해주시겠어요?") },
            { 329, Encoding.UTF8.GetBytes("파티를 해체할까요?") },
            { 330, Encoding.UTF8.GetBytes("링크셸에 초대해도 될까요?") },
            { 331, Encoding.UTF8.GetBytes("링크셸에 초대해주시겠어요?") },
            { 332, Encoding.UTF8.GetBytes("자유부대에 초대해도 될까요?") },
            { 333, Encoding.UTF8.GetBytes("자유부대에 초대해주시겠어요?") },
            { 334, Encoding.UTF8.GetBytes("뭐 하고 계시나요?") },
            { 335, Encoding.UTF8.GetBytes("카드 대결 하실래요?") },
            { 336, Encoding.UTF8.GetBytes("규칙을 바꾸고 싶어요.") },
            { 337, Encoding.UTF8.GetBytes("대회 대결 하실래요?") },
            { 338, Encoding.UTF8.GetBytes("MP는 괜찮으세요?") },
            { 339, Encoding.UTF8.GetBytes("모르는 점이 있으신가요?") },
            { 340, Encoding.UTF8.GetBytes("보셨나요?") },
            { 341, Encoding.UTF8.GetBytes("공략 방법은 아시나요?") },
            { 400, Encoding.UTF8.GetBytes("【대답】") },
            { 401, Encoding.UTF8.GetBytes("모르겠어요.") },
            { 402, Encoding.UTF8.GetBytes("필요 없어요.") },
            { 403, Encoding.UTF8.GetBytes("\"네, 부탁합니다.\"") },
            { 404, Encoding.UTF8.GetBytes("부탁합니다.") },
            { 405, Encoding.UTF8.GetBytes("알겠습니다.") },
            { 406, Encoding.UTF8.GetBytes("지금은 바쁘니 나중에 이야기해요.") },
            { 407, Encoding.UTF8.GetBytes("지금은 혼자 다니고 싶어요.") },
            { 408, Encoding.UTF8.GetBytes("대답하고 싶지만 어떻게 말해야 할지 모르겠어요.") },
            { 409, Encoding.UTF8.GetBytes("그렇군요.") },
            { 410, Encoding.UTF8.GetBytes("말씀은 감사하지만 사양할게요.") },
            { 411, Encoding.UTF8.GetBytes("흐음.") },
            { 412, Encoding.UTF8.GetBytes("음…") },
            { 413, Encoding.UTF8.GetBytes("뭐!?") },
            { 414, Encoding.UTF8.GetBytes("정말?") },
            { 415, Encoding.UTF8.GetBytes("으으음.") },
            { 416, Encoding.UTF8.GetBytes("다른 약속이 있어요.") },
            { 417, Encoding.UTF8.GetBytes("재대결하고 싶습니다.") },
            { 418, Encoding.UTF8.GetBytes("대결을 마치고 싶습니다.") },
            { 419, Encoding.UTF8.GetBytes("잠시 중단하고 싶습니다.") },
            { 420, Encoding.UTF8.GetBytes("그럴지도 모릅니다.") },
            { 500, Encoding.UTF8.GetBytes("【이유】") },
            { 501, Encoding.UTF8.GetBytes("시전 중입니다.") },
            { 502, Encoding.UTF8.GetBytes("일하러 갈 시간입니다.") },
            { 503, Encoding.UTF8.GetBytes("약속이 있습니다.") },
            { 504, Encoding.UTF8.GetBytes("자러 갈 겁니다.") },
            { 505, Encoding.UTF8.GetBytes("힘들어요.") },
            { 506, Encoding.UTF8.GetBytes("볼일이 있어서 그만 가볼게요.") },
            { 507, Encoding.UTF8.GetBytes("몸이 안 좋습니다.") },
            { 508, Encoding.UTF8.GetBytes("내키지 않습니다.") },
            { 509, Encoding.UTF8.GetBytes("재미있을 것 같네요.") },
            { 510, Encoding.UTF8.GetBytes("임무 중입니다.") },
            { 511, Encoding.UTF8.GetBytes("전투 중입니다.") },
            { 512, Encoding.UTF8.GetBytes("돈 벌러 가야 합니다.") },
            { 513, Encoding.UTF8.GetBytes("기억이 안 납니다.") },
            { 514, Encoding.UTF8.GetBytes("모릅니다.") },
            { 515, Encoding.UTF8.GetBytes("방금 사용했습니다.") },
            { 516, Encoding.UTF8.GetBytes("경험치를 벌고 싶습니다.") },
            { 517, Encoding.UTF8.GetBytes("실수했습니다.") },
            { 518, Encoding.UTF8.GetBytes("이미 참가 중입니다.") },
            { 519, Encoding.UTF8.GetBytes("이미 가지고 있습니다.") },
            { 520, Encoding.UTF8.GetBytes("모집이 끝났습니다.") },
            { 521, Encoding.UTF8.GetBytes("준비 중입니다.") },
            { 522, Encoding.UTF8.GetBytes("바쁩니다.") },
            { 523, Encoding.UTF8.GetBytes("잡담을 나누고 있습니다.") },
            { 524, Encoding.UTF8.GetBytes("키보드를 안 쓰고 있습니다.") },
            { 525, Encoding.UTF8.GetBytes("탐색 중입니다.") },
            { 600, Encoding.UTF8.GetBytes("【교환】") },
            { 601, Encoding.UTF8.GetBytes("주시면 안 될까요?") },
            { 602, Encoding.UTF8.GetBytes("해 주시면 안 될까요?") },
            { 603, Encoding.UTF8.GetBytes("깎아 주시면 안 될까요?") },
            { 604, Encoding.UTF8.GetBytes("사 주시면 안 될까요?") },
            { 605, Encoding.UTF8.GetBytes("파시면 안 될까요?") },
            { 606, Encoding.UTF8.GetBytes("교환하시겠어요?") },
            { 607, Encoding.UTF8.GetBytes("필요 없으신가요?") },
            { 608, Encoding.UTF8.GetBytes("제작 가능하신가요?") },
            { 609, Encoding.UTF8.GetBytes("가지고 계신가요?") },
            { 610, Encoding.UTF8.GetBytes("필요한 재료를 알려주세요.") },
            { 611, Encoding.UTF8.GetBytes("돈이 없습니다.") },
            { 612, Encoding.UTF8.GetBytes("아이템이 없습니다.") },
            { 613, Encoding.UTF8.GetBytes("줄 수 있는 게 없습니다.") },
            { 614, Encoding.UTF8.GetBytes("이걸 드리겠습니다.") },
            { 615, Encoding.UTF8.GetBytes("주세요.") },
            { 616, Encoding.UTF8.GetBytes("보상:") },
            { 617, Encoding.UTF8.GetBytes("가격:") },
            { 618, Encoding.UTF8.GetBytes("우편물") },
            { 700, Encoding.UTF8.GetBytes("【편성】") },
            { 701, Encoding.UTF8.GetBytes("모집 중입니다.") },
            { 702, Encoding.UTF8.GetBytes("모여주세요.") },
            { 703, Encoding.UTF8.GetBytes("함께 하실래요?") },
            { 704, Encoding.UTF8.GetBytes("한 분이신가요?") },
            { 705, Encoding.UTF8.GetBytes("빈자리 있나요?") },
            { 706, Encoding.UTF8.GetBytes("초대해주세요.") },
            { 707, Encoding.UTF8.GetBytes("참가하고 싶습니다.") },
            { 708, Encoding.UTF8.GetBytes("리더가 누구인가요?") },
            { 709, Encoding.UTF8.GetBytes("짧게 도는 것도 괜찮습니다.") },
            { 710, Encoding.UTF8.GetBytes("파티에 빈자리가 없습니다.") },
            { 711, Encoding.UTF8.GetBytes("도와주세요.") },
            { 712, Encoding.UTF8.GetBytes("파티 해체하겠습니다.") },
            { 713, Encoding.UTF8.GetBytes("자리 비우겠습니다.") },
            { 714, Encoding.UTF8.GetBytes("파티에 참가하고 싶습니다.") },
            { 715, Encoding.UTF8.GetBytes("소규모 파티") },
            { 716, Encoding.UTF8.GetBytes("대규모 파티") },
            { 717, Encoding.UTF8.GetBytes("아직 익숙하지 않습니다.") },
            { 800, Encoding.UTF8.GetBytes("【전술】") },
            { 801, Encoding.UTF8.GetBytes("따라오세요.") },
            { 802, Encoding.UTF8.GetBytes("따라가겠습니다.") },
            { 803, Encoding.UTF8.GetBytes("조사해주세요.") },
            { 804, Encoding.UTF8.GetBytes("찾았어요!") },
            { 805, Encoding.UTF8.GetBytes("전력을 다해 공격하세요!") },
            { 806, Encoding.UTF8.GetBytes("뒤로 물러나주세요.") },
            { 807, Encoding.UTF8.GetBytes("적개심 수치에 주의하세요.") },
            { 808, Encoding.UTF8.GetBytes("이거 먼저 처치할게요!") },
            { 809, Encoding.UTF8.GetBytes("공격하지 마세요.") },
            { 810, Encoding.UTF8.GetBytes("발을 묶어주세요!") },
            { 811, Encoding.UTF8.GetBytes("효과 없애주세요!") },
            { 812, Encoding.UTF8.GetBytes("회복해주세요!") },
            { 813, Encoding.UTF8.GetBytes("걸어주세요!") },
            { 814, Encoding.UTF8.GetBytes("도망쳐요!") },
            { 815, Encoding.UTF8.GetBytes("도와주세요!") },
            { 816, Encoding.UTF8.GetBytes("멈추세요!") },
            { 817, Encoding.UTF8.GetBytes("대기하세요.") },
            { 818, Encoding.UTF8.GetBytes("없어졌습니다.") },
            { 819, Encoding.UTF8.GetBytes("없습니다.") },
            { 820, Encoding.UTF8.GetBytes("아껴 쓰세요.") },
            { 821, Encoding.UTF8.GetBytes("아껴 쓰겠습니다.") },
            { 822, Encoding.UTF8.GetBytes("장비 내구도가 떨어졌습니다.") },
            { 823, Encoding.UTF8.GetBytes("준비완료!") },
            { 824, Encoding.UTF8.GetBytes("표식을 설정해주세요.") },
            { 825, Encoding.UTF8.GetBytes("이거 쓰세요.") },
            { 826, Encoding.UTF8.GetBytes("조금만 쉴게요.") },
            { 827, Encoding.UTF8.GetBytes("적을 끌고 오겠습니다.") },
            { 828, Encoding.UTF8.GetBytes("적은 제가 맡을게요.") },
            { 829, Encoding.UTF8.GetBytes("잠깐만요.") },
            { 830, Encoding.UTF8.GetBytes("현지에서 모이죠.") },
            { 831, Encoding.UTF8.GetBytes("이동합니다.") },
            { 832, Encoding.UTF8.GetBytes("그 자리에 있으세요.") },
            { 833, Encoding.UTF8.GetBytes("지금 그쪽으로 갈게요.") },
            { 834, Encoding.UTF8.GetBytes("금방 돌아올게요.") },
            { 835, Encoding.UTF8.GetBytes("주사위 굴려주세요.") },
            { 836, Encoding.UTF8.GetBytes("약점:") },
            { 837, Encoding.UTF8.GetBytes("주의:") },
            { 838, Encoding.UTF8.GetBytes("추천:") },
            { 839, Encoding.UTF8.GetBytes("토벌 순서:") },
            { 840, Encoding.UTF8.GetBytes("원하는 것:") },
            { 841, Encoding.UTF8.GetBytes("적개심 끌어주세요.") },
            { 842, Encoding.UTF8.GetBytes("적이 다가옵니다!") },
            { 843, Encoding.UTF8.GetBytes("신경 쓰지 마세요.") },
            { 844, Encoding.UTF8.GetBytes("무시하세요.") },
            { 845, Encoding.UTF8.GetBytes("교대") },
            { 846, Encoding.UTF8.GetBytes("교대해주세요!") },
            { 847, Encoding.UTF8.GetBytes("제가 먼저 공격하겠습니다!") },
            { 848, Encoding.UTF8.GetBytes("천천히 진행합시다.") },
            { 849, Encoding.UTF8.GetBytes("실행해주세요!") },
            { 900, Encoding.UTF8.GetBytes("【역할】") },
            { 901, Encoding.UTF8.GetBytes("파티장") },
            { 902, Encoding.UTF8.GetBytes("부대장") },
            { 903, Encoding.UTF8.GetBytes("투사") },
            { 904, Encoding.UTF8.GetBytes("마법사") },
            { 905, Encoding.UTF8.GetBytes("채집가") },
            { 906, Encoding.UTF8.GetBytes("제작자") },
            { 907, Encoding.UTF8.GetBytes("방어 역할") },
            { 908, Encoding.UTF8.GetBytes("근거리 공격 역할") },
            { 909, Encoding.UTF8.GetBytes("원거리 공격 역할") },
            { 910, Encoding.UTF8.GetBytes("회복 역할") },
            { 911, Encoding.UTF8.GetBytes("강화 역할") },
            { 912, Encoding.UTF8.GetBytes("마법 공격 역할") },
            { 913, Encoding.UTF8.GetBytes("공격 역할") },
            { 950, Encoding.UTF8.GetBytes("【위치】") },
            { 951, Encoding.UTF8.GetBytes("위치") },
            { 952, Encoding.UTF8.GetBytes("북쪽") },
            { 953, Encoding.UTF8.GetBytes("남쪽") },
            { 954, Encoding.UTF8.GetBytes("동쪽") },
            { 955, Encoding.UTF8.GetBytes("서쪽") },
            { 956, Encoding.UTF8.GetBytes("위쪽") },
            { 957, Encoding.UTF8.GetBytes("아래쪽") },
            { 958, Encoding.UTF8.GetBytes("오른쪽") },
            { 959, Encoding.UTF8.GetBytes("왼쪽") },
            { 960, Encoding.UTF8.GetBytes("앞") },
            { 961, Encoding.UTF8.GetBytes("뒤") },
            { 962, Encoding.UTF8.GetBytes("옆") },
            { 963, Encoding.UTF8.GetBytes("정면") },
            { 964, Encoding.UTF8.GetBytes("중앙") },
            { 965, Encoding.UTF8.GetBytes("측면") },
            { 966, Encoding.UTF8.GetBytes("안쪽") },
            { 967, Encoding.UTF8.GetBytes("바깥쪽") },
            { 968, Encoding.UTF8.GetBytes("이쪽") },
            { 969, Encoding.UTF8.GetBytes("저쪽") },
            { 970, Encoding.UTF8.GetBytes("그쪽") },
            { 971, Encoding.UTF8.GetBytes("좀 더 가까이") },
            { 972, Encoding.UTF8.GetBytes("좀 더 멀리") },
            { 973, Encoding.UTF8.GetBytes("입구") },
            { 974, Encoding.UTF8.GetBytes("출구") },
            { 1000, Encoding.UTF8.GetBytes("【시간】") },
            { 1001, Encoding.UTF8.GetBytes("그저께") },
            { 1002, Encoding.UTF8.GetBytes("어제") },
            { 1003, Encoding.UTF8.GetBytes("오늘") },
            { 1004, Encoding.UTF8.GetBytes("내일") },
            { 1005, Encoding.UTF8.GetBytes("모레") },
            { 1006, Encoding.UTF8.GetBytes("저번 주") },
            { 1007, Encoding.UTF8.GetBytes("이번 주") },
            { 1008, Encoding.UTF8.GetBytes("다음 주") },
            { 1009, Encoding.UTF8.GetBytes("오전") },
            { 1010, Encoding.UTF8.GetBytes("오후") },
            { 1011, Encoding.UTF8.GetBytes("아침") },
            { 1012, Encoding.UTF8.GetBytes("낮") },
            { 1013, Encoding.UTF8.GetBytes("밤") },
            { 1014, Encoding.UTF8.GetBytes("요일") },
            { 1015, Encoding.UTF8.GetBytes("일요일") },
            { 1016, Encoding.UTF8.GetBytes("월요일") },
            { 1017, Encoding.UTF8.GetBytes("화요일") },
            { 1018, Encoding.UTF8.GetBytes("수요일") },
            { 1019, Encoding.UTF8.GetBytes("목요일") },
            { 1020, Encoding.UTF8.GetBytes("금요일") },
            { 1021, Encoding.UTF8.GetBytes("토요일") },
            { 1022, Encoding.UTF8.GetBytes("휴일") },
            { 1023, Encoding.UTF8.GetBytes("휴가") },
            { 1024, Encoding.UTF8.GetBytes("장기") },
            { 1025, Encoding.UTF8.GetBytes("단기") },
            { 1026, Encoding.UTF8.GetBytes("날짜") },
            { 1027, Encoding.UTF8.GetBytes("초") },
            { 1028, Encoding.UTF8.GetBytes("분") },
            { 1029, Encoding.UTF8.GetBytes("시간") },
            { 1030, Encoding.UTF8.GetBytes("월") },
            { 1031, Encoding.UTF8.GetBytes("년") },
            { 1032, Encoding.UTF8.GetBytes("1월") },
            { 1033, Encoding.UTF8.GetBytes("2월") },
            { 1034, Encoding.UTF8.GetBytes("3월") },
            { 1035, Encoding.UTF8.GetBytes("4월") },
            { 1036, Encoding.UTF8.GetBytes("5월") },
            { 1037, Encoding.UTF8.GetBytes("6월") },
            { 1038, Encoding.UTF8.GetBytes("7월") },
            { 1039, Encoding.UTF8.GetBytes("8월") },
            { 1040, Encoding.UTF8.GetBytes("9월") },
            { 1041, Encoding.UTF8.GetBytes("10월") },
            { 1042, Encoding.UTF8.GetBytes("11월") },
            { 1043, Encoding.UTF8.GetBytes("12월") },
            { 1044, Encoding.UTF8.GetBytes("지난달") },
            { 1045, Encoding.UTF8.GetBytes("이번 달") },
            { 1046, Encoding.UTF8.GetBytes("다음 달") },
            { 1047, Encoding.UTF8.GetBytes("작년") },
            { 1048, Encoding.UTF8.GetBytes("올해") },
            { 1049, Encoding.UTF8.GetBytes("내년") },
            { 1050, Encoding.UTF8.GetBytes("지금") },
            { 1051, Encoding.UTF8.GetBytes("곧") },
            { 1052, Encoding.UTF8.GetBytes("언제든지") },
            { 1053, Encoding.UTF8.GetBytes("처음") },
            { 1054, Encoding.UTF8.GetBytes("마지막") },
            { 1055, Encoding.UTF8.GetBytes("대기 시간") },
            { 1056, Encoding.UTF8.GetBytes("남은 시간") },
            { 1057, Encoding.UTF8.GetBytes("종료 시간") },
            { 1058, Encoding.UTF8.GetBytes("제6성력") },
            { 1059, Encoding.UTF8.GetBytes("제7재해") },
            { 1060, Encoding.UTF8.GetBytes("제7성력") },
            { 1150, Encoding.UTF8.GetBytes("【이동 방법】") },
            { 1151, Encoding.UTF8.GetBytes("걷기") },
            { 1152, Encoding.UTF8.GetBytes("달리기") },
            { 1153, Encoding.UTF8.GetBytes("따라가기") },
            { 1154, Encoding.UTF8.GetBytes("초코보") },
            { 1155, Encoding.UTF8.GetBytes("내 초코보") },
            { 1156, Encoding.UTF8.GetBytes("초코보 대여") },
            { 1157, Encoding.UTF8.GetBytes("초코보 수송") },
            { 1158, Encoding.UTF8.GetBytes("마운트") },
            { 1159, Encoding.UTF8.GetBytes("텔레포") },
            { 1160, Encoding.UTF8.GetBytes("데존") },
            { 1161, Encoding.UTF8.GetBytes("도시 내 이동") },
            { 1162, Encoding.UTF8.GetBytes("비공정") },
            { 1163, Encoding.UTF8.GetBytes("귀환 지점") },
            { 1164, Encoding.UTF8.GetBytes("정기선") },
            { 1165, Encoding.UTF8.GetBytes("나는 탈것") },
            { 1200, Encoding.UTF8.GetBytes("【시설】") },
            { 1201, Encoding.UTF8.GetBytes("에테라이트") },
            { 1202, Encoding.UTF8.GetBytes("도시 내 이동") },
            { 1203, Encoding.UTF8.GetBytes("모험가 길드") },
            { 1204, Encoding.UTF8.GetBytes("길드") },
            { 1205, Encoding.UTF8.GetBytes("상점") },
            { 1206, Encoding.UTF8.GetBytes("초코보 대여소") },
            { 1207, Encoding.UTF8.GetBytes("여관") },
            { 1208, Encoding.UTF8.GetBytes("초인종") },
            { 1209, Encoding.UTF8.GetBytes("휴식 지역") },
            { 1210, Encoding.UTF8.GetBytes("길드 의뢰 발행 담당자") },
            { 1211, Encoding.UTF8.GetBytes("링크셸 배포 담당자") },
            { 1212, Encoding.UTF8.GetBytes("장터 게시판") },
            { 1213, Encoding.UTF8.GetBytes("집사 고용창구") },
            { 1214, Encoding.UTF8.GetBytes("수리공") },
            { 1215, Encoding.UTF8.GetBytes("비공정 승강장") },
            { 1216, Encoding.UTF8.GetBytes("배달부 모그리") },
            { 1217, Encoding.UTF8.GetBytes("선착장") },
            { 1218, Encoding.UTF8.GetBytes("여객선 부두") },
            { 1219, Encoding.UTF8.GetBytes("비공정 승강장") },
            { 1220, Encoding.UTF8.GetBytes("흑와단 군령부") },
            { 1221, Encoding.UTF8.GetBytes("쌍사당 통합사령부") },
            { 1222, Encoding.UTF8.GetBytes("불멸대 작전본부") },
            { 1223, Encoding.UTF8.GetBytes("모험가 거주구역") },
            { 1224, Encoding.UTF8.GetBytes("투기장 대결 접수처") },
            { 1225, Encoding.UTF8.GetBytes("마물 수배 게시판") },
            { 1226, Encoding.UTF8.GetBytes("일기예보사") },
            { 1227, Encoding.UTF8.GetBytes("미용사 호출 초인종") },
            { 1228, Encoding.UTF8.GetBytes("확장 구역") },
            { 1250, Encoding.UTF8.GetBytes("【총사령부】") },
            { 1251, Encoding.UTF8.GetBytes("총사령부") },
            { 1252, Encoding.UTF8.GetBytes("계급") },
            { 1253, Encoding.UTF8.GetBytes("군수물자") },
            { 1254, Encoding.UTF8.GetBytes("보급물자") },
            { 1255, Encoding.UTF8.GetBytes("희소물자") },
            { 1256, Encoding.UTF8.GetBytes("흑와단") },
            { 1257, Encoding.UTF8.GetBytes("쌍사당") },
            { 1258, Encoding.UTF8.GetBytes("불멸대") },
            { 1270, Encoding.UTF8.GetBytes("【자유부대】") },
            { 1271, Encoding.UTF8.GetBytes("자유부대") },
            { 1272, Encoding.UTF8.GetBytes("서명") },
            { 1273, Encoding.UTF8.GetBytes("부대 게시판") },
            { 1274, Encoding.UTF8.GetBytes("부대 금고") },
            { 1275, Encoding.UTF8.GetBytes("부대 문장") },
            { 1276, Encoding.UTF8.GetBytes("부대 혜택") },
            { 1300, Encoding.UTF8.GetBytes("【게임 시스템】") },
            { 1301, Encoding.UTF8.GetBytes("클래스") },
            { 1302, Encoding.UTF8.GetBytes("클래스 체인지") },
            { 1303, Encoding.UTF8.GetBytes("잡") },
            { 1304, Encoding.UTF8.GetBytes("잡 체인지") },
            { 1305, Encoding.UTF8.GetBytes("소울 크리스탈") },
            { 1306, Encoding.UTF8.GetBytes("레벨") },
            { 1307, Encoding.UTF8.GetBytes("경험치") },
            { 1308, Encoding.UTF8.GetBytes("수호신") },
            { 1309, Encoding.UTF8.GetBytes("민족") },
            { 1310, Encoding.UTF8.GetBytes("부족") },
            { 1311, Encoding.UTF8.GetBytes("지역") },
            { 1312, Encoding.UTF8.GetBytes("장비") },
            { 1313, Encoding.UTF8.GetBytes("아이템") },
            { 1314, Encoding.UTF8.GetBytes("장비세트") },
            { 1315, Encoding.UTF8.GetBytes("휴식 보너스") },
            { 1316, Encoding.UTF8.GetBytes("솔로") },
            { 1317, Encoding.UTF8.GetBytes("파티") },
            { 1318, Encoding.UTF8.GetBytes("탈것") },
            { 1319, Encoding.UTF8.GetBytes("꼬마 친구") },
            { 1320, Encoding.UTF8.GetBytes("집사") },
            { 1321, Encoding.UTF8.GetBytes("전투") },
            { 1322, Encoding.UTF8.GetBytes("제작") },
            { 1323, Encoding.UTF8.GetBytes("채집") },
            { 1324, Encoding.UTF8.GetBytes("내구도") },
            { 1325, Encoding.UTF8.GetBytes("결속도") },
            { 1326, Encoding.UTF8.GetBytes("장비 적성") },
            { 1327, Encoding.UTF8.GetBytes("보물상자") },
            { 1328, Encoding.UTF8.GetBytes("대상") },
            { 1329, Encoding.UTF8.GetBytes("대상 고정") },
            { 1330, Encoding.UTF8.GetBytes("주시 대상") },
            { 1331, Encoding.UTF8.GetBytes("대상 표식") },
            { 1332, Encoding.UTF8.GetBytes("메뉴") },
            { 1333, Encoding.UTF8.GetBytes("지도") },
            { 1334, Encoding.UTF8.GetBytes("게임 문의") },
            { 1335, Encoding.UTF8.GetBytes("스크린샷") },
            { 1336, Encoding.UTF8.GetBytes("로그아웃") },
            { 1337, Encoding.UTF8.GetBytes("게임 종료") },
            { 1338, Encoding.UTF8.GetBytes("강제 종료") },
            { 1339, Encoding.UTF8.GetBytes("상용구 사전") },
            { 1340, Encoding.UTF8.GetBytes("감정 표현") },
            { 1341, Encoding.UTF8.GetBytes("업적") },
            { 1342, Encoding.UTF8.GetBytes("칭호") },
            { 1343, Encoding.UTF8.GetBytes("화폐") },
            { 1344, Encoding.UTF8.GetBytes("길") },
            { 1345, Encoding.UTF8.GetBytes("교환") },
            { 1346, Encoding.UTF8.GetBytes("조사") },
            { 1347, Encoding.UTF8.GetBytes("따라가기") },
            { 1348, Encoding.UTF8.GetBytes("연합 파티") },
            { 1349, Encoding.UTF8.GetBytes("하우징") },
            { 1350, Encoding.UTF8.GetBytes("우호도") },
            { 1351, Encoding.UTF8.GetBytes("우호 랭크") },
            { 1352, Encoding.UTF8.GetBytes("플레이어 추천") },
            { 1353, Encoding.UTF8.GetBytes("알라그 석판") },
            { 1354, Encoding.UTF8.GetBytes("알라그 석판: 신화") },
            { 1355, Encoding.UTF8.GetBytes("알라그 석판: 철학") },
            { 1356, Encoding.UTF8.GetBytes("추방 투표") },
            { 1357, Encoding.UTF8.GetBytes("포기 투표") },
            { 1358, Encoding.UTF8.GetBytes("지면 표식") },
            { 1359, Encoding.UTF8.GetBytes("지상 조준") },
            { 1360, Encoding.UTF8.GetBytes("장비 투영") },
            { 1361, Encoding.UTF8.GetBytes("알라그 석판: 전기") },
            { 1362, Encoding.UTF8.GetBytes("미용사") },
            { 1363, Encoding.UTF8.GetBytes("집사 수행") },
            { 1364, Encoding.UTF8.GetBytes("아트마") },
            { 1365, Encoding.UTF8.GetBytes("조디악 웨폰") },
            { 1366, Encoding.UTF8.GetBytes("알렉산드라이트") },
            { 1367, Encoding.UTF8.GetBytes("아니무스") },
            { 1368, Encoding.UTF8.GetBytes("노우스") },
            { 1369, Encoding.UTF8.GetBytes("동맹 휘장") },
            { 1370, Encoding.UTF8.GetBytes("마물 수배서") },
            { 1371, Encoding.UTF8.GetBytes("무법자의 전장") },
            { 1372, Encoding.UTF8.GetBytes("초월하는 힘") },
            { 1373, Encoding.UTF8.GetBytes("초코보 육성") },
            { 1374, Encoding.UTF8.GetBytes("일기예보") },
            { 1375, Encoding.UTF8.GetBytes("알라그 석판: 시학") },
            { 1376, Encoding.UTF8.GetBytes("공헌도") },
            { 1377, Encoding.UTF8.GetBytes("군표") },
            { 1378, Encoding.UTF8.GetBytes("명예 점수") },
            { 1379, Encoding.UTF8.GetBytes("제니스") },
            { 1380, Encoding.UTF8.GetBytes("넥서스") },
            { 1381, Encoding.UTF8.GetBytes("센추리오 휘장") },
            { 1382, Encoding.UTF8.GetBytes("알라그 석판: 법전") },
            { 1383, Encoding.UTF8.GetBytes("알라그 석판: 금서") },
            { 1384, Encoding.UTF8.GetBytes("파티장 분배") },
            { 1385, Encoding.UTF8.GetBytes("선입찰 금지") },
            { 1400, Encoding.UTF8.GetBytes("【전투】") },
            { 1401, Encoding.UTF8.GetBytes("공격") },
            { 1402, Encoding.UTF8.GetBytes("기술") },
            { 1403, Encoding.UTF8.GetBytes("일반 기술") },
            { 1404, Encoding.UTF8.GetBytes("특성") },
            { 1405, Encoding.UTF8.GetBytes("잡 기술") },
            { 1406, Encoding.UTF8.GetBytes("추가 기술") },
            { 1407, Encoding.UTF8.GetBytes("마법") },
            { 1408, Encoding.UTF8.GetBytes("무기 기술") },
            { 1409, Encoding.UTF8.GetBytes("능력") },
            { 1410, Encoding.UTF8.GetBytes("시전 시간") },
            { 1411, Encoding.UTF8.GetBytes("재사용 대기 시간") },
            { 1412, Encoding.UTF8.GetBytes("사용 적성") },
            { 1413, Encoding.UTF8.GetBytes("링크") },
            { 1414, Encoding.UTF8.GetBytes("소환수") },
            { 1415, Encoding.UTF8.GetBytes("버디") },
            { 1416, Encoding.UTF8.GetBytes("적개심") },
            { 1417, Encoding.UTF8.GetBytes("호전적") },
            { 1418, Encoding.UTF8.GetBytes("비호전적") },
            { 1419, Encoding.UTF8.GetBytes("전투불능") },
            { 1420, Encoding.UTF8.GetBytes("전리품") },
            { 1421, Encoding.UTF8.GetBytes("분배") },
            { 1422, Encoding.UTF8.GetBytes("주사위") },
            { 1423, Encoding.UTF8.GetBytes("저항") },
            { 1424, Encoding.UTF8.GetBytes("습득") },
            { 1425, Encoding.UTF8.GetBytes("감지") },
            { 1426, Encoding.UTF8.GetBytes("범위") },
            { 1427, Encoding.UTF8.GetBytes("리미트 브레이크") },
            { 1428, Encoding.UTF8.GetBytes("적") },
            { 1429, Encoding.UTF8.GetBytes("마물") },
            { 1430, Encoding.UTF8.GetBytes("악명 높은 마물") },
            { 1431, Encoding.UTF8.GetBytes("능력치 보너스") },
            { 1432, Encoding.UTF8.GetBytes("연속 처치 보너스") },
            { 1433, Encoding.UTF8.GetBytes("추가 직업 보너스") },
            { 1434, Encoding.UTF8.GetBytes("레벨 조정") },
            { 1435, Encoding.UTF8.GetBytes("PvP 기술") },
            { 1436, Encoding.UTF8.GetBytes("범위공격") },
            { 1437, Encoding.UTF8.GetBytes("전방 범위공격") },
            { 1438, Encoding.UTF8.GetBytes("후방 범위공격") },
            { 1439, Encoding.UTF8.GetBytes("전체공격") },
            { 1440, Encoding.UTF8.GetBytes("외곽 거점") },
            { 1441, Encoding.UTF8.GetBytes("거주구역 유적") },
            { 1442, Encoding.UTF8.GetBytes("거점") },
            { 1443, Encoding.UTF8.GetBytes("깃발") },
            { 1444, Encoding.UTF8.GetBytes("점거") },
            { 1445, Encoding.UTF8.GetBytes("중립") },
            { 1446, Encoding.UTF8.GetBytes("전술 점수") },
            { 1447, Encoding.UTF8.GetBytes("시장 유적") },
            { 1448, Encoding.UTF8.GetBytes("태양신전") },
            { 1449, Encoding.UTF8.GetBytes("콤보") },
            { 1450, Encoding.UTF8.GetBytes("아드레날린 폭주") },
            { 1451, Encoding.UTF8.GetBytes("단독 공격") },
            { 1452, Encoding.UTF8.GetBytes("쇠뇌") },
            { 1453, Encoding.UTF8.GetBytes("알라그 석탑") },
            { 1500, Encoding.UTF8.GetBytes("【접속 상태】") },
            { 1501, Encoding.UTF8.GetBytes("접속 중") },
            { 1502, Encoding.UTF8.GetBytes("자리 비움") },
            { 1503, Encoding.UTF8.GetBytes("다른 용무 중") },
            { 1504, Encoding.UTF8.GetBytes("파티 찾는 중") },
            { 1505, Encoding.UTF8.GetBytes("마테리아 장착 대행 중") },
            { 1506, Encoding.UTF8.GetBytes("임무 중") },
            { 1507, Encoding.UTF8.GetBytes("접속 종료") },
            { 1508, Encoding.UTF8.GetBytes("파티 모집 중") },
            { 1509, Encoding.UTF8.GetBytes("초보자") },
            { 1550, Encoding.UTF8.GetBytes("【의사소통】") },
            { 1551, Encoding.UTF8.GetBytes("대화") },
            { 1552, Encoding.UTF8.GetBytes("귓속말") },
            { 1553, Encoding.UTF8.GetBytes("말하기") },
            { 1554, Encoding.UTF8.GetBytes("외치기") },
            { 1555, Encoding.UTF8.GetBytes("떠들기") },
            { 1556, Encoding.UTF8.GetBytes("친구 목록") },
            { 1557, Encoding.UTF8.GetBytes("차단 목록 관리") },
            { 1558, Encoding.UTF8.GetBytes("플레이어 검색") },
            { 1559, Encoding.UTF8.GetBytes("링크셸") },
            { 1560, Encoding.UTF8.GetBytes("모그레터") },
            { 1564, Encoding.UTF8.GetBytes("포럼") },
            { 1565, Encoding.UTF8.GetBytes("순위") },
            { 1566, Encoding.UTF8.GetBytes("총사령부 순위") },
            { 1567, Encoding.UTF8.GetBytes("자유부대 순위") },
            { 1568, Encoding.UTF8.GetBytes("파티") },
            { 1569, Encoding.UTF8.GetBytes("연합 파티") },
            { 1570, Encoding.UTF8.GetBytes("링크셸") },
            { 1571, Encoding.UTF8.GetBytes("자유부대") },
            { 1600, Encoding.UTF8.GetBytes("【제작 & 채집】") },
            { 1601, Encoding.UTF8.GetBytes("샤드") },
            { 1602, Encoding.UTF8.GetBytes("크리스탈") },
            { 1603, Encoding.UTF8.GetBytes("클러스터") },
            { 1604, Encoding.UTF8.GetBytes("마테리아") },
            { 1605, Encoding.UTF8.GetBytes("마테리아화") },
            { 1606, Encoding.UTF8.GetBytes("마테리아 공예") },
            { 1607, Encoding.UTF8.GetBytes("장터") },
            { 1608, Encoding.UTF8.GetBytes("장터 검색") },
            { 1609, Encoding.UTF8.GetBytes("HQ") },
            { 1610, Encoding.UTF8.GetBytes("고유") },
            { 1611, Encoding.UTF8.GetBytes("거래 불가") },
            { 1612, Encoding.UTF8.GetBytes("재료") },
            { 1613, Encoding.UTF8.GetBytes("간이 제작") },
            { 1614, Encoding.UTF8.GetBytes("품질") },
            { 1615, Encoding.UTF8.GetBytes("고품질") },
            { 1616, Encoding.UTF8.GetBytes("최고품질") },
            { 1617, Encoding.UTF8.GetBytes("수리") },
            { 1618, Encoding.UTF8.GetBytes("수리 재료") },
            { 1619, Encoding.UTF8.GetBytes("염색") },
            { 1620, Encoding.UTF8.GetBytes("성목") },
            { 1621, Encoding.UTF8.GetBytes("나무 베기") },
            { 1622, Encoding.UTF8.GetBytes("풀 베기") },
            { 1623, Encoding.UTF8.GetBytes("채굴장") },
            { 1624, Encoding.UTF8.GetBytes("채굴") },
            { 1625, Encoding.UTF8.GetBytes("암석 캐기") },
            { 1626, Encoding.UTF8.GetBytes("낚시") },
            { 1627, Encoding.UTF8.GetBytes("마테리아 장착") },
            { 1628, Encoding.UTF8.GetBytes("금단의 마테리아 장착") },
            { 1629, Encoding.UTF8.GetBytes("재배") },
            { 1630, Encoding.UTF8.GetBytes("육성") },
            { 1631, Encoding.UTF8.GetBytes("수확") },
            { 1632, Encoding.UTF8.GetBytes("비전서") },
            { 1633, Encoding.UTF8.GetBytes("분해") },
            { 1634, Encoding.UTF8.GetBytes("터주 낚시") },
            { 1635, Encoding.UTF8.GetBytes("놓아주기") },
            { 1636, Encoding.UTF8.GetBytes("미지의 채집 장소") },
            { 1637, Encoding.UTF8.GetBytes("소장품") },
            { 1638, Encoding.UTF8.GetBytes("전문 장인") },
            { 1639, Encoding.UTF8.GetBytes("호부") },
            { 1640, Encoding.UTF8.GetBytes("전승록") },
            { 1641, Encoding.UTF8.GetBytes("제작자용 화폐") },
            { 1642, Encoding.UTF8.GetBytes("채집자용 화폐") },
            { 1643, Encoding.UTF8.GetBytes("제작자용 화폐: 적화") },
            { 1644, Encoding.UTF8.GetBytes("제작자용 화폐: 청화") },
            { 1645, Encoding.UTF8.GetBytes("채집가용 화폐: 적화") },
            { 1646, Encoding.UTF8.GetBytes("채집가용 화폐: 청화") },
            { 1900, Encoding.UTF8.GetBytes("【야만신과 야만족】") },
            { 1901, Encoding.UTF8.GetBytes("야만신") },
            { 1902, Encoding.UTF8.GetBytes("이프리트") },
            { 1903, Encoding.UTF8.GetBytes("타이탄") },
            { 1904, Encoding.UTF8.GetBytes("가루다") },
            { 1905, Encoding.UTF8.GetBytes("바하무트") },
            { 1906, Encoding.UTF8.GetBytes("모그루 모그 12세") },
            { 1907, Encoding.UTF8.GetBytes("야만족") },
            { 1908, Encoding.UTF8.GetBytes("아말쟈") },
            { 1909, Encoding.UTF8.GetBytes("실프") },
            { 1910, Encoding.UTF8.GetBytes("이크살") },
            { 1911, Encoding.UTF8.GetBytes("코볼드") },
            { 1912, Encoding.UTF8.GetBytes("사하긴") },
            { 1913, Encoding.UTF8.GetBytes("리바이어선") },
            { 1914, Encoding.UTF8.GetBytes("라무") },
            { 1915, Encoding.UTF8.GetBytes("시바") },
            { 1916, Encoding.UTF8.GetBytes("알렉산더") },
            { 1917, Encoding.UTF8.GetBytes("라바나") },
            { 1918, Encoding.UTF8.GetBytes("비스마르크") },
            { 2000, Encoding.UTF8.GetBytes("【임무】") },
            { 2001, Encoding.UTF8.GetBytes("임무") },
            { 2002, Encoding.UTF8.GetBytes("퀘스트") },
            { 2003, Encoding.UTF8.GetBytes("주요 퀘스트") },
            { 2004, Encoding.UTF8.GetBytes("부가 퀘스트") },
            { 2005, Encoding.UTF8.GetBytes("클래스 퀘스트") },
            { 2006, Encoding.UTF8.GetBytes("잡 퀘스트") },
            { 2007, Encoding.UTF8.GetBytes("총사령부 퀘스트") },
            { 2008, Encoding.UTF8.GetBytes("돌발 임무") },
            { 2009, Encoding.UTF8.GetBytes("길드 의뢰") },
            { 2010, Encoding.UTF8.GetBytes("의뢰") },
            { 2011, Encoding.UTF8.GetBytes("용병업") },
            { 2012, Encoding.UTF8.GetBytes("채집업") },
            { 2013, Encoding.UTF8.GetBytes("제작업") },
            { 2015, Encoding.UTF8.GetBytes("총사령부 의뢰") },
            { 2017, Encoding.UTF8.GetBytes("의뢰 협동") },
            { 2018, Encoding.UTF8.GetBytes("의뢰 수주권") },
            { 2019, Encoding.UTF8.GetBytes("의뢰 난이도") },
            { 2020, Encoding.UTF8.GetBytes("길드 작전") },
            { 2021, Encoding.UTF8.GetBytes("던전") },
            { 2022, Encoding.UTF8.GetBytes("토벌전") },
            { 2023, Encoding.UTF8.GetBytes("토벌전") },
            { 2024, Encoding.UTF8.GetBytes("강습전") },
            { 2025, Encoding.UTF8.GetBytes("레이드") },
            { 2026, Encoding.UTF8.GetBytes("투기장") },
            { 2027, Encoding.UTF8.GetBytes("토토라크 감옥") },
            { 2028, Encoding.UTF8.GetBytes("탐타라 묘소") },
            { 2029, Encoding.UTF8.GetBytes("구리종 광산") },
            { 2030, Encoding.UTF8.GetBytes("사스타샤 침식 동굴") },
            { 2031, Encoding.UTF8.GetBytes("금빛 골짜기") },
            { 2032, Encoding.UTF8.GetBytes("하우케타 별궁") },
            { 2033, Encoding.UTF8.GetBytes("할라탈리 수련장") },
            { 2034, Encoding.UTF8.GetBytes("브레이플록스의 야영지") },
            { 2035, Encoding.UTF8.GetBytes("카른의 무너진 사원") },
            { 2036, Encoding.UTF8.GetBytes("방랑자의 궁전") },
            { 2037, Encoding.UTF8.GetBytes("돌방패 경계초소") },
            { 2038, Encoding.UTF8.GetBytes("나무꾼의 비명") },
            { 2039, Encoding.UTF8.GetBytes("제멜 요새") },
            { 2040, Encoding.UTF8.GetBytes("옛 암다포르 성") },
            { 2041, Encoding.UTF8.GetBytes("카스트룸 메리디아눔") },
            { 2042, Encoding.UTF8.GetBytes("마도성 프라이토리움") },
            { 2043, Encoding.UTF8.GetBytes("집단전 훈련을 완수하라!") },
            { 2044, Encoding.UTF8.GetBytes("방황하는 사령을 쓰러뜨려라!") },
            { 2045, Encoding.UTF8.GetBytes("관문을 돌파하고 최심부에 있는 적을 쓰러뜨려라!") },
            { 2046, Encoding.UTF8.GetBytes("길거북을 사로잡아라!") },
            { 2047, Encoding.UTF8.GetBytes("독성 요괴꽃을 제거하라!") },
            { 2048, Encoding.UTF8.GetBytes("무법자 '나나니단'을 섬멸하라!") },
            { 2049, Encoding.UTF8.GetBytes("몽환의 브라크시오를 쓰러뜨려라!") },
            { 2050, Encoding.UTF8.GetBytes("폭탄마 고블린 군단을 소탕하라!") },
            { 2051, Encoding.UTF8.GetBytes("오염원 몰볼을 쓰러뜨려라!") },
            { 2052, Encoding.UTF8.GetBytes("갱도에 나타난 요마 부소를 쓰러뜨려라!") },
            { 2053, Encoding.UTF8.GetBytes("무적의 부하를 조종하는 요마를 쓰러뜨려라!") },
            { 2054, Encoding.UTF8.GetBytes("봄들을 통솔하는 '봄 여왕'을 쓰러뜨려라!") },
            { 2055, Encoding.UTF8.GetBytes("불길한 진형을 짜는 요마를 섬멸하라!") },
            { 2056, Encoding.UTF8.GetBytes("세 거인족을 제압하여 유물을 지켜내라!") },
            { 2057, Encoding.UTF8.GetBytes("이프리트 토벌전") },
            { 2058, Encoding.UTF8.GetBytes("타이탄 토벌전") },
            { 2059, Encoding.UTF8.GetBytes("가루다 토벌전") },
            { 2060, Encoding.UTF8.GetBytes("진 이프리트 토벌전") },
            { 2061, Encoding.UTF8.GetBytes("진 타이탄 토벌전") },
            { 2062, Encoding.UTF8.GetBytes("진 가루다 토벌전") },
            { 2063, Encoding.UTF8.GetBytes("리트아틴 강습전") },
            { 2064, Encoding.UTF8.GetBytes("대미궁 바하무트") },
            { 2065, Encoding.UTF8.GetBytes("늑대우리") },
            { 2066, Encoding.UTF8.GetBytes("극 이프리트 토벌전") },
            { 2067, Encoding.UTF8.GetBytes("극 타이탄 토벌전") },
            { 2068, Encoding.UTF8.GetBytes("극 가루다 토벌전") },
            { 2069, Encoding.UTF8.GetBytes("선왕 모그루 모그 12세 토벌전") },
            { 2070, Encoding.UTF8.GetBytes("알테마 웨폰 파괴작전") },
            { 2071, Encoding.UTF8.GetBytes("크리스탈 타워") },
            { 2072, Encoding.UTF8.GetBytes("해후편") },
            { 2073, Encoding.UTF8.GetBytes("고대인의 미궁") },
            { 2074, Encoding.UTF8.GetBytes("지도 해독") },
            { 2075, Encoding.UTF8.GetBytes("어려움") },
            { 2076, Encoding.UTF8.GetBytes("무작위 임무") },
            { 2077, Encoding.UTF8.GetBytes("침공편") },
            { 2078, Encoding.UTF8.GetBytes("시리우스 대등대") },
            { 2079, Encoding.UTF8.GetBytes("극왕 모그루 모그 12세 토벌전") },
            { 2080, Encoding.UTF8.GetBytes("진 리바이어선 토벌전") },
            { 2081, Encoding.UTF8.GetBytes("극 리바이어선 토벌전") },
            { 2082, Encoding.UTF8.GetBytes("도름 키마이라 토벌전") },
            { 2083, Encoding.UTF8.GetBytes("하이드라 토벌전") },
            { 2084, Encoding.UTF8.GetBytes("길가메시 토벌전") },
            { 2085, Encoding.UTF8.GetBytes("PvP") },
            { 2086, Encoding.UTF8.GetBytes("야만족 퀘스트") },
            { 2087, Encoding.UTF8.GetBytes("야만족 일일 퀘스트") },
            { 2088, Encoding.UTF8.GetBytes("야만족 스토리 퀘스트") },
            { 2089, Encoding.UTF8.GetBytes("외전 퀘스트") },
            { 2090, Encoding.UTF8.GetBytes("보물찾기") },
            { 2091, Encoding.UTF8.GetBytes("연대기 퀘스트") },
            { 2092, Encoding.UTF8.GetBytes("기간 한정 이벤트") },
            { 2093, Encoding.UTF8.GetBytes("옛 암다포르 시가지") },
            { 2094, Encoding.UTF8.GetBytes("황도십이문서") },
            { 2095, Encoding.UTF8.GetBytes("천공의 두루마리") },
            { 2096, Encoding.UTF8.GetBytes("마물 사냥") },
            { 2097, Encoding.UTF8.GetBytes("정예 마물") },
            { 2098, Encoding.UTF8.GetBytes("진 라무 토벌전") },
            { 2099, Encoding.UTF8.GetBytes("극 라무 토벌전") },
            { 2100, Encoding.UTF8.GetBytes("시르쿠스 탑") },
            { 2101, Encoding.UTF8.GetBytes("대미궁 바하무트(영웅)") },
            { 2102, Encoding.UTF8.GetBytes("카르테노 평원") },
            { 2103, Encoding.UTF8.GetBytes("난파선의 섬") },
            { 2104, Encoding.UTF8.GetBytes("전장") },
            { 2105, Encoding.UTF8.GetBytes("저레벨") },
            { 2106, Encoding.UTF8.GetBytes("숙련자") },
            { 2107, Encoding.UTF8.GetBytes("고레벨") },
            { 2108, Encoding.UTF8.GetBytes("진성편") },
            { 2109, Encoding.UTF8.GetBytes("진 시바 토벌전") },
            { 2110, Encoding.UTF8.GetBytes("극 시바 토벌전") },
            { 2111, Encoding.UTF8.GetBytes("얼음외투 대빙벽") },
            { 2112, Encoding.UTF8.GetBytes("아마지나배 투기대회 결승전") },
            { 2113, Encoding.UTF8.GetBytes("납품 퀘스트") },
            { 2114, Encoding.UTF8.GetBytes("투신 오딘 토벌전") },
            { 2115, Encoding.UTF8.GetBytes("어둠의 세계") },
            { 2116, Encoding.UTF8.GetBytes("외곽 유적지대") },
            { 2117, Encoding.UTF8.GetBytes("제압전") },
            { 2118, Encoding.UTF8.GetBytes("섬멸전") },
            { 2119, Encoding.UTF8.GetBytes("묵약의 탑") },
            { 2120, Encoding.UTF8.GetBytes("진 길가메시 토벌전") },
            { 2121, Encoding.UTF8.GetBytes("아씨엔") },
            { 2122, Encoding.UTF8.GetBytes("보이드") },
            { 2123, Encoding.UTF8.GetBytes("구브라 환상도서관") },
            { 2124, Encoding.UTF8.GetBytes("거두지 않는 섬") },
            { 2125, Encoding.UTF8.GetBytes("이슈가르드 교황청") },
            { 2126, Encoding.UTF8.GetBytes("무한연속 박물함") },
            { 2127, Encoding.UTF8.GetBytes("어스름 요새") },
            { 2128, Encoding.UTF8.GetBytes("솜 알") },
            { 2129, Encoding.UTF8.GetBytes("마과학 연구소") },
            { 2130, Encoding.UTF8.GetBytes("용의 둥지") },
            { 2131, Encoding.UTF8.GetBytes("진 라바나 토벌전") },
            { 2132, Encoding.UTF8.GetBytes("극 라바나 토벌전") },
            { 2133, Encoding.UTF8.GetBytes("진 비스마르크 토벌전") },
            { 2134, Encoding.UTF8.GetBytes("극 비스마르크 토벌전") },
            { 2135, Encoding.UTF8.GetBytes("봉인된 바위섬") },
            { 2136, Encoding.UTF8.GetBytes("쟁탈전") },
            { 2137, Encoding.UTF8.GetBytes("기공성 알렉산더") },
            { 2138, Encoding.UTF8.GetBytes("기공성 알렉산더(영웅)") },
            { 2139, Encoding.UTF8.GetBytes("기동편") },
            { 2140, Encoding.UTF8.GetBytes("아씨엔 나브리알레스 토벌전") },
            { 2141, Encoding.UTF8.GetBytes("성도 이슈가르드 방어전") },
            { 2142, Encoding.UTF8.GetBytes("나이츠 오브 라운드 토벌전") },
            { 2200, Encoding.UTF8.GetBytes("【탈것】") },
            { 2201, Encoding.UTF8.GetBytes("【클래스와 잡】") },
            { 2202, Encoding.UTF8.GetBytes("【지명】") },
            { 2203, Encoding.UTF8.GetBytes("【민족】") },
            { 2204, Encoding.UTF8.GetBytes("【부족】") },
            { 2205, Encoding.UTF8.GetBytes("【수호신】") },
            { 2206, Encoding.UTF8.GetBytes("【일반 기술】") },
            { 2207, Encoding.UTF8.GetBytes("【기술】") },
            { 2208, Encoding.UTF8.GetBytes("【제작 기술】") },
            { 2209, Encoding.UTF8.GetBytes("【버디 기술】") },
            { 2210, Encoding.UTF8.GetBytes("【소환수 기술】") },
            { 2211, Encoding.UTF8.GetBytes("【날씨】") },
            { 2212, Encoding.UTF8.GetBytes("【주 메뉴】") },
            { 2213, Encoding.UTF8.GetBytes("【텍스트 명령어】") },
            { 2214, Encoding.UTF8.GetBytes("【PvP 기술】") },
            { 2215, Encoding.UTF8.GetBytes("【소환수】") },
            { 2216, Encoding.UTF8.GetBytes("【꼬마 친구】") },
            { 3000, Encoding.UTF8.GetBytes("【골드 소서】") },
            { 3001, Encoding.UTF8.GetBytes("초코보 경주") },
            { 3002, Encoding.UTF8.GetBytes("경주 초코보") },
            { 3003, Encoding.UTF8.GetBytes("신입 초코보") },
            { 3004, Encoding.UTF8.GetBytes("은퇴 초코보") },
            { 3005, Encoding.UTF8.GetBytes("교배") },
            { 3006, Encoding.UTF8.GetBytes("체급") },
            { 3007, Encoding.UTF8.GetBytes("혈통 레벨") },
            { 3008, Encoding.UTF8.GetBytes("무작위 코스") },
            { 3009, Encoding.UTF8.GetBytes("사골리 사막") },
            { 3010, Encoding.UTF8.GetBytes("고요한 야영지") },
            { 3011, Encoding.UTF8.GetBytes("트리플 트라이어드") },
            { 3012, Encoding.UTF8.GetBytes("카드") },
            { 3013, Encoding.UTF8.GetBytes("카드 유형") },
            { 3014, Encoding.UTF8.GetBytes("희귀도") },
            { 3015, Encoding.UTF8.GetBytes("대결") },
            { 3016, Encoding.UTF8.GetBytes("대회") },
            { 3017, Encoding.UTF8.GetBytes("토너먼트") },
            { 3018, Encoding.UTF8.GetBytes("승점") },
            { 3019, Encoding.UTF8.GetBytes("특수 규칙") },
            { 3020, Encoding.UTF8.GetBytes("유행 규칙") },
            { 3021, Encoding.UTF8.GetBytes("경기 규칙") },
            { 3022, Encoding.UTF8.GetBytes("대회 규칙") },
            { 3023, Encoding.UTF8.GetBytes("모두 공개") },
            { 3024, Encoding.UTF8.GetBytes("3장 공개") },
            { 3025, Encoding.UTF8.GetBytes("동수") },
            { 3026, Encoding.UTF8.GetBytes("연장전") },
            { 3027, Encoding.UTF8.GetBytes("합산") },
            { 3028, Encoding.UTF8.GetBytes("무작위 패") },
            { 3029, Encoding.UTF8.GetBytes("순서대로") },
            { 3030, Encoding.UTF8.GetBytes("무작위 순서") },
            { 3031, Encoding.UTF8.GetBytes("역전") },
            { 3032, Encoding.UTF8.GetBytes("에이스 약화") },
            { 3033, Encoding.UTF8.GetBytes("유형 강화") },
            { 3034, Encoding.UTF8.GetBytes("유형 약화") },
            { 3035, Encoding.UTF8.GetBytes("카드 교환") },
            { 3036, Encoding.UTF8.GetBytes("무작위 규칙") },
            { 3037, Encoding.UTF8.GetBytes("덱") },
            { 3038, Encoding.UTF8.GetBytes("원하는 규칙") },
            { 3039, Encoding.UTF8.GetBytes("돌발 게임") },
            { 3040, Encoding.UTF8.GetBytes("복권") },
            { 3041, Encoding.UTF8.GetBytes("주간 복권") },
            { 3042, Encoding.UTF8.GetBytes("일일 복권") },
            { 3043, Encoding.UTF8.GetBytes("당첨번호") },
        };
    }
}
