using System.Collections.Generic;
using System.Text;

namespace FFChat
{
    static partial class FFData
    {
        public static readonly IDictionary<int, byte[]> Companion = new Dictionary<int, byte[]>
        {
            { 1, Encoding.UTF8.GetBytes("꼬마 봄") },
            { 2, Encoding.UTF8.GetBytes("자동인형001") },
            { 3, Encoding.UTF8.GetBytes("초코초코보") },
            { 4, Encoding.UTF8.GetBytes("캐트시 인형") },
            { 5, Encoding.UTF8.GetBytes("베이비모스") },
            { 6, Encoding.UTF8.GetBytes("자동인형003L") },
            { 7, Encoding.UTF8.GetBytes("자동인형003G") },
            { 8, Encoding.UTF8.GetBytes("자동인형003U") },
            { 9, Encoding.UTF8.GetBytes("흑와단 초코초코보") },
            { 10, Encoding.UTF8.GetBytes("쌍사당 초코초코보") },
            { 11, Encoding.UTF8.GetBytes("불멸대 초코초코보") },
            { 12, Encoding.UTF8.GetBytes("몰볼 묘목") },
            { 13, Encoding.UTF8.GetBytes("꼬마 청설모") },
            { 14, Encoding.UTF8.GetBytes("애송이버섯") },
            { 15, Encoding.UTF8.GetBytes("벼룩모기 유충") },
            { 16, Encoding.UTF8.GetBytes("파랑새") },
            { 17, Encoding.UTF8.GetBytes("꼬마 영양") },
            { 18, Encoding.UTF8.GetBytes("아기 임프") },
            { 19, Encoding.UTF8.GetBytes("꼬마 커얼") },
            { 20, Encoding.UTF8.GetBytes("검은 커얼") },
            { 21, Encoding.UTF8.GetBytes("힐디 인형") },
            { 22, Encoding.UTF8.GetBytes("자갈 골렘") },
            { 23, Encoding.UTF8.GetBytes("톤베리 인형") },
            { 24, Encoding.UTF8.GetBytes("꼬마 금강거북") },
            { 25, Encoding.UTF8.GetBytes("아기 랍토르") },
            { 26, Encoding.UTF8.GetBytes("아기 박쥐") },
            { 27, Encoding.UTF8.GetBytes("꼬마 묘목") },
            { 28, Encoding.UTF8.GetBytes("먼지토끼") },
            { 29, Encoding.UTF8.GetBytes("듈라한 인형") },
            { 30, Encoding.UTF8.GetBytes("왕올챙이") },
            { 31, Encoding.UTF8.GetBytes("통통푸크") },
            { 32, Encoding.UTF8.GetBytes("꼬마 물소") },
            { 33, Encoding.UTF8.GetBytes("미니텐더") },
            { 34, Encoding.UTF8.GetBytes("아기 게") },
            { 35, Encoding.UTF8.GetBytes("아기 늑대") },
            { 36, Encoding.UTF8.GetBytes("꼬마 눈알") },
            { 37, Encoding.UTF8.GetBytes("꼬마 도도") },
            { 38, Encoding.UTF8.GetBytes("코브란 유충") },
            { 39, Encoding.UTF8.GetBytes("큰뿔염소 인형") },
            { 40, Encoding.UTF8.GetBytes("꼬마 아프칼루") },
            { 41, Encoding.UTF8.GetBytes("새싹 구부") },
            { 42, Encoding.UTF8.GetBytes("미니 푸딩") },
            { 43, Encoding.UTF8.GetBytes("마도 뱅가드 추종형") },
            { 44, Encoding.UTF8.GetBytes("악마의 벽돌") },
            { 45, Encoding.UTF8.GetBytes("작은 두더지") },
            { 46, Encoding.UTF8.GetBytes("꼬마 양") },
            { 47, Encoding.UTF8.GetBytes("작은 슬라임") },
            { 48, Encoding.UTF8.GetBytes("작은 만드라고라") },
            { 49, Encoding.UTF8.GetBytes("고블린 인형") },
            { 50, Encoding.UTF8.GetBytes("실프 인형") },
            { 51, Encoding.UTF8.GetBytes("자동 커서") },
            { 52, Encoding.UTF8.GetBytes("무적호 모형") },
            { 53, Encoding.UTF8.GetBytes("키키룬 인형") },
            { 54, Encoding.UTF8.GetBytes("검은 초코초코보") },
            { 55, Encoding.UTF8.GetBytes("달라가브 인형") },
            { 56, Encoding.UTF8.GetBytes("정신지배아") },
            { 57, Encoding.UTF8.GetBytes("말 없는 콜리브리") },
            { 58, Encoding.UTF8.GetBytes("아말쟈 인형") },
            { 59, Encoding.UTF8.GetBytes("이크살 인형") },
            { 60, Encoding.UTF8.GetBytes("코볼드 인형") },
            { 61, Encoding.UTF8.GetBytes("사하긴 인형") },
            { 62, Encoding.UTF8.GetBytes("골레무스") },
            { 63, Encoding.UTF8.GetBytes("샨토토 인형") },
            { 64, Encoding.UTF8.GetBytes("에드비아 인형") },
            { 65, Encoding.UTF8.GetBytes("태엽 태양") },
            { 66, Encoding.UTF8.GetBytes("푹신푹신 방석") },
            { 67, Encoding.UTF8.GetBytes("빛의 인형") },
            { 68, Encoding.UTF8.GetBytes("빛의 인형") },
            { 69, Encoding.UTF8.GetBytes("빛의 인형") },
            { 70, Encoding.UTF8.GetBytes("빛의 인형") },
            { 71, Encoding.UTF8.GetBytes("지도자 인형") },
            { 72, Encoding.UTF8.GetBytes("멜위브 인형") },
            { 73, Encoding.UTF8.GetBytes("카느 에 센나 인형") },
            { 74, Encoding.UTF8.GetBytes("라우반 인형") },
            { 75, Encoding.UTF8.GetBytes("초코초코보 왕자") },
            { 76, Encoding.UTF8.GetBytes("오딘 인형") },
            { 77, Encoding.UTF8.GetBytes("빛의 전사 인형") },
            { 78, Encoding.UTF8.GetBytes("바하무트 인형") },
            { 79, Encoding.UTF8.GetBytes("모그리 인형") },
            { 80, Encoding.UTF8.GetBytes("아기 오포오포") },
            { 81, Encoding.UTF8.GetBytes("빗자루 인형") },
            { 82, Encoding.UTF8.GetBytes("서큐버스 인형") },
            { 83, Encoding.UTF8.GetBytes("어린 즈") },
            { 84, Encoding.UTF8.GetBytes("나나모 인형") },
            { 85, Encoding.UTF8.GetBytes("길가메시 인형") },
            { 86, Encoding.UTF8.GetBytes("양파 왕자") },
            { 87, Encoding.UTF8.GetBytes("가지 기사") },
            { 88, Encoding.UTF8.GetBytes("마늘 광대") },
            { 89, Encoding.UTF8.GetBytes("토마토 왕") },
            { 90, Encoding.UTF8.GetBytes("만드라 왕비") },
            { 91, Encoding.UTF8.GetBytes("야슈톨라 인형") },
            { 92, Encoding.UTF8.GetBytes("양파 인형") },
            { 93, Encoding.UTF8.GetBytes("보물상자") },
            { 94, Encoding.UTF8.GetBytes("꼬마 맥") },
            { 95, Encoding.UTF8.GetBytes("나나 곰인형") },
            { 96, Encoding.UTF8.GetBytes("태엽 수레") },
            { 97, Encoding.UTF8.GetBytes("너츠 이터") },
            { 98, Encoding.UTF8.GetBytes("민필리아 인형") },
            { 99, Encoding.UTF8.GetBytes("산크레드 인형") },
            { 100, Encoding.UTF8.GetBytes("마도 비트 자율형") },
            { 101, Encoding.UTF8.GetBytes("옅은 어둠의 구름") },
            { 102, Encoding.UTF8.GetBytes("꼬마 낭카") },
            { 104, Encoding.UTF8.GetBytes("오르트로스 인형") },
            { 105, Encoding.UTF8.GetBytes("눈사람 인형") },
            { 106, Encoding.UTF8.GetBytes("통통 초코보") },
            { 107, Encoding.UTF8.GetBytes("이다 인형") },
            { 108, Encoding.UTF8.GetBytes("파파리모 인형") },
            { 109, Encoding.UTF8.GetBytes("위리앙제 인형") },
            { 110, Encoding.UTF8.GetBytes("뚱냥이") },
            { 111, Encoding.UTF8.GetBytes("리틀풋") },
            { 112, Encoding.UTF8.GetBytes("작은 미라") },
            { 113, Encoding.UTF8.GetBytes("엔터프라이즈 모형") },
            { 114, Encoding.UTF8.GetBytes("배달부 모그리 인형") },
            { 115, Encoding.UTF8.GetBytes("암살어") },
            { 116, Encoding.UTF8.GetBytes("선물 상자") },
            { 117, Encoding.UTF8.GetBytes("꼬마 물요정") },
            { 118, Encoding.UTF8.GetBytes("루이수아 인형") },
            { 119, Encoding.UTF8.GetBytes("미드가르드오름") },
            { 120, Encoding.UTF8.GetBytes("초록틀") },
            { 121, Encoding.UTF8.GetBytes("깍깍이") },
            { 122, Encoding.UTF8.GetBytes("엔키두") },
            { 123, Encoding.UTF8.GetBytes("보랏빛 인형") },
            { 124, Encoding.UTF8.GetBytes("선구자 인형") },
            { 125, Encoding.UTF8.GetBytes("데즐 인형") },
            { 126, Encoding.UTF8.GetBytes("코볼드 2호") },
            { 127, Encoding.UTF8.GetBytes("바다의 악마") },
            { 128, Encoding.UTF8.GetBytes("검은 초코초코보 비행사") },
            { 129, Encoding.UTF8.GetBytes("카인 인형") },
            { 130, Encoding.UTF8.GetBytes("알피노 인형") },
            { 131, Encoding.UTF8.GetBytes("알리제 인형") },
            { 132, Encoding.UTF8.GetBytes("타타루 인형") },
            { 133, Encoding.UTF8.GetBytes("시드 인형") },
            { 134, Encoding.UTF8.GetBytes("유니콜트") },
            { 136, Encoding.UTF8.GetBytes("미니멈 아토모스") },
            { 137, Encoding.UTF8.GetBytes("아기 올빼미") },
            { 138, Encoding.UTF8.GetBytes("미운 아기 오리") },
            { 139, Encoding.UTF8.GetBytes("게일리키튼") },
            { 140, Encoding.UTF8.GetBytes("태엽 손수레") },
            { 141, Encoding.UTF8.GetBytes("레서판다") },
            { 142, Encoding.UTF8.GetBytes("63페이지") },
            { 143, Encoding.UTF8.GetBytes("쇠난쟁이") },
            { 144, Encoding.UTF8.GetBytes("아기 그리핀") },
            { 145, Encoding.UTF8.GetBytes("이젤 인형") },
            { 146, Encoding.UTF8.GetBytes("가스트라") },
            { 147, Encoding.UTF8.GetBytes("VII호 증기 워커") },
            { 148, Encoding.UTF8.GetBytes("로열 베이비모스") },
            { 149, Encoding.UTF8.GetBytes("추종 시스템") },
            { 150, Encoding.UTF8.GetBytes("유우기리 인형") },
            { 151, Encoding.UTF8.GetBytes("카벙클 페리도트") },
            { 152, Encoding.UTF8.GetBytes("카벙클 헬리오도르") },
            { 154, Encoding.UTF8.GetBytes("노다지") },
            { 155, Encoding.UTF8.GetBytes("모그리 음악단") },
            { 159, Encoding.UTF8.GetBytes("호박 집사") },
            { 167, Encoding.UTF8.GetBytes("프리오닐 인형") },
        };
    }
}
