using System.Collections.Generic;
using System.Text;

namespace FFChat
{
    static partial class FFData
    {
        public static readonly IDictionary<int, byte[]> PlaceName = new Dictionary<int, byte[]>
        {
            { 18, Encoding.UTF8.GetBytes("길드 의뢰") },
            { 20, Encoding.UTF8.GetBytes("하이델린") },
            { 21, Encoding.UTF8.GetBytes("에오르제아") },
            { 22, Encoding.UTF8.GetBytes("라노시아") },
            { 23, Encoding.UTF8.GetBytes("검은장막 숲") },
            { 24, Encoding.UTF8.GetBytes("다날란") },
            { 25, Encoding.UTF8.GetBytes("커르다스") },
            { 26, Encoding.UTF8.GetBytes("모르도나") },
            { 27, Encoding.UTF8.GetBytes("림사 로민사") },
            { 28, Encoding.UTF8.GetBytes("림사 로민사 상층 갑판") },
            { 29, Encoding.UTF8.GetBytes("림사 로민사 하층 갑판") },
            { 30, Encoding.UTF8.GetBytes("중부 라노시아") },
            { 31, Encoding.UTF8.GetBytes("저지 라노시아") },
            { 32, Encoding.UTF8.GetBytes("동부 라노시아") },
            { 33, Encoding.UTF8.GetBytes("서부 라노시아") },
            { 34, Encoding.UTF8.GetBytes("고지 라노시아") },
            { 35, Encoding.UTF8.GetBytes("사스타샤 침식 동굴") },
            { 36, Encoding.UTF8.GetBytes("브레이플록스의 야영지") },
            { 37, Encoding.UTF8.GetBytes("방랑자의 궁전") },
            { 39, Encoding.UTF8.GetBytes("울다하") },
            { 40, Encoding.UTF8.GetBytes("울다하 날 회랑") },
            { 41, Encoding.UTF8.GetBytes("울다하 달 회랑") },
            { 42, Encoding.UTF8.GetBytes("서부 다날란") },
            { 43, Encoding.UTF8.GetBytes("중부 다날란") },
            { 44, Encoding.UTF8.GetBytes("동부 다날란") },
            { 45, Encoding.UTF8.GetBytes("남부 다날란") },
            { 46, Encoding.UTF8.GetBytes("북부 다날란") },
            { 47, Encoding.UTF8.GetBytes("나무꾼의 비명") },
            { 48, Encoding.UTF8.GetBytes("구리종 광산") },
            { 49, Encoding.UTF8.GetBytes("할라탈리 수련장") },
            { 50, Encoding.UTF8.GetBytes("카른의 무너진 사원") },
            { 51, Encoding.UTF8.GetBytes("그리다니아") },
            { 52, Encoding.UTF8.GetBytes("그리다니아 신시가지") },
            { 53, Encoding.UTF8.GetBytes("그리다니아 구시가지") },
            { 54, Encoding.UTF8.GetBytes("검은장막 숲 중부삼림") },
            { 55, Encoding.UTF8.GetBytes("검은장막 숲 동부삼림") },
            { 56, Encoding.UTF8.GetBytes("검은장막 숲 남부삼림") },
            { 57, Encoding.UTF8.GetBytes("검은장막 숲 북부삼림") },
            { 58, Encoding.UTF8.GetBytes("탐타라 묘소") },
            { 59, Encoding.UTF8.GetBytes("하우케타 별궁") },
            { 61, Encoding.UTF8.GetBytes("토토라크 감옥") },
            { 62, Encoding.UTF8.GetBytes("이슈가르드") },
            { 63, Encoding.UTF8.GetBytes("커르다스 중앙고지") },
            { 64, Encoding.UTF8.GetBytes("제멜 요새") },
            { 65, Encoding.UTF8.GetBytes("금빛 골짜기") },
            { 67, Encoding.UTF8.GetBytes("모르도나") },
            { 68, Encoding.UTF8.GetBytes("비취 호수") },
            { 69, Encoding.UTF8.GetBytes("숲눈물 벌채지") },
            { 70, Encoding.UTF8.GetBytes("굽은가지 가도") },
            { 71, Encoding.UTF8.GetBytes("수영풀 쉼터") },
            { 72, Encoding.UTF8.GetBytes("송장나무 숲") },
            { 73, Encoding.UTF8.GetBytes("벌꿀 마당") },
            { 74, Encoding.UTF8.GetBytes("아홉덩굴 숲") },
            { 75, Encoding.UTF8.GetBytes("가시나무 숲") },
            { 76, Encoding.UTF8.GetBytes("종달새의 지저귐") },
            { 77, Encoding.UTF8.GetBytes("실프 영지") },
            { 78, Encoding.UTF8.GetBytes("높은길") },
            { 79, Encoding.UTF8.GetBytes("낮은길") },
            { 80, Encoding.UTF8.GetBytes("뱀허물 숲") },
            { 81, Encoding.UTF8.GetBytes("침묵의 화단") },
            { 82, Encoding.UTF8.GetBytes("우르드의 선물") },
            { 83, Encoding.UTF8.GetBytes("소근소근 덤불") },
            { 84, Encoding.UTF8.GetBytes("평온의 정원") },
            { 85, Encoding.UTF8.GetBytes("오리나무 샘") },
            { 86, Encoding.UTF8.GetBytes("영광의 개울") },
            { 87, Encoding.UTF8.GetBytes("푸른 오소리 관문") },
            { 88, Encoding.UTF8.GetBytes("하얀 늑대 관문") },
            { 89, Encoding.UTF8.GetBytes("길버트 감시초소") },
            { 90, Encoding.UTF8.GetBytes("배넉 연병장") },
            { 91, Encoding.UTF8.GetBytes("가비노의 오두막") },
            { 92, Encoding.UTF8.GetBytes("맨바위 언덕") },
            { 93, Encoding.UTF8.GetBytes("워렌 감옥") },
            { 94, Encoding.UTF8.GetBytes("굽은가지 목장") },
            { 95, Encoding.UTF8.GetBytes("갈반스 감시초소") },
            { 96, Encoding.UTF8.GetBytes("대지신의 망각") },
            { 97, Encoding.UTF8.GetBytes("탐타라 묘소") },
            { 98, Encoding.UTF8.GetBytes("거울못 나루") },
            { 99, Encoding.UTF8.GetBytes("수련암") },
            { 100, Encoding.UTF8.GetBytes("울타리나무") },
            { 101, Encoding.UTF8.GetBytes("영원그늘") },
            { 102, Encoding.UTF8.GetBytes("하우케타 별궁") },
            { 103, Encoding.UTF8.GetBytes("공물단") },
            { 104, Encoding.UTF8.GetBytes("움트는 연못") },
            { 105, Encoding.UTF8.GetBytes("비늘바위") },
            { 106, Encoding.UTF8.GetBytes("스프리건 소굴") },
            { 107, Encoding.UTF8.GetBytes("호손 일가의 산장") },
            { 108, Encoding.UTF8.GetBytes("울타리나무") },
            { 110, Encoding.UTF8.GetBytes("아마리세 감시초소") },
            { 111, Encoding.UTF8.GetBytes("카스트룸 오리엔스") },
            { 112, Encoding.UTF8.GetBytes("열두 신 대성당") },
            { 113, Encoding.UTF8.GetBytes("실프 임시 주거지") },
            { 114, Encoding.UTF8.GetBytes("달빛홀씨 숲") },
            { 115, Encoding.UTF8.GetBytes("요람나무") },
            { 116, Encoding.UTF8.GetBytes("금빛잎새 단") },
            { 117, Encoding.UTF8.GetBytes("대롱대롱 꽈리") },
            { 118, Encoding.UTF8.GetBytes("버스카론 감시소 옛터") },
            { 119, Encoding.UTF8.GetBytes("주점 '버스카론 맘대로'") },
            { 120, Encoding.UTF8.GetBytes("토토라크 감옥") },
            { 121, Encoding.UTF8.GetBytes("이솜하 구덩이") },
            { 122, Encoding.UTF8.GetBytes("주인 없는 암자") },
            { 123, Encoding.UTF8.GetBytes("고요한 야영지") },
            { 125, Encoding.UTF8.GetBytes("옛 암다포르 시가지") },
            { 126, Encoding.UTF8.GetBytes("징검뿌리 늪지대") },
            { 127, Encoding.UTF8.GetBytes("남부삼림 발착장") },
            { 128, Encoding.UTF8.GetBytes("옛 암다포르 성") },
            { 129, Encoding.UTF8.GetBytes("채석공방") },
            { 130, Encoding.UTF8.GetBytes("붉은둔덕 요새") },
            { 131, Encoding.UTF8.GetBytes("고블린족 야영지") },
            { 132, Encoding.UTF8.GetBytes("낙엽 유입지") },
            { 133, Encoding.UTF8.GetBytes("우르드의 샘") },
            { 135, Encoding.UTF8.GetBytes("노란 뱀 관문") },
            { 136, Encoding.UTF8.GetBytes("소근소근 조련소") },
            { 137, Encoding.UTF8.GetBytes("에 타타 감시초소") },
            { 138, Encoding.UTF8.GetBytes("울타리나무") },
            { 139, Encoding.UTF8.GetBytes("숲언덕 공방") },
            { 140, Encoding.UTF8.GetBytes("가을박 마을") },
            { 141, Encoding.UTF8.GetBytes("둥둥 뜬 코르크 여관") },
            { 142, Encoding.UTF8.GetBytes("플로렌텔 감시초소") },
            { 143, Encoding.UTF8.GetBytes("산길잡이 바위굴") },
            { 144, Encoding.UTF8.GetBytes("겔모라 유적") },
            { 145, Encoding.UTF8.GetBytes("이크살군 벌채장") },
            { 146, Encoding.UTF8.GetBytes("유지니아 감시초소") },
            { 147, Encoding.UTF8.GetBytes("임시 대미궁 바하무트") },
            { 151, Encoding.UTF8.GetBytes("여관 '둥지나무'") },
            { 152, Encoding.UTF8.GetBytes("에오르제아 지하공간") },
            { 153, Encoding.UTF8.GetBytes("모르디온 감옥") },
            { 154, Encoding.UTF8.GetBytes("늑대우리") },
            { 155, Encoding.UTF8.GetBytes("꽃꿀 나루") },
            { 156, Encoding.UTF8.GetBytes("서쪽 잎맥") },
            { 157, Encoding.UTF8.GetBytes("동쪽 잎맥") },
            { 158, Encoding.UTF8.GetBytes("조슬랑 감시초소") },
            { 159, Encoding.UTF8.GetBytes("들꽃만발 양봉장") },
            { 160, Encoding.UTF8.GetBytes("정령 깃든 어린나무") },
            { 161, Encoding.UTF8.GetBytes("산들바람 줄기") },
            { 162, Encoding.UTF8.GetBytes("여름여울") },
            { 163, Encoding.UTF8.GetBytes("삼 말름 굽잇길") },
            { 164, Encoding.UTF8.GetBytes("모라비 만") },
            { 165, Encoding.UTF8.GetBytes("삼나무 숲") },
            { 166, Encoding.UTF8.GetBytes("신의 손아귀") },
            { 167, Encoding.UTF8.GetBytes("핏빛해안") },
            { 168, Encoding.UTF8.GetBytes("빗물받이 숲") },
            { 169, Encoding.UTF8.GetBytes("아젤리스 옛 가도") },
            { 170, Encoding.UTF8.GetBytes("쿼터스톤") },
            { 171, Encoding.UTF8.GetBytes("해골 골짜기") },
            { 172, Encoding.UTF8.GetBytes("하프스톤") },
            { 173, Encoding.UTF8.GetBytes("환영 제도") },
            { 174, Encoding.UTF8.GetBytes("참나무 숲") },
            { 175, Encoding.UTF8.GetBytes("기나긴 오르막") },
            { 176, Encoding.UTF8.GetBytes("무쇠호수") },
            { 177, Encoding.UTF8.GetBytes("청동호수") },
            { 178, Encoding.UTF8.GetBytes("젤마 계곡") },
            { 179, Encoding.UTF8.GetBytes("산들바람 관문") },
            { 180, Encoding.UTF8.GetBytes("갈라디온 만") },
            { 181, Encoding.UTF8.GetBytes("데네벨 가도") },
            { 182, Encoding.UTF8.GetBytes("불량배 강") },
            { 183, Encoding.UTF8.GetBytes("라다그란 관문") },
            { 184, Encoding.UTF8.GetBytes("여름여울 농장") },
            { 185, Encoding.UTF8.GetBytes("바다노래 석굴") },
            { 186, Encoding.UTF8.GetBytes("아젤리스 강") },
            { 187, Encoding.UTF8.GetBytes("가마솥 공터") },
            { 188, Encoding.UTF8.GetBytes("개척자의 헛간") },
            { 189, Encoding.UTF8.GetBytes("낭떠러지 절벽") },
            { 190, Encoding.UTF8.GetBytes("하늘승강기") },
            { 191, Encoding.UTF8.GetBytes("데네벨 관문") },
            { 192, Encoding.UTF8.GetBytes("속삭임 골짜기") },
            { 193, Encoding.UTF8.GetBytes("니므 강") },
            { 194, Encoding.UTF8.GetBytes("앞돛대 탑") },
            { 195, Encoding.UTF8.GetBytes("미아교") },
            { 196, Encoding.UTF8.GetBytes("안경 바위") },
            { 197, Encoding.UTF8.GetBytes("과부의 눈물") },
            { 198, Encoding.UTF8.GetBytes("폭풍 관문") },
            { 199, Encoding.UTF8.GetBytes("오쉬온 대교") },
            { 200, Encoding.UTF8.GetBytes("붉은수탉 농장") },
            { 201, Encoding.UTF8.GetBytes("회색함대 풍차마을") },
            { 202, Encoding.UTF8.GetBytes("눈먼 무쇠 갱도") },
            { 203, Encoding.UTF8.GetBytes("라다그란 가도") },
            { 204, Encoding.UTF8.GetBytes("버려진 폐가") },
            { 205, Encoding.UTF8.GetBytes("흰갈매기 탑") },
            { 206, Encoding.UTF8.GetBytes("코스타 델 솔") },
            { 207, Encoding.UTF8.GetBytes("아젤리스 강") },
            { 208, Encoding.UTF8.GetBytes("선착장") },
            { 209, Encoding.UTF8.GetBytes("갈록의 보금자리") },
            { 210, Encoding.UTF8.GetBytes("선착장: 숨겨진 폭포") },
            { 211, Encoding.UTF8.GetBytes("숨겨진 폭포") },
            { 212, Encoding.UTF8.GetBytes("브레이플록스의 야영지") },
            { 213, Encoding.UTF8.GetBytes("끊어진 가죽끈 주막") },
            { 214, Encoding.UTF8.GetBytes("붉은사마귀 폭포") },
            { 215, Encoding.UTF8.GetBytes("선착장: 빗물받이 숲") },
            { 216, Encoding.UTF8.GetBytes("포도주 항구") },
            { 217, Encoding.UTF8.GetBytes("카스트룸 옥시덴스") },
            { 218, Encoding.UTF8.GetBytes("칼새횃대 개척지") },
            { 219, Encoding.UTF8.GetBytes("도도 서식지") },
            { 220, Encoding.UTF8.GetBytes("양조장이 등대") },
            { 221, Encoding.UTF8.GetBytes("데네벨 가도") },
            { 222, Encoding.UTF8.GetBytes("사스타샤 침식 동굴") },
            { 223, Encoding.UTF8.GetBytes("맥주 항구") },
            { 224, Encoding.UTF8.GetBytes("해골 골짜기 야영지") },
            { 225, Encoding.UTF8.GetBytes("에어크햄 묘지") },
            { 226, Encoding.UTF8.GetBytes("북쪽 방파벽") },
            { 227, Encoding.UTF8.GetBytes("남쪽 방파벽") },
            { 228, Encoding.UTF8.GetBytes("배의 무덤") },
            { 230, Encoding.UTF8.GetBytes("시리우스 대등대") },
            { 231, Encoding.UTF8.GetBytes("메메룬 교역상점") },
            { 232, Encoding.UTF8.GetBytes("가여운 여인의 제재소") },
            { 233, Encoding.UTF8.GetBytes("살라오스의 유해") },
            { 234, Encoding.UTF8.GetBytes("얼간이 폭포") },
            { 235, Encoding.UTF8.GetBytes("은둔자의 암자") },
            { 236, Encoding.UTF8.GetBytes("니므 하늘유적") },
            { 237, Encoding.UTF8.GetBytes("감시대 야영지") },
            { 238, Encoding.UTF8.GetBytes("우가마로 무장광산") },
            { 239, Encoding.UTF8.GetBytes("청동호수 야영지") },
            { 240, Encoding.UTF8.GetBytes("방랑자의 궁전") },
            { 241, Encoding.UTF8.GetBytes("지지룬 교역상점") },
            { 242, Encoding.UTF8.GetBytes("코볼드군 시굴지") },
            { 243, Encoding.UTF8.GetBytes("망치 대지") },
            { 244, Encoding.UTF8.GetBytes("지평선 가장자리") },
            { 245, Encoding.UTF8.GetBytes("발자국 계곡") },
            { 246, Encoding.UTF8.GetBytes("하늬바람 곶") },
            { 247, Encoding.UTF8.GetBytes("가시 빠진 분지") },
            { 248, Encoding.UTF8.GetBytes("검은솔 들판") },
            { 249, Encoding.UTF8.GetBytes("악마의 손아귀") },
            { 250, Encoding.UTF8.GetBytes("마른뼈 황야") },
            { 251, Encoding.UTF8.GetBytes("모래 관문") },
            { 252, Encoding.UTF8.GetBytes("웰윅 숲") },
            { 253, Encoding.UTF8.GetBytes("불타는 장벽") },
            { 254, Encoding.UTF8.GetBytes("불결한 샘터") },
            { 255, Encoding.UTF8.GetBytes("잔라크") },
            { 256, Encoding.UTF8.GetBytes("붉은 미궁") },
            { 257, Encoding.UTF8.GetBytes("사골리 사막") },
            { 258, Encoding.UTF8.GetBytes("푸른안개 수맥") },
            { 259, Encoding.UTF8.GetBytes("라우반의 완충지") },
            { 260, Encoding.UTF8.GetBytes("카스트룸 메리디아눔") },
            { 261, Encoding.UTF8.GetBytes("사사모의 여든 계단") },
            { 262, Encoding.UTF8.GetBytes("횃불산 등대") },
            { 263, Encoding.UTF8.GetBytes("전갈 교역소") },
            { 264, Encoding.UTF8.GetBytes("노피카의 우물") },
            { 265, Encoding.UTF8.GetBytes("말뚝박기탑 1호") },
            { 266, Encoding.UTF8.GetBytes("은 장터") },
            { 267, Encoding.UTF8.GetBytes("구리종 광산") },
            { 268, Encoding.UTF8.GetBytes("해돋이 문") },
            { 269, Encoding.UTF8.GetBytes("해넘이 문") },
            { 270, Encoding.UTF8.GetBytes("알라그 햇길") },
            { 271, Encoding.UTF8.GetBytes("지평선 관문") },
            { 272, Encoding.UTF8.GetBytes("초승달 만") },
            { 273, Encoding.UTF8.GetBytes("말없는 왕") },
            { 274, Encoding.UTF8.GetBytes("저녁별 만") },
            { 275, Encoding.UTF8.GetBytes("달샘 동굴") },
            { 276, Encoding.UTF8.GetBytes("파라타의 묘소") },
            { 277, Encoding.UTF8.GetBytes("제국군 전초기지") },
            { 278, Encoding.UTF8.GetBytes("돌팔매 빈민굴") },
            { 279, Encoding.UTF8.GetBytes("페스카 모험가 야영지") },
            { 280, Encoding.UTF8.GetBytes("자매 언덕") },
            { 281, Encoding.UTF8.GetBytes("검댕개울") },
            { 282, Encoding.UTF8.GetBytes("왕립 나나모 농원") },
            { 283, Encoding.UTF8.GetBytes("울다하 조차장") },
            { 284, Encoding.UTF8.GetBytes("알라그 별길") },
            { 285, Encoding.UTF8.GetBytes("페스카 전망대") },
            { 286, Encoding.UTF8.GetBytes("사사간 대왕 나무") },
            { 287, Encoding.UTF8.GetBytes("사골리 관문") },
            { 288, Encoding.UTF8.GetBytes("알라그 햇길") },
            { 289, Encoding.UTF8.GetBytes("주점 '궤짝과 관짝'") },
            { 290, Encoding.UTF8.GetBytes("검은솔 정류소") },
            { 291, Encoding.UTF8.GetBytes("실디하 유적") },
            { 292, Encoding.UTF8.GetBytes("사막쥐 소굴") },
            { 293, Encoding.UTF8.GetBytes("지옥무리 개미굴") },
            { 294, Encoding.UTF8.GetBytes("희망 없는 유민가") },
            { 295, Encoding.UTF8.GetBytes("봉화 언덕") },
            { 296, Encoding.UTF8.GetBytes("나나와 은광") },
            { 297, Encoding.UTF8.GetBytes("부정한 계승자") },
            { 298, Encoding.UTF8.GetBytes("키브론 별장 자취") },
            { 299, Encoding.UTF8.GetBytes("알라그 햇길") },
            { 300, Encoding.UTF8.GetBytes("마른뼈 야영지") },
            { 301, Encoding.UTF8.GetBytes("보이지 않는 도시") },
            { 302, Encoding.UTF8.GetBytes("성 아다마 란다마 교회") },
            { 303, Encoding.UTF8.GetBytes("송곳 봉우리") },
            { 304, Encoding.UTF8.GetBytes("금 장터") },
            { 305, Encoding.UTF8.GetBytes("할라탈리 수련장") },
            { 306, Encoding.UTF8.GetBytes("아말쟈군 진영") },
            { 307, Encoding.UTF8.GetBytes("하늘다리") },
            { 308, Encoding.UTF8.GetBytes("유그람 강") },
            { 309, Encoding.UTF8.GetBytes("달 사당") },
            { 310, Encoding.UTF8.GetBytes("검붉은 폭포") },
            { 311, Encoding.UTF8.GetBytes("마지막 기원") },
            { 312, Encoding.UTF8.GetBytes("카른의 무너진 사원") },
            { 313, Encoding.UTF8.GetBytes("리틀 알라미고") },
            { 314, Encoding.UTF8.GetBytes("도마뱀 개울") },
            { 315, Encoding.UTF8.GetBytes("떠돌이의 무덤") },
            { 316, Encoding.UTF8.GetBytes("화염 신도 부락") },
            { 317, Encoding.UTF8.GetBytes("유령 호수") },
            { 318, Encoding.UTF8.GetBytes("잔라크 보조 진영") },
            { 319, Encoding.UTF8.GetBytes("잔라크 제단") },
            { 320, Encoding.UTF8.GetBytes("자하라크 진영") },
            { 321, Encoding.UTF8.GetBytes("날 사당") },
            { 322, Encoding.UTF8.GetBytes("미노타우로스 말름") },
            { 323, Encoding.UTF8.GetBytes("잊힌 오아시스") },
            { 324, Encoding.UTF8.GetBytes("비레고의 강타") },
            { 325, Encoding.UTF8.GetBytes("푸른안개 야영지") },
            { 326, Encoding.UTF8.GetBytes("동쪽 감시탑") },
            { 327, Encoding.UTF8.GetBytes("서쪽 감시탑") },
            { 328, Encoding.UTF8.GetBytes("아마지나 미스릴 폐광") },
            { 329, Encoding.UTF8.GetBytes("달라가브의 발톱") },
            { 330, Encoding.UTF8.GetBytes("청린 원천지") },
            { 331, Encoding.UTF8.GetBytes("청린 정제소") },
            { 332, Encoding.UTF8.GetBytes("전진 관문") },
            { 333, Encoding.UTF8.GetBytes("카스트룸 메리디아눔") },
            { 334, Encoding.UTF8.GetBytes("송곳 봉우리") },
            { 335, Encoding.UTF8.GetBytes("마도열차 정거장") },
            { 336, Encoding.UTF8.GetBytes("비공전함 발착장") },
            { 337, Encoding.UTF8.GetBytes("모라비 조선소") },
            { 338, Encoding.UTF8.GetBytes("소금기둥 해변") },
            { 339, Encoding.UTF8.GetBytes("촛불지기 부두") },
            { 340, Encoding.UTF8.GetBytes("텅 빈 심장") },
            { 341, Encoding.UTF8.GetBytes("오쉬온 등대") },
            { 342, Encoding.UTF8.GetBytes("청린 채취장") },
            { 343, Encoding.UTF8.GetBytes("하우케타 별궁 1층") },
            { 344, Encoding.UTF8.GetBytes("하우케타 별궁 2층") },
            { 345, Encoding.UTF8.GetBytes("하우케타 별궁 지하") },
            { 346, Encoding.UTF8.GetBytes("신궁부대 사령실") },
            { 347, Encoding.UTF8.GetBytes("말없는 선인의 좌탁") },
            { 348, Encoding.UTF8.GetBytes("재생의 그루터기") },
            { 349, Encoding.UTF8.GetBytes("카스트룸 마리눔") },
            { 350, Encoding.UTF8.GetBytes("외지 라노시아") },
            { 351, Encoding.UTF8.GetBytes("사령함교: 제독실") },
            { 352, Encoding.UTF8.GetBytes("림사 로민사 회의장") },
            { 353, Encoding.UTF8.GetBytes("림사 로민사 연설장") },
            { 354, Encoding.UTF8.GetBytes("은갑옷단 총장실") },
            { 355, Encoding.UTF8.GetBytes("향불방") },
            { 356, Encoding.UTF8.GetBytes("모래의 집") },
            { 357, Encoding.UTF8.GetBytes("불꽃신의 제단") },
            { 358, Encoding.UTF8.GetBytes("늑대우리 부두") },
            { 359, Encoding.UTF8.GetBytes("오고모로 화산구 신전") },
            { 360, Encoding.UTF8.GetBytes("가시 정원") },
            { 361, Encoding.UTF8.GetBytes("울부짖는 눈 석탑군") },
            { 362, Encoding.UTF8.GetBytes("바다뱀 소굴") },
            { 363, Encoding.UTF8.GetBytes("사프사 산란지") },
            { 364, Encoding.UTF8.GetBytes("사하긴군 진영") },
            { 365, Encoding.UTF8.GetBytes("은닉 항구") },
            { 366, Encoding.UTF8.GetBytes("뜨끈포도주 요양원") },
            { 368, Encoding.UTF8.GetBytes("선착장: 맥주 항구") },
            { 370, Encoding.UTF8.GetBytes("방파제: 초승달 만") },
            { 371, Encoding.UTF8.GetBytes("방파제: 은 장터") },
            { 372, Encoding.UTF8.GetBytes("지하 2층") },
            { 373, Encoding.UTF8.GetBytes("달 회랑") },
            { 374, Encoding.UTF8.GetBytes("새벽의 방") },
            { 375, Encoding.UTF8.GetBytes("말뚝박기탑 2호") },
            { 376, Encoding.UTF8.GetBytes("말뚝박기탑 3호") },
            { 377, Encoding.UTF8.GetBytes("나무꾼의 비명") },
            { 378, Encoding.UTF8.GetBytes("에테라이트 광장") },
            { 379, Encoding.UTF8.GetBytes("차원의 틈: 영빈실") },
            { 380, Encoding.UTF8.GetBytes("용머리 벌판") },
            { 381, Encoding.UTF8.GetBytes("섭리의 땅") },
            { 382, Encoding.UTF8.GetBytes("큰바위 언덕") },
            { 383, Encoding.UTF8.GetBytes("하얀테 설원") },
            { 384, Encoding.UTF8.GetBytes("할드라스 전진가도") },
            { 385, Encoding.UTF8.GetBytes("아도넬 점성대") },
            { 386, Encoding.UTF8.GetBytes("그리핀 대교") },
            { 387, Encoding.UTF8.GetBytes("아트보르그 요새지대") },
            { 388, Encoding.UTF8.GetBytes("용머리 전진기지") },
            { 389, Encoding.UTF8.GetBytes("마녀의 비탈") },
            { 390, Encoding.UTF8.GetBytes("강철 경계초소") },
            { 391, Encoding.UTF8.GetBytes("악귀의 위장") },
            { 392, Encoding.UTF8.GetBytes("성 다니펜의 눈물") },
            { 393, Encoding.UTF8.GetBytes("나탈란 입식지") },
            { 394, Encoding.UTF8.GetBytes("금빛 골짜기") },
            { 395, Encoding.UTF8.GetBytes("일곱 메아리의 길") },
            { 396, Encoding.UTF8.GetBytes("비석 탑") },
            { 397, Encoding.UTF8.GetBytes("할로네의 눈길") },
            { 398, Encoding.UTF8.GetBytes("성 다니펜의 여정") },
            { 399, Encoding.UTF8.GetBytes("제멜 요새") },
            { 400, Encoding.UTF8.GetBytes("대심판의 문") },
            { 401, Encoding.UTF8.GetBytes("돌방패 경계초소") },
            { 402, Encoding.UTF8.GetBytes("하얀테 전초지") },
            { 403, Encoding.UTF8.GetBytes("베히모스의 영역") },
            { 404, Encoding.UTF8.GetBytes("얼음외투 대빙벽") },
            { 405, Encoding.UTF8.GetBytes("칼날 봉우리") },
            { 406, Encoding.UTF8.GetBytes("구름길") },
            { 407, Encoding.UTF8.GetBytes("구름바다") },
            { 408, Encoding.UTF8.GetBytes("하얀 늑대 관문(중부삼림 서쪽 방면)") },
            { 409, Encoding.UTF8.GetBytes("짙은안개 습원") },
            { 410, Encoding.UTF8.GetBytes("은빛눈물 호수 북부") },
            { 411, Encoding.UTF8.GetBytes("망자의 종소리") },
            { 412, Encoding.UTF8.GetBytes("붕괴한 야영지") },
            { 413, Encoding.UTF8.GetBytes("엉킨덩굴 습지대") },
            { 414, Encoding.UTF8.GetBytes("이른서리 고개") },
            { 415, Encoding.UTF8.GetBytes("카스트룸 센트리") },
            { 416, Encoding.UTF8.GetBytes("성 코이나크 재단 조사지") },
            { 417, Encoding.UTF8.GetBytes("노래하는 열곡") },
            { 418, Encoding.UTF8.GetBytes("묵약의 탑") },
            { 419, Encoding.UTF8.GetBytes("영원그늘<br>(장로나무)") },
            { 420, Encoding.UTF8.GetBytes("크리스탈 타워") },
            { 421, Encoding.UTF8.GetBytes("은빛눈물 호수") },
            { 422, Encoding.UTF8.GetBytes("강심장호") },
            { 423, Encoding.UTF8.GetBytes("대결 접수처") },
            { 424, Encoding.UTF8.GetBytes("선착장: 늑대우리") },
            { 425, Encoding.UTF8.GetBytes("안갯빛 마을") },
            { 426, Encoding.UTF8.GetBytes("라벤더 안식처") },
            { 427, Encoding.UTF8.GetBytes("하늘잔 마루") },
            { 428, Encoding.UTF8.GetBytes("연병장") },
            { 429, Encoding.UTF8.GetBytes("근위대의 길") },
            { 430, Encoding.UTF8.GetBytes("마도성 프라이토리움") },
            { 431, Encoding.UTF8.GetBytes("폐기물 처리장") },
            { 432, Encoding.UTF8.GetBytes("주 진입로") },
            { 433, Encoding.UTF8.GetBytes("제V폐쇄구역") },
            { 434, Encoding.UTF8.GetBytes("중앙 교차로") },
            { 435, Encoding.UTF8.GetBytes("마도열차 정류장") },
            { 436, Encoding.UTF8.GetBytes("무기고") },
            { 437, Encoding.UTF8.GetBytes("비공정 발착장") },
            { 438, Encoding.UTF8.GetBytes("청린 양수장") },
            { 439, Encoding.UTF8.GetBytes("던스탠 감시초소") },
            { 440, Encoding.UTF8.GetBytes("마도성 프라이토리움") },
            { 441, Encoding.UTF8.GetBytes("최상층") },
            { 442, Encoding.UTF8.GetBytes("관리층") },
            { 443, Encoding.UTF8.GetBytes("방어층") },
            { 444, Encoding.UTF8.GetBytes("주요층") },
            { 445, Encoding.UTF8.GetBytes("기저층") },
            { 446, Encoding.UTF8.GetBytes("공방층") },
            { 447, Encoding.UTF8.GetBytes("비공정 승강장") },
            { 448, Encoding.UTF8.GetBytes("대공 방어 구역") },
            { 449, Encoding.UTF8.GetBytes("마도 아머 격납고") },
            { 450, Encoding.UTF8.GetBytes("바깥 통로") },
            { 451, Encoding.UTF8.GetBytes("군단장실") },
            { 452, Encoding.UTF8.GetBytes("기저 중추 구역") },
            { 453, Encoding.UTF8.GetBytes("경사 승강기") },
            { 454, Encoding.UTF8.GetBytes("스카이와의 연구실") },
            { 455, Encoding.UTF8.GetBytes("마도 공방 구역") },
            { 456, Encoding.UTF8.GetBytes("공방 승강기") },
            { 457, Encoding.UTF8.GetBytes("후방 출입구") },
            { 458, Encoding.UTF8.GetBytes("마도 병기 인증실") },
            { 459, Encoding.UTF8.GetBytes("울부짖는 눈 테두리") },
            { 460, Encoding.UTF8.GetBytes("선착장: 모라비 조선소") },
            { 461, Encoding.UTF8.GetBytes("선착장: 환영 제도") },
            { 462, Encoding.UTF8.GetBytes("로타노 해") },
            { 463, Encoding.UTF8.GetBytes("라그나로크급 구속함") },
            { 464, Encoding.UTF8.GetBytes("메테오 탐사갱 상부") },
            { 465, Encoding.UTF8.GetBytes("메테오 탐사갱 하부") },
            { 466, Encoding.UTF8.GetBytes("라그나로크급 구속함") },
            { 467, Encoding.UTF8.GetBytes("가동격벽") },
            { 468, Encoding.UTF8.GetBytes("중추구획") },
            { 469, Encoding.UTF8.GetBytes("제1함교") },
            { 470, Encoding.UTF8.GetBytes("안내인: 날 사당") },
            { 471, Encoding.UTF8.GetBytes("안내인: 미노타우로스 말름") },
            { 472, Encoding.UTF8.GetBytes("모래의 집") },
            { 473, Encoding.UTF8.GetBytes("안내인: 하얀 늑대 관문") },
            { 474, Encoding.UTF8.GetBytes("군단병 구역") },
            { 475, Encoding.UTF8.GetBytes("선착장: 거울못 나루") },
            { 476, Encoding.UTF8.GetBytes("선착장: 라벤더 안식처") },
            { 477, Encoding.UTF8.GetBytes("후방 출입구") },
            { 478, Encoding.UTF8.GetBytes("고대인의 미궁") },
            { 479, Encoding.UTF8.GetBytes("고대인의 미궁 1층") },
            { 480, Encoding.UTF8.GetBytes("고대인의 미궁 2층") },
            { 481, Encoding.UTF8.GetBytes("돌의 집") },
            { 482, Encoding.UTF8.GetBytes("잿빛 진영") },
            { 483, Encoding.UTF8.GetBytes("구리종 광산(어려움)") },
            { 484, Encoding.UTF8.GetBytes("하우케타 별궁(어려움)") },
            { 485, Encoding.UTF8.GetBytes("아래층 1") },
            { 486, Encoding.UTF8.GetBytes("아래층 2") },
            { 487, Encoding.UTF8.GetBytes("아래층 3") },
            { 488, Encoding.UTF8.GetBytes("가운데층 1") },
            { 489, Encoding.UTF8.GetBytes("가운데층 2") },
            { 490, Encoding.UTF8.GetBytes("가운데층 3") },
            { 491, Encoding.UTF8.GetBytes("위층") },
            { 492, Encoding.UTF8.GetBytes("山スポット25") },
            { 493, Encoding.UTF8.GetBytes("시르쿠스 탑") },
            { 494, Encoding.UTF8.GetBytes("사스타샤 침식 동굴(어려움)") },
            { 495, Encoding.UTF8.GetBytes("방랑자의 궁전(어려움)") },
            { 496, Encoding.UTF8.GetBytes("봉인된 바위섬") },
            { 497, Encoding.UTF8.GetBytes("아발라시아") },
            { 498, Encoding.UTF8.GetBytes("드라바니아") },
            { 500, Encoding.UTF8.GetBytes("림사 로민사") },
            { 501, Encoding.UTF8.GetBytes("저지 라노시아") },
            { 502, Encoding.UTF8.GetBytes("라노시아") },
            { 503, Encoding.UTF8.GetBytes("고지 라노시아") },
            { 504, Encoding.UTF8.GetBytes("울다하") },
            { 505, Encoding.UTF8.GetBytes("다날란") },
            { 506, Encoding.UTF8.GetBytes("그리다니아(검은장막 숲)") },
            { 507, Encoding.UTF8.GetBytes("검은장막 숲") },
            { 508, Encoding.UTF8.GetBytes("커르다스") },
            { 509, Encoding.UTF8.GetBytes("모르도나") },
            { 510, Encoding.UTF8.GetBytes("아발라시아") },
            { 511, Encoding.UTF8.GetBytes("드라바니아") },
            { 512, Encoding.UTF8.GetBytes("이슈가르드") },
            { 520, Encoding.UTF8.GetBytes("참회의 회랑") },
            { 521, Encoding.UTF8.GetBytes("관용의 회랑") },
            { 522, Encoding.UTF8.GetBytes("어리석은 자의 방") },
            { 523, Encoding.UTF8.GetBytes("벌거벗은 자의 방") },
            { 524, Encoding.UTF8.GetBytes("심문의 방") },
            { 525, Encoding.UTF8.GetBytes("단죄의 방") },
            { 526, Encoding.UTF8.GetBytes("속죄의 회랑") },
            { 527, Encoding.UTF8.GetBytes("고해의 방") },
            { 528, Encoding.UTF8.GetBytes("출입구") },
            { 529, Encoding.UTF8.GetBytes("파도소리 오쉬폰의 독방") },
            { 530, Encoding.UTF8.GetBytes("둔탱이 베르간드의 독방") },
            { 531, Encoding.UTF8.GetBytes("열손가락 타타비의 독방") },
            { 532, Encoding.UTF8.GetBytes("늪사람 유킬의 독방") },
            { 533, Encoding.UTF8.GetBytes("달랑드르 공녀의 독방") },
            { 534, Encoding.UTF8.GetBytes("출입구") },
            { 535, Encoding.UTF8.GetBytes("어린나무 제단") },
            { 536, Encoding.UTF8.GetBytes("이름 없는 묘") },
            { 537, Encoding.UTF8.GetBytes("절대왕 갈반스의 묘") },
            { 538, Encoding.UTF8.GetBytes("이니크 가 묘") },
            { 539, Encoding.UTF8.GetBytes("큰나무 제단") },
            { 540, Encoding.UTF8.GetBytes("메나 가 묘") },
            { 541, Encoding.UTF8.GetBytes("고목나무 제단") },
            { 542, Encoding.UTF8.GetBytes("돌다리") },
            { 543, Encoding.UTF8.GetBytes("적막의 고리") },
            { 544, Encoding.UTF8.GetBytes("항아리 방") },
            { 545, Encoding.UTF8.GetBytes("칼라인 카페") },
            { 546, Encoding.UTF8.GetBytes("모험가 길드") },
            { 547, Encoding.UTF8.GetBytes("칼라인 카페<br>(모험가 길드)") },
            { 548, Encoding.UTF8.GetBytes("여관 '둥지나무'") },
            { 549, Encoding.UTF8.GetBytes("그리다니아 비공정 승강장") },
            { 550, Encoding.UTF8.GetBytes("미스탈 이음다리") },
            { 551, Encoding.UTF8.GetBytes("물레방아 네거리") },
            { 552, Encoding.UTF8.GetBytes("푸른 오소리 관문") },
            { 553, Encoding.UTF8.GetBytes("떡갈나무 저택") },
            { 554, Encoding.UTF8.GetBytes("목수 길드") },
            { 555, Encoding.UTF8.GetBytes("떡갈나무 저택<br>(목수 길드)") },
            { 556, Encoding.UTF8.GetBytes("피가가의 물레방아") },
            { 557, Encoding.UTF8.GetBytes("도토리 놀이터") },
            { 558, Encoding.UTF8.GetBytes("베를랑 이음다리") },
            { 559, Encoding.UTF8.GetBytes("하얀 늑대 관문") },
            { 560, Encoding.UTF8.GetBytes("붉은 수달 관문") },
            { 561, Encoding.UTF8.GetBytes("신궁부대 본부") },
            { 562, Encoding.UTF8.GetBytes("궁술사 길드") },
            { 563, Encoding.UTF8.GetBytes("신궁부대 본부<br>(궁술사 길드)") },
            { 564, Encoding.UTF8.GetBytes("흑단나무 상점가") },
            { 565, Encoding.UTF8.GetBytes("자단나무 상점가") },
            { 566, Encoding.UTF8.GetBytes("나무그늘 정자") },
            { 567, Encoding.UTF8.GetBytes("가죽공방 '펜이르'") },
            { 568, Encoding.UTF8.GetBytes("가죽공예가 길드") },
            { 569, Encoding.UTF8.GetBytes("공예품점 '펜이르'") },
            { 570, Encoding.UTF8.GetBytes("귀곡부대 주둔소") },
            { 571, Encoding.UTF8.GetBytes("창술사 길드") },
            { 572, Encoding.UTF8.GetBytes("귀곡부대 주둔소<br>(창술사 길드)") },
            { 573, Encoding.UTF8.GetBytes("무구점 '켄타우로스의 눈'") },
            { 574, Encoding.UTF8.GetBytes("검은 멧돼지 관문") },
            { 575, Encoding.UTF8.GetBytes("아프칼루 폭포") },
            { 576, Encoding.UTF8.GetBytes("어진나무 명상굴") },
            { 577, Encoding.UTF8.GetBytes("환술사 길드") },
            { 578, Encoding.UTF8.GetBytes("어진나무 명상굴<br>(환술사 길드)") },
            { 579, Encoding.UTF8.GetBytes("풍요신 제단") },
            { 580, Encoding.UTF8.GetBytes("미 케토 야외음악당") },
            { 581, Encoding.UTF8.GetBytes("비옥토 농장") },
            { 582, Encoding.UTF8.GetBytes("원예가 길드") },
            { 583, Encoding.UTF8.GetBytes("비옥토 농장<br>(원예가 길드)") },
            { 584, Encoding.UTF8.GetBytes("휘파람 방앗간") },
            { 585, Encoding.UTF8.GetBytes("홍차강") },
            { 586, Encoding.UTF8.GetBytes("속삭임 계곡") },
            { 587, Encoding.UTF8.GetBytes("비취 호수") },
            { 588, Encoding.UTF8.GetBytes("시내 중심부") },
            { 589, Encoding.UTF8.GetBytes("문투이 양조창고") },
            { 590, Encoding.UTF8.GetBytes("에테라이트 광장") },
            { 591, Encoding.UTF8.GetBytes("쌍사당 통합사령부") },
            { 592, Encoding.UTF8.GetBytes("동부 나루터<br>검은장막 숲 동부삼림") },
            { 593, Encoding.UTF8.GetBytes("초코보 대여소") },
            { 594, Encoding.UTF8.GetBytes("가죽공방 '펜이르'<br>(가죽공예가 길드)") },
            { 595, Encoding.UTF8.GetBytes("동부 나루터") },
            { 596, Encoding.UTF8.GetBytes("막힌 길인 것 같다") },
            { 597, Encoding.UTF8.GetBytes("푸른 오소리 관문(중부삼림 동쪽 방면)") },
            { 598, Encoding.UTF8.GetBytes("노란 뱀 관문(북부삼림 방면)") },
            { 599, Encoding.UTF8.GetBytes("1층") },
            { 600, Encoding.UTF8.GetBytes("2층") },
            { 601, Encoding.UTF8.GetBytes("지하 1층") },
            { 602, Encoding.UTF8.GetBytes("입구") },
            { 603, Encoding.UTF8.GetBytes("식량 창고") },
            { 604, Encoding.UTF8.GetBytes("장미 방") },
            { 605, Encoding.UTF8.GetBytes("창고") },
            { 606, Encoding.UTF8.GetBytes("음악실") },
            { 607, Encoding.UTF8.GetBytes("도서실") },
            { 608, Encoding.UTF8.GetBytes("백합 방") },
            { 609, Encoding.UTF8.GetBytes("패랭이꽃 방") },
            { 610, Encoding.UTF8.GetBytes("와인 저장고") },
            { 611, Encoding.UTF8.GetBytes("피의자의 방") },
            { 612, Encoding.UTF8.GetBytes("고문의 방") },
            { 613, Encoding.UTF8.GetBytes("날 관문") },
            { 614, Encoding.UTF8.GetBytes("불멸대 작전본부") },
            { 615, Encoding.UTF8.GetBytes("모래늪") },
            { 616, Encoding.UTF8.GetBytes("모래늪<br>(모험가 길드)") },
            { 617, Encoding.UTF8.GetBytes("여관 '모래시계'") },
            { 618, Encoding.UTF8.GetBytes("백금 신기루") },
            { 619, Encoding.UTF8.GetBytes("격투사 길드") },
            { 620, Encoding.UTF8.GetBytes("백금 신기루<br>(격투사 길드)") },
            { 621, Encoding.UTF8.GetBytes("에메랄드 거리") },
            { 622, Encoding.UTF8.GetBytes("투기장") },
            { 623, Encoding.UTF8.GetBytes("검술사 길드") },
            { 624, Encoding.UTF8.GetBytes("투기장<br>(검술사 길드)") },
            { 625, Encoding.UTF8.GetBytes("루디우스 무구점") },
            { 626, Encoding.UTF8.GetBytes("나나모 관문") },
            { 627, Encoding.UTF8.GetBytes("아르자네스 납골당") },
            { 628, Encoding.UTF8.GetBytes("에랄리그 묘당") },
            { 629, Encoding.UTF8.GetBytes("주술사 길드") },
            { 630, Encoding.UTF8.GetBytes("아르자네스 납골당<br>(주술사 길드)") },
            { 631, Encoding.UTF8.GetBytes("보석점 '에쉬템'") },
            { 632, Encoding.UTF8.GetBytes("에쉬템 직영공방") },
            { 633, Encoding.UTF8.GetBytes("보석공예가 길드") },
            { 634, Encoding.UTF8.GetBytes("에쉬템 직영공방<br>(보석공예가 길드)") },
            { 635, Encoding.UTF8.GetBytes("아마지나 광산회사") },
            { 636, Encoding.UTF8.GetBytes("광부 길드") },
            { 637, Encoding.UTF8.GetBytes("아마지나 광산회사<br>(광부 길드)") },
            { 638, Encoding.UTF8.GetBytes("줄마노 거리") },
            { 639, Encoding.UTF8.GetBytes("황금 마당") },
            { 640, Encoding.UTF8.GetBytes("루비길 국제시장") },
            { 641, Encoding.UTF8.GetBytes("우물식 승강기") },
            { 642, Encoding.UTF8.GetBytes("직물전문점 '태양비단'") },
            { 643, Encoding.UTF8.GetBytes("재봉사 길드") },
            { 644, Encoding.UTF8.GetBytes("직물전문점 '태양비단'<br>(재봉사 길드)") },
            { 645, Encoding.UTF8.GetBytes("달 관문") },
            { 646, Encoding.UTF8.GetBytes("사파이어길 국제시장") },
            { 647, Encoding.UTF8.GetBytes("진주 거리") },
            { 648, Encoding.UTF8.GetBytes("밀바네스 예배당") },
            { 649, Encoding.UTF8.GetBytes("프론데일 약학원") },
            { 650, Encoding.UTF8.GetBytes("연금술사 길드") },
            { 651, Encoding.UTF8.GetBytes("프론데일 약학원<br>(연금술사 길드)") },
            { 652, Encoding.UTF8.GetBytes("프론데일 보도") },
            { 653, Encoding.UTF8.GetBytes("왕의 산책로") },
            { 654, Encoding.UTF8.GetBytes("울다하 비공정 승강장") },
            { 655, Encoding.UTF8.GetBytes("둥지나무 여관 문") },
            { 656, Encoding.UTF8.GetBytes("침식 동굴") },
            { 657, Encoding.UTF8.GetBytes("안개수염 아지트") },
            { 658, Encoding.UTF8.GetBytes("안개수염 해구") },
            { 659, Encoding.UTF8.GetBytes("침식 동굴") },
            { 660, Encoding.UTF8.GetBytes("울부짖는 연못") },
            { 661, Encoding.UTF8.GetBytes("막다른 곳") },
            { 662, Encoding.UTF8.GetBytes("커얼의 보금자리") },
            { 663, Encoding.UTF8.GetBytes("현제문") },
            { 664, Encoding.UTF8.GetBytes("조수실") },
            { 665, Encoding.UTF8.GetBytes("출입구") },
            { 666, Encoding.UTF8.GetBytes("항해사실") },
            { 667, Encoding.UTF8.GetBytes("갑판원실") },
            { 668, Encoding.UTF8.GetBytes("선장실") },
            { 669, Encoding.UTF8.GetBytes("징벌방") },
            { 670, Encoding.UTF8.GetBytes("현제문") },
            { 671, Encoding.UTF8.GetBytes("잠수부문") },
            { 672, Encoding.UTF8.GetBytes("숨겨진 나루터") },
            { 673, Encoding.UTF8.GetBytes("A1 갱도") },
            { 674, Encoding.UTF8.GetBytes("B1 갱도") },
            { 675, Encoding.UTF8.GetBytes("B4 갱도") },
            { 676, Encoding.UTF8.GetBytes("재개발구역 E1 갱도") },
            { 677, Encoding.UTF8.GetBytes("재개발구역 E2 갱도") },
            { 678, Encoding.UTF8.GetBytes("식인종의 웅덩이") },
            { 679, Encoding.UTF8.GetBytes("아우성 구렁") },
            { 680, Encoding.UTF8.GetBytes("한탄의 구렁") },
            { 681, Encoding.UTF8.GetBytes("암굴왕의 옥좌") },
            { 682, Encoding.UTF8.GetBytes("개척되지 않은 덤불") },
            { 683, Encoding.UTF8.GetBytes("브레이플록스의 피난처") },
            { 684, Encoding.UTF8.GetBytes("진흙탕 수원지") },
            { 685, Encoding.UTF8.GetBytes("브레이플록스의 야영지") },
            { 686, Encoding.UTF8.GetBytes("브레이플록스의 감시소") },
            { 687, Encoding.UTF8.GetBytes("피난처 앞뜰") },
            { 688, Encoding.UTF8.GetBytes("피난처 뒷뜰") },
            { 689, Encoding.UTF8.GetBytes("야영지 앞뜰") },
            { 690, Encoding.UTF8.GetBytes("용의 보금자리") },
            { 691, Encoding.UTF8.GetBytes("야영지 내문") },
            { 692, Encoding.UTF8.GetBytes("권투 훈련장") },
            { 693, Encoding.UTF8.GetBytes("검투 훈련장") },
            { 694, Encoding.UTF8.GetBytes("수투 훈련장") },
            { 698, Encoding.UTF8.GetBytes("관청 구역") },
            { 700, Encoding.UTF8.GetBytes("상층 갑판") },
            { 701, Encoding.UTF8.GetBytes("하층 갑판") },
            { 702, Encoding.UTF8.GetBytes("아스탈리시아호") },
            { 703, Encoding.UTF8.GetBytes("산호탑<br>(도끼술사 길드)") },
            { 704, Encoding.UTF8.GetBytes("산호탑") },
            { 705, Encoding.UTF8.GetBytes("총술사 길드") },
            { 706, Encoding.UTF8.GetBytes("멜반 세관공사") },
            { 707, Encoding.UTF8.GetBytes("멜반 세관공사<br>(비술사 길드)") },
            { 708, Encoding.UTF8.GetBytes("레스토랑 '비스마르크'") },
            { 709, Encoding.UTF8.GetBytes("레스토랑 '비스마르크'<br>(요리사 길드)") },
            { 710, Encoding.UTF8.GetBytes("날디크와 비멜리 사") },
            { 711, Encoding.UTF8.GetBytes("\"날디크와 비멜리 사<br>(대장장이, 갑주제작사 길드)\"") },
            { 712, Encoding.UTF8.GetBytes("비술사 길드") },
            { 713, Encoding.UTF8.GetBytes("그물 창고") },
            { 714, Encoding.UTF8.GetBytes("그물 창고<br>(어부 길드)") },
            { 715, Encoding.UTF8.GetBytes("물에 빠진 돌고래 주점") },
            { 716, Encoding.UTF8.GetBytes("물에 빠진 돌고래 주점<br>(모험가 길드)") },
            { 717, Encoding.UTF8.GetBytes("생선가게 '유리바다'") },
            { 718, Encoding.UTF8.GetBytes("약국 '일곱 번째 세이지'") },
            { 719, Encoding.UTF8.GetBytes("영원한 소녀 주점") },
            { 720, Encoding.UTF8.GetBytes("요리사 길드") },
            { 721, Encoding.UTF8.GetBytes("뒷돛대") },
            { 722, Encoding.UTF8.GetBytes("사령함교") },
            { 723, Encoding.UTF8.GetBytes("사령함교: 작전지휘실") },
            { 724, Encoding.UTF8.GetBytes("사령함교: 작전회의실") },
            { 725, Encoding.UTF8.GetBytes("림사 로민사 비공정 승강장") },
            { 726, Encoding.UTF8.GetBytes("초코보 대여소") },
            { 727, Encoding.UTF8.GetBytes("북극성 등대") },
            { 728, Encoding.UTF8.GetBytes("여객선 부두") },
            { 729, Encoding.UTF8.GetBytes("양식장") },
            { 730, Encoding.UTF8.GetBytes("경매소") },
            { 731, Encoding.UTF8.GetBytes("까마귀 승강기") },
            { 732, Encoding.UTF8.GetBytes("방파벽 회관") },
            { 733, Encoding.UTF8.GetBytes("여관 '뒷돛대'") },
            { 734, Encoding.UTF8.GetBytes("어부 길드") },
            { 735, Encoding.UTF8.GetBytes("산들바람 관문") },
            { 736, Encoding.UTF8.GetBytes("폭풍 관문") },
            { 737, Encoding.UTF8.GetBytes("뱃고물 광장") },
            { 738, Encoding.UTF8.GetBytes("에테라이트 광장") },
            { 739, Encoding.UTF8.GetBytes("팔분의 광장") },
            { 741, Encoding.UTF8.GetBytes("닻 마당") },
            { 742, Encoding.UTF8.GetBytes("제비갈매기 대교") },
            { 743, Encoding.UTF8.GetBytes("국제거리 광장") },
            { 744, Encoding.UTF8.GetBytes("국제거리 동쪽 상점가") },
            { 745, Encoding.UTF8.GetBytes("국제거리 서쪽 상점가") },
            { 746, Encoding.UTF8.GetBytes("칠성장어 다리") },
            { 747, Encoding.UTF8.GetBytes("피라미 다리") },
            { 748, Encoding.UTF8.GetBytes("중앙 관제구역") },
            { 749, Encoding.UTF8.GetBytes("북쪽 관제구역") },
            { 750, Encoding.UTF8.GetBytes("선장 구역") },
            { 751, Encoding.UTF8.GetBytes("남쪽 관제구역") },
            { 752, Encoding.UTF8.GetBytes("해병 구역") },
            { 753, Encoding.UTF8.GetBytes("상업 구역") },
            { 754, Encoding.UTF8.GetBytes("선착장: 림사 로민사") },
            { 755, Encoding.UTF8.GetBytes("흑와단 군령부") },
            { 756, Encoding.UTF8.GetBytes("패랭이꽃 문") },
            { 757, Encoding.UTF8.GetBytes("잠긴 문") },
            { 758, Encoding.UTF8.GetBytes("잠긴 문") },
            { 759, Encoding.UTF8.GetBytes("피난처 정문") },
            { 760, Encoding.UTF8.GetBytes("피난처 내문") },
            { 761, Encoding.UTF8.GetBytes("피난처 뒷문") },
            { 762, Encoding.UTF8.GetBytes("야영지 정문") },
            { 763, Encoding.UTF8.GetBytes("선장실 문") },
            { 764, Encoding.UTF8.GetBytes("모험가 길드(대장장이·갑주제작사 길드/흑와단)") },
            { 765, Encoding.UTF8.GetBytes("요리사 길드(레스토랑 '비스마르크')") },
            { 766, Encoding.UTF8.GetBytes("도끼술사 길드(산호탑)") },
            { 767, Encoding.UTF8.GetBytes("시장(국제거리 광장)") },
            { 768, Encoding.UTF8.GetBytes("어부 길드(쌍검사 길드)") },
            { 769, Encoding.UTF8.GetBytes("비술사 길드") },
            { 770, Encoding.UTF8.GetBytes("산들바람 관문(중부 라노시아 방면)") },
            { 771, Encoding.UTF8.GetBytes("폭풍 관문(저지 라노시아 방면)") },
            { 772, Encoding.UTF8.GetBytes("모험가 길드(시장)") },
            { 773, Encoding.UTF8.GetBytes("주술사 길드") },
            { 774, Encoding.UTF8.GetBytes("검술사 길드(투기장)") },
            { 775, Encoding.UTF8.GetBytes("광부 길드") },
            { 776, Encoding.UTF8.GetBytes("연금술사 길드") },
            { 777, Encoding.UTF8.GetBytes("재봉사 길드") },
            { 778, Encoding.UTF8.GetBytes("울다하 왕정청") },
            { 779, Encoding.UTF8.GetBytes("나나모 관문(서부 다날란 방면)") },
            { 780, Encoding.UTF8.GetBytes("날 관문(중부 다날란 북쪽 방면)") },
            { 781, Encoding.UTF8.GetBytes("달 관문(중부 다날란 남쪽 방면)") },
            { 782, Encoding.UTF8.GetBytes("궁술사 길드") },
            { 783, Encoding.UTF8.GetBytes("가죽공예가 길드(시장)") },
            { 784, Encoding.UTF8.GetBytes("창술사 길드") },
            { 785, Encoding.UTF8.GetBytes("환술사 길드") },
            { 786, Encoding.UTF8.GetBytes("원예가 길드") },
            { 787, Encoding.UTF8.GetBytes("미 케토 야외음악당") },
            { 788, Encoding.UTF8.GetBytes("보석공예가 길드") },
            { 789, Encoding.UTF8.GetBytes("침묵의 정원") },
            { 790, Encoding.UTF8.GetBytes("긴 복도") },
            { 791, Encoding.UTF8.GetBytes("여행자의 나루터") },
            { 792, Encoding.UTF8.GetBytes("수상정원") },
            { 793, Encoding.UTF8.GetBytes("무한회랑") },
            { 794, Encoding.UTF8.GetBytes("여행자의 쉼터") },
            { 795, Encoding.UTF8.GetBytes("방랑자의 예배당") },
            { 796, Encoding.UTF8.GetBytes("금박 웅덩이") },
            { 797, Encoding.UTF8.GetBytes("빈털터리 동굴") },
            { 798, Encoding.UTF8.GetBytes("노란 호수") },
            { 799, Encoding.UTF8.GetBytes("수위의 함정") },
            { 800, Encoding.UTF8.GetBytes("수위 집합소") },
            { 801, Encoding.UTF8.GetBytes("금고 문") },
            { 802, Encoding.UTF8.GetBytes("세금징수인의 금고") },
            { 803, Encoding.UTF8.GetBytes("수전노의 거처") },
            { 804, Encoding.UTF8.GetBytes("수전노의 곳간") },
            { 805, Encoding.UTF8.GetBytes("경비병 집합소") },
            { 806, Encoding.UTF8.GetBytes("초코보 축사") },
            { 807, Encoding.UTF8.GetBytes("출입구") },
            { 808, Encoding.UTF8.GetBytes("대집회장") },
            { 809, Encoding.UTF8.GetBytes("용숨결 폭포") },
            { 810, Encoding.UTF8.GetBytes("위병 식당") },
            { 811, Encoding.UTF8.GetBytes("위병 숙사") },
            { 812, Encoding.UTF8.GetBytes("성 다니펜 예배당") },
            { 813, Encoding.UTF8.GetBytes("연병장") },
            { 814, Encoding.UTF8.GetBytes("태양의 테라스") },
            { 815, Encoding.UTF8.GetBytes("타타메푸 II세의 기도소") },
            { 816, Encoding.UTF8.GetBytes("라라푸토 I세의 안뜰") },
            { 817, Encoding.UTF8.GetBytes("라라푸토 IV세의 지하신전") },
            { 818, Encoding.UTF8.GetBytes("무력의 방") },
            { 819, Encoding.UTF8.GetBytes("부의 방") },
            { 820, Encoding.UTF8.GetBytes("마력의 방") },
            { 821, Encoding.UTF8.GetBytes("지혜의 방") },
            { 822, Encoding.UTF8.GetBytes("라라푸토 III세의 안뜰") },
            { 823, Encoding.UTF8.GetBytes("심판의 방") },
            { 824, Encoding.UTF8.GetBytes("메메토 여왕의 기도소") },
            { 825, Encoding.UTF8.GetBytes("태양신 아제마의 방") },
            { 826, Encoding.UTF8.GetBytes("기도소 문") },
            { 827, Encoding.UTF8.GetBytes("잠긴 문") },
            { 828, Encoding.UTF8.GetBytes("잠긴 문") },
            { 829, Encoding.UTF8.GetBytes("잠긴 문") },
            { 830, Encoding.UTF8.GetBytes("잠긴 문") },
            { 831, Encoding.UTF8.GetBytes("잠긴 문") },
            { 832, Encoding.UTF8.GetBytes("지하신전 문") },
            { 833, Encoding.UTF8.GetBytes("무력의 문") },
            { 834, Encoding.UTF8.GetBytes("부의 문") },
            { 835, Encoding.UTF8.GetBytes("마력의 문") },
            { 836, Encoding.UTF8.GetBytes("지혜의 문") },
            { 837, Encoding.UTF8.GetBytes("심판의 문") },
            { 838, Encoding.UTF8.GetBytes("메마른 층") },
            { 839, Encoding.UTF8.GetBytes("샘솟는 층") },
            { 840, Encoding.UTF8.GetBytes("청린수 층") },
            { 841, Encoding.UTF8.GetBytes("포식의 앞방") },
            { 842, Encoding.UTF8.GetBytes("침전하는 중간방") },
            { 843, Encoding.UTF8.GetBytes("대식왕의 널방") },
            { 844, Encoding.UTF8.GetBytes("뒷문") },
            { 845, Encoding.UTF8.GetBytes("정문") },
            { 846, Encoding.UTF8.GetBytes("집회실 문") },
            { 847, Encoding.UTF8.GetBytes("식당 문") },
            { 848, Encoding.UTF8.GetBytes("마도 필드 IV") },
            { 849, Encoding.UTF8.GetBytes("1층") },
            { 850, Encoding.UTF8.GetBytes("지하 1층") },
            { 851, Encoding.UTF8.GetBytes("늑대 구렁") },
            { 852, Encoding.UTF8.GetBytes("송곳니 감옥") },
            { 853, Encoding.UTF8.GetBytes("발톱 감옥") },
            { 854, Encoding.UTF8.GetBytes("유적 입구") },
            { 855, Encoding.UTF8.GetBytes("무너진 유적") },
            { 856, Encoding.UTF8.GetBytes("지하 유적") },
            { 857, Encoding.UTF8.GetBytes("대십자 광장") },
            { 858, Encoding.UTF8.GetBytes("부패의 미궁") },
            { 859, Encoding.UTF8.GetBytes("이계의 미궁") },
            { 860, Encoding.UTF8.GetBytes("연옥의 미궁") },
            { 861, Encoding.UTF8.GetBytes("승천의 회랑") },
            { 862, Encoding.UTF8.GetBytes("죽은 자의 욕실") },
            { 863, Encoding.UTF8.GetBytes("임시 입구") },
            { 864, Encoding.UTF8.GetBytes("어리석은 자의 욕실") },
            { 865, Encoding.UTF8.GetBytes("썩은 왕의 사당") },
            { 866, Encoding.UTF8.GetBytes("통탄의 회랑") },
            { 867, Encoding.UTF8.GetBytes("요괴왕의 사당") },
            { 868, Encoding.UTF8.GetBytes("초열의 회랑") },
            { 869, Encoding.UTF8.GetBytes("짐승왕의 사당") },
            { 870, Encoding.UTF8.GetBytes("부정의 집회실") },
            { 871, Encoding.UTF8.GetBytes("참극의 익랑") },
            { 872, Encoding.UTF8.GetBytes("배신의 알현실") },
            { 873, Encoding.UTF8.GetBytes("1층") },
            { 874, Encoding.UTF8.GetBytes("2층") },
            { 875, Encoding.UTF8.GetBytes("3층") },
            { 876, Encoding.UTF8.GetBytes("비탄의 앞뜰") },
            { 877, Encoding.UTF8.GetBytes("감시 망루") },
            { 878, Encoding.UTF8.GetBytes("우측 울타리") },
            { 879, Encoding.UTF8.GetBytes("보조 격납고") },
            { 880, Encoding.UTF8.GetBytes("기병 막사") },
            { 881, Encoding.UTF8.GetBytes("좌측 울타리") },
            { 882, Encoding.UTF8.GetBytes("용맹한 장수의 사당") },
            { 883, Encoding.UTF8.GetBytes("망자의 욕실") },
            { 884, Encoding.UTF8.GetBytes("피의자의 방 문") },
            { 885, Encoding.UTF8.GetBytes("고문의 방 문") },
            { 886, Encoding.UTF8.GetBytes("조사 거점") },
            { 887, Encoding.UTF8.GetBytes("메테오 균열") },
            { 888, Encoding.UTF8.GetBytes("메테오 탐사갱") },
            { 889, Encoding.UTF8.GetBytes("알라그 유적") },
            { 890, Encoding.UTF8.GetBytes("제I날개깃") },
            { 891, Encoding.UTF8.GetBytes("탐사 갱도 심부") },
            { 892, Encoding.UTF8.GetBytes("제VII구획") },
            { 893, Encoding.UTF8.GetBytes("제IV구획") },
            { 894, Encoding.UTF8.GetBytes("제II구획") },
            { 895, Encoding.UTF8.GetBytes("제I구획") },
            { 896, Encoding.UTF8.GetBytes("제III구획") },
            { 897, Encoding.UTF8.GetBytes("제V구획") },
            { 898, Encoding.UTF8.GetBytes("제VI구획") },
            { 899, Encoding.UTF8.GetBytes("기관부 연소실") },
            { 900, Encoding.UTF8.GetBytes("기관부 압축실") },
            { 901, Encoding.UTF8.GetBytes("기관부 추진제실") },
            { 902, Encoding.UTF8.GetBytes("가동격벽") },
            { 903, Encoding.UTF8.GetBytes("바하무트의 오른손") },
            { 904, Encoding.UTF8.GetBytes("제1함교") },
            { 905, Encoding.UTF8.GetBytes("승강기 구획") },
            { 906, Encoding.UTF8.GetBytes("제XII날개깃") },
            { 907, Encoding.UTF8.GetBytes("제XI날개깃") },
            { 908, Encoding.UTF8.GetBytes("제X날개깃") },
            { 909, Encoding.UTF8.GetBytes("제IX날개깃") },
            { 910, Encoding.UTF8.GetBytes("제VIII날개깃") },
            { 911, Encoding.UTF8.GetBytes("제VII날개깃") },
            { 912, Encoding.UTF8.GetBytes("제VI날개깃") },
            { 913, Encoding.UTF8.GetBytes("제V날개깃") },
            { 914, Encoding.UTF8.GetBytes("제IV날개깃") },
            { 915, Encoding.UTF8.GetBytes("제III날개깃") },
            { 916, Encoding.UTF8.GetBytes("제II날개깃") },
            { 917, Encoding.UTF8.GetBytes("방위 지휘실") },
            { 918, Encoding.UTF8.GetBytes("늑대우리") },
            { 919, Encoding.UTF8.GetBytes("구속함") },
            { 920, Encoding.UTF8.GetBytes("육각 승강기") },
            { 921, Encoding.UTF8.GetBytes("구속함 가동격벽") },
            { 922, Encoding.UTF8.GetBytes("요새 외곽") },
            { 923, Encoding.UTF8.GetBytes("요새 내곽") },
            { 924, Encoding.UTF8.GetBytes("기관부 연소실") },
            { 925, Encoding.UTF8.GetBytes("기관부 압축실") },
            { 926, Encoding.UTF8.GetBytes("기관부 추진제실") },
            { 927, Encoding.UTF8.GetBytes("시리우스 대등대") },
            { 928, Encoding.UTF8.GetBytes("제2탑 기반부") },
            { 929, Encoding.UTF8.GetBytes("에테르 저장실") },
            { 930, Encoding.UTF8.GetBytes("에테르 압축실") },
            { 931, Encoding.UTF8.GetBytes("시리우스 등롱실") },
            { 932, Encoding.UTF8.GetBytes("제3탑 기반부") },
            { 933, Encoding.UTF8.GetBytes("제4탑 기반부") },
            { 934, Encoding.UTF8.GetBytes("에테르 펌프실") },
            { 935, Encoding.UTF8.GetBytes("5층") },
            { 936, Encoding.UTF8.GetBytes("4층") },
            { 937, Encoding.UTF8.GetBytes("3층") },
            { 938, Encoding.UTF8.GetBytes("2층") },
            { 939, Encoding.UTF8.GetBytes("1층") },
            { 940, Encoding.UTF8.GetBytes("지하 1층") },
            { 941, Encoding.UTF8.GetBytes("크리스탈 관문") },
            { 942, Encoding.UTF8.GetBytes("여덟 검사의 앞뜰") },
            { 943, Encoding.UTF8.GetBytes("일곱째 낙원") },
            { 944, Encoding.UTF8.GetBytes("제789땅굴단 채굴지") },
            { 945, Encoding.UTF8.GetBytes("노부의 육성지") },
            { 946, Encoding.UTF8.GetBytes("달그림자 섬") },
            { 947, Encoding.UTF8.GetBytes("바다 위 상선") },
            { 948, Encoding.UTF8.GetBytes("바다 위 해적선") },
            { 949, Encoding.UTF8.GetBytes("회귀의 묘비") },
            { 950, Encoding.UTF8.GetBytes("미지의 낚시터") },
            { 951, Encoding.UTF8.GetBytes("잎맥 물줄기") },
            { 952, Encoding.UTF8.GetBytes("거울못") },
            { 953, Encoding.UTF8.GetBytes("청록의 나락") },
            { 954, Encoding.UTF8.GetBytes("잔물결 시내") },
            { 955, Encoding.UTF8.GetBytes("실프의 계곡") },
            { 956, Encoding.UTF8.GetBytes("하두바 강 상류") },
            { 957, Encoding.UTF8.GetBytes("하두바 강 중류") },
            { 958, Encoding.UTF8.GetBytes("하두바 강 하류") },
            { 959, Encoding.UTF8.GetBytes("하두바 강 동쪽") },
            { 960, Encoding.UTF8.GetBytes("고블린족 양식장") },
            { 961, Encoding.UTF8.GetBytes("술렁이는 강") },
            { 962, Encoding.UTF8.GetBytes("가을박 호수") },
            { 963, Encoding.UTF8.GetBytes("타호토틀 호수") },
            { 964, Encoding.UTF8.GetBytes("그리다니아: 비취 호수") },
            { 965, Encoding.UTF8.GetBytes("그리다니아: 홍차강 하류") },
            { 966, Encoding.UTF8.GetBytes("엉킨덩굴 습지대 원류") },
            { 967, Encoding.UTF8.GetBytes("노래하는 열곡 북부") },
            { 968, Encoding.UTF8.GetBytes("커르다스 강") },
            { 969, Encoding.UTF8.GetBytes("칼날 봉우리 기슭") },
            { 970, Encoding.UTF8.GetBytes("용머리 전진기지 저수지") },
            { 971, Encoding.UTF8.GetBytes("조사대 얼음 구멍") },
            { 972, Encoding.UTF8.GetBytes("이슈가르드 구름바다") },
            { 973, Encoding.UTF8.GetBytes("산들바람 줄기 연안") },
            { 974, Encoding.UTF8.GetBytes("여름여울 연안") },
            { 975, Encoding.UTF8.GetBytes("서쪽 아젤리스 강") },
            { 976, Encoding.UTF8.GetBytes("모라비 만 서쪽 절벽") },
            { 977, Encoding.UTF8.GetBytes("삼나무 숲 연안") },
            { 978, Encoding.UTF8.GetBytes("남부 핏빛해안") },
            { 979, Encoding.UTF8.GetBytes("북부 핏빛해안") },
            { 980, Encoding.UTF8.GetBytes("동쪽 아젤리스 강") },
            { 981, Encoding.UTF8.GetBytes("빗물받이 소택지") },
            { 982, Encoding.UTF8.GetBytes("해골 골짜기 연안") },
            { 983, Encoding.UTF8.GetBytes("하프스톤 연안") },
            { 984, Encoding.UTF8.GetBytes("환영 제도 북부") },
            { 985, Encoding.UTF8.GetBytes("환영 제도 남부") },
            { 986, Encoding.UTF8.GetBytes("청동호수 남부") },
            { 987, Encoding.UTF8.GetBytes("청동호수 북부") },
            { 988, Encoding.UTF8.GetBytes("청동호수 얕은 물") },
            { 989, Encoding.UTF8.GetBytes("기나긴 오르막 계곡") },
            { 990, Encoding.UTF8.GetBytes("검댕개울 상류") },
            { 991, Encoding.UTF8.GetBytes("검댕개울 하류") },
            { 992, Encoding.UTF8.GetBytes("마른뼈 황야 북쪽 샘터") },
            { 993, Encoding.UTF8.GetBytes("마른뼈 황야 남쪽 샘터") },
            { 994, Encoding.UTF8.GetBytes("적포도주 강") },
            { 995, Encoding.UTF8.GetBytes("자하라크 샘") },
            { 996, Encoding.UTF8.GetBytes("사골리 모래바다") },
            { 997, Encoding.UTF8.GetBytes("사골리 모래언덕") },
            { 998, Encoding.UTF8.GetBytes("푸른안개 샘터") },
            { 999, Encoding.UTF8.GetBytes("그리다니아: 홍차강 상류") },
            { 1000, Encoding.UTF8.GetBytes("그리다니아: 속삭임 계곡") },
            { 1001, Encoding.UTF8.GetBytes("로타노 해 먼바다: 뱃머리") },
            { 1002, Encoding.UTF8.GetBytes("로타노 해 먼바다: 뱃고물") },
            { 1003, Encoding.UTF8.GetBytes("얼지 않는 연못") },
            { 1004, Encoding.UTF8.GetBytes("투명한 연못") },
            { 1005, Encoding.UTF8.GetBytes("죽음의 호수 남쪽") },
            { 1006, Encoding.UTF8.GetBytes("죽음의 호수 서쪽") },
            { 1007, Encoding.UTF8.GetBytes("애도의 바위굴 서쪽") },
            { 1008, Encoding.UTF8.GetBytes("살리아크 강 상류") },
            { 1009, Encoding.UTF8.GetBytes("살리아크 강 중류") },
            { 1010, Encoding.UTF8.GetBytes("솜 알 산머리") },
            { 1011, Encoding.UTF8.GetBytes("폐수 웅덩이") },
            { 1050, Encoding.UTF8.GetBytes("토토라크 감옥") },
            { 1051, Encoding.UTF8.GetBytes("탐타라 묘소") },
            { 1052, Encoding.UTF8.GetBytes("구리종 광산") },
            { 1053, Encoding.UTF8.GetBytes("사스타샤 침식 동굴") },
            { 1054, Encoding.UTF8.GetBytes("금빛 골짜기") },
            { 1055, Encoding.UTF8.GetBytes("하우케타 별궁") },
            { 1056, Encoding.UTF8.GetBytes("할라탈리 수련장") },
            { 1057, Encoding.UTF8.GetBytes("브레이플록스의 야영지") },
            { 1058, Encoding.UTF8.GetBytes("카른의 무너진 사원") },
            { 1059, Encoding.UTF8.GetBytes("방랑자의 궁전") },
            { 1060, Encoding.UTF8.GetBytes("돌방패 경계초소") },
            { 1061, Encoding.UTF8.GetBytes("나무꾼의 비명") },
            { 1062, Encoding.UTF8.GetBytes("제멜 요새") },
            { 1063, Encoding.UTF8.GetBytes("옛 암다포르 성") },
            { 1064, Encoding.UTF8.GetBytes("시리우스 대등대") },
            { 1065, Encoding.UTF8.GetBytes("구리종 광산(어려움)") },
            { 1066, Encoding.UTF8.GetBytes("하우케타 별궁(어려움)") },
            { 1067, Encoding.UTF8.GetBytes("브레이플록스의 야영지(어려움)") },
            { 1068, Encoding.UTF8.GetBytes("할라탈리 수련장(어려움)") },
            { 1069, Encoding.UTF8.GetBytes("옛 암다포르 시가지") },
            { 1100, Encoding.UTF8.GetBytes("안갯빛 마을: 아담한 주택") },
            { 1101, Encoding.UTF8.GetBytes("안갯빛 마을: 일반 주택") },
            { 1102, Encoding.UTF8.GetBytes("안갯빛 마을: 대형 주택") },
            { 1103, Encoding.UTF8.GetBytes("하늘잔 마루: 아담한 주택") },
            { 1104, Encoding.UTF8.GetBytes("하늘잔 마루: 일반 주택") },
            { 1105, Encoding.UTF8.GetBytes("하늘잔 마루: 대형 주택") },
            { 1106, Encoding.UTF8.GetBytes("라벤더 안식처: 아담한 주택") },
            { 1107, Encoding.UTF8.GetBytes("라벤더 안식처: 일반 주택") },
            { 1108, Encoding.UTF8.GetBytes("라벤더 안식처: 대형 주택") },
            { 1109, Encoding.UTF8.GetBytes("1층") },
            { 1110, Encoding.UTF8.GetBytes("2층") },
            { 1111, Encoding.UTF8.GetBytes("지하 1층") },
            { 1112, Encoding.UTF8.GetBytes("1층") },
            { 1113, Encoding.UTF8.GetBytes("2층") },
            { 1114, Encoding.UTF8.GetBytes("지하 1층") },
            { 1145, Encoding.UTF8.GetBytes("주택") },
            { 1146, Encoding.UTF8.GetBytes("거주구 담당관") },
            { 1147, Encoding.UTF8.GetBytes("1층") },
            { 1148, Encoding.UTF8.GetBytes("지하 1층") },
            { 1149, Encoding.UTF8.GetBytes("선착장: 안갯빛 마을") },
            { 1150, Encoding.UTF8.GetBytes("안갯빛 마을 동부") },
            { 1151, Encoding.UTF8.GetBytes("라벤더 안식처 동부") },
            { 1152, Encoding.UTF8.GetBytes("하늘잔 마루 북부") },
            { 1153, Encoding.UTF8.GetBytes("하늘잔 마루 남동부") },
            { 1154, Encoding.UTF8.GetBytes("안내인: 하늘잔 마루") },
            { 1155, Encoding.UTF8.GetBytes("안갯빛 마을 남부") },
            { 1156, Encoding.UTF8.GetBytes("안갯빛 마을 남부(선착장)") },
            { 1157, Encoding.UTF8.GetBytes("안갯빛 마을: 개인실") },
            { 1158, Encoding.UTF8.GetBytes("하늘잔 마루: 개인실") },
            { 1159, Encoding.UTF8.GetBytes("라벤더 안식처: 개인실") },
            { 1160, Encoding.UTF8.GetBytes("개인 주택") },
            { 1161, Encoding.UTF8.GetBytes("안갯빛 마을") },
            { 1162, Encoding.UTF8.GetBytes("[확장 구역] 안갯빛 마을") },
            { 1163, Encoding.UTF8.GetBytes("하늘잔 마루") },
            { 1164, Encoding.UTF8.GetBytes("[확장 구역] 하늘잔 마루") },
            { 1165, Encoding.UTF8.GetBytes("라벤더 안식처") },
            { 1166, Encoding.UTF8.GetBytes("[확장 구역] 라벤더 안식처") },
            { 1167, Encoding.UTF8.GetBytes("[확장 구역] 안갯빛 해변") },
            { 1168, Encoding.UTF8.GetBytes("[확장 구역] 안개문 광장") },
            { 1169, Encoding.UTF8.GetBytes("[확장 구역] 멜위브 수도교") },
            { 1170, Encoding.UTF8.GetBytes("[확장 구역] 바다눈길 시장") },
            { 1171, Encoding.UTF8.GetBytes("[확장 구역] 안갯빛 마을 북동부") },
            { 1172, Encoding.UTF8.GetBytes("[확장 구역] 안갯빛 마을 남동부") },
            { 1173, Encoding.UTF8.GetBytes("[확장 구역] 안갯빛 마을 중앙부") },
            { 1174, Encoding.UTF8.GetBytes("[확장 구역] 안갯빛 마을 북서부") },
            { 1175, Encoding.UTF8.GetBytes("[확장 구역] 안갯빛 마을 남서부") },
            { 1176, Encoding.UTF8.GetBytes("[확장 구역] 바다눈길 시장(거주구 담당관)") },
            { 1177, Encoding.UTF8.GetBytes("[확장 구역] 센나의 나무") },
            { 1178, Encoding.UTF8.GetBytes("[확장 구역] 나무왕관 상점가") },
            { 1179, Encoding.UTF8.GetBytes("[확장 구역] 서낭신의 돌문") },
            { 1180, Encoding.UTF8.GetBytes("[확장 구역] 연둣빛 상점가") },
            { 1181, Encoding.UTF8.GetBytes("[확장 구역] 라벤더 안식처 북동부") },
            { 1182, Encoding.UTF8.GetBytes("[확장 구역] 라벤더 안식처 남부") },
            { 1183, Encoding.UTF8.GetBytes("[확장 구역] 라벤더 안식처 북서부") },
            { 1184, Encoding.UTF8.GetBytes("[확장 구역] 라벤더 안식처 남서부") },
            { 1185, Encoding.UTF8.GetBytes("[확장 구역] 야이누 파의 뜰") },
            { 1186, Encoding.UTF8.GetBytes("[확장 구역] 보랏빛 나루") },
            { 1187, Encoding.UTF8.GetBytes("[확장 구역] 나무왕관 상점가(거주구 담당관)") },
            { 1188, Encoding.UTF8.GetBytes("[확장 구역] 끝없는 외풍") },
            { 1189, Encoding.UTF8.GetBytes("[확장 구역] 하늘잔 시장") },
            { 1190, Encoding.UTF8.GetBytes("[확장 구역] 한마음 광장") },
            { 1191, Encoding.UTF8.GetBytes("[확장 구역] 나나모 대풍차") },
            { 1192, Encoding.UTF8.GetBytes("[확장 구역] 라우반의 팔") },
            { 1193, Encoding.UTF8.GetBytes("[확장 구역] 하늘잔 마루 동부") },
            { 1194, Encoding.UTF8.GetBytes("[확장 구역] 하늘잔 마루 북부") },
            { 1195, Encoding.UTF8.GetBytes("[확장 구역] 하늘잔 마루 남동부") },
            { 1196, Encoding.UTF8.GetBytes("[확장 구역] 하늘잔 마루 남부") },
            { 1197, Encoding.UTF8.GetBytes("[확장 구역] 하늘잔 마루 남서부") },
            { 1198, Encoding.UTF8.GetBytes("[확장 구역] 하늘잔 시장(거주구 담당관)") },
            { 1200, Encoding.UTF8.GetBytes("안개문 광장") },
            { 1201, Encoding.UTF8.GetBytes("멜위브 수도교") },
            { 1202, Encoding.UTF8.GetBytes("바다눈길 시장") },
            { 1203, Encoding.UTF8.GetBytes("안갯빛 해변") },
            { 1204, Encoding.UTF8.GetBytes("안갯빛 마을 북서부") },
            { 1205, Encoding.UTF8.GetBytes("안갯빛 마을 북동부") },
            { 1206, Encoding.UTF8.GetBytes("바다눈길 시장(거주구 담당관)") },
            { 1207, Encoding.UTF8.GetBytes("안갯빛 마을 남동부") },
            { 1208, Encoding.UTF8.GetBytes("하늘잔 시장") },
            { 1209, Encoding.UTF8.GetBytes("끝없는 외풍") },
            { 1210, Encoding.UTF8.GetBytes("한마음 광장") },
            { 1211, Encoding.UTF8.GetBytes("나나모 대풍차") },
            { 1212, Encoding.UTF8.GetBytes("라우반의 팔") },
            { 1213, Encoding.UTF8.GetBytes("하늘잔 시장(거주구 담당관)") },
            { 1214, Encoding.UTF8.GetBytes("하늘잔 마루 북동부") },
            { 1215, Encoding.UTF8.GetBytes("하늘잔 마루 서부") },
            { 1216, Encoding.UTF8.GetBytes("하늘잔 마루 동부") },
            { 1217, Encoding.UTF8.GetBytes("나무왕관 상점가") },
            { 1218, Encoding.UTF8.GetBytes("센나의 나무") },
            { 1219, Encoding.UTF8.GetBytes("서낭신의 돌문") },
            { 1220, Encoding.UTF8.GetBytes("연둣빛 상점가") },
            { 1221, Encoding.UTF8.GetBytes("야이누 파의 뜰") },
            { 1222, Encoding.UTF8.GetBytes("보랏빛 나루") },
            { 1223, Encoding.UTF8.GetBytes("라벤더 안식처 북서부") },
            { 1224, Encoding.UTF8.GetBytes("라벤더 안식처 남동부") },
            { 1225, Encoding.UTF8.GetBytes("라벤더 안식처 남서부") },
            { 1226, Encoding.UTF8.GetBytes("나무왕관 상점가(거주구 담당관)") },
            { 1227, Encoding.UTF8.GetBytes("안갯빛 마을: 지하공방") },
            { 1228, Encoding.UTF8.GetBytes("하늘잔 마루: 지하공방") },
            { 1229, Encoding.UTF8.GetBytes("라벤더 안식처: 지하공방") },
            { 1230, Encoding.UTF8.GetBytes("에테라이트") },
            { 1231, Encoding.UTF8.GetBytes("도시 내 이동") },
            { 1232, Encoding.UTF8.GetBytes("상점") },
            { 1233, Encoding.UTF8.GetBytes("수리") },
            { 1234, Encoding.UTF8.GetBytes("모그레터") },
            { 1235, Encoding.UTF8.GetBytes("초인종") },
            { 1236, Encoding.UTF8.GetBytes("집사 고용") },
            { 1237, Encoding.UTF8.GetBytes("링크셸 배포") },
            { 1238, Encoding.UTF8.GetBytes("부대 금고") },
            { 1239, Encoding.UTF8.GetBytes("초인종") },
            { 1240, Encoding.UTF8.GetBytes("침대") },
            { 1241, Encoding.UTF8.GetBytes("방명록") },
            { 1242, Encoding.UTF8.GetBytes("간이 에테라이트") },
            { 1243, Encoding.UTF8.GetBytes("던전") },
            { 1244, Encoding.UTF8.GetBytes("선착장") },
            { 1245, Encoding.UTF8.GetBytes("여객선 부두") },
            { 1246, Encoding.UTF8.GetBytes("비공정 승강장") },
            { 1247, Encoding.UTF8.GetBytes("거점") },
            { 1248, Encoding.UTF8.GetBytes("여관") },
            { 1249, Encoding.UTF8.GetBytes("모험가 길드") },
            { 1250, Encoding.UTF8.GetBytes("위층으로") },
            { 1251, Encoding.UTF8.GetBytes("아래층으로") },
            { 1252, Encoding.UTF8.GetBytes("인접 지역으로") },
            { 1253, Encoding.UTF8.GetBytes("아말쟈족 거점") },
            { 1254, Encoding.UTF8.GetBytes("실프족 거점") },
            { 1255, Encoding.UTF8.GetBytes("이크살족 거점") },
            { 1256, Encoding.UTF8.GetBytes("사하긴족 거점") },
            { 1257, Encoding.UTF8.GetBytes("코볼드족 거점") },
            { 1258, Encoding.UTF8.GetBytes("검술사 길드") },
            { 1259, Encoding.UTF8.GetBytes("격투사 길드") },
            { 1260, Encoding.UTF8.GetBytes("도끼술사 길드") },
            { 1261, Encoding.UTF8.GetBytes("창술사 길드") },
            { 1262, Encoding.UTF8.GetBytes("궁술사 길드") },
            { 1263, Encoding.UTF8.GetBytes("환술사 길드") },
            { 1264, Encoding.UTF8.GetBytes("주술사 길드") },
            { 1265, Encoding.UTF8.GetBytes("비술사 길드") },
            { 1266, Encoding.UTF8.GetBytes("목수 길드") },
            { 1267, Encoding.UTF8.GetBytes("대장장이 길드") },
            { 1268, Encoding.UTF8.GetBytes("갑주제작사 길드") },
            { 1269, Encoding.UTF8.GetBytes("보석공예가 길드") },
            { 1270, Encoding.UTF8.GetBytes("가죽공예가 길드") },
            { 1271, Encoding.UTF8.GetBytes("재봉사 길드") },
            { 1272, Encoding.UTF8.GetBytes("연금술사 길드") },
            { 1273, Encoding.UTF8.GetBytes("요리사 길드") },
            { 1274, Encoding.UTF8.GetBytes("광부 길드") },
            { 1275, Encoding.UTF8.GetBytes("원예가 길드") },
            { 1276, Encoding.UTF8.GetBytes("어부 길드") },
            { 1277, Encoding.UTF8.GetBytes("흑와단 군령부") },
            { 1278, Encoding.UTF8.GetBytes("쌍사당 통합사령부") },
            { 1279, Encoding.UTF8.GetBytes("불멸대 작전본부") },
            { 1280, Encoding.UTF8.GetBytes("거주구 담당관") },
            { 1281, Encoding.UTF8.GetBytes("장터 게시판") },
            { 1282, Encoding.UTF8.GetBytes("대결 접수처") },
            { 1283, Encoding.UTF8.GetBytes("레이드") },
            { 1284, Encoding.UTF8.GetBytes("흑와단 대기 지점") },
            { 1285, Encoding.UTF8.GetBytes("쌍사당 대기 지점") },
            { 1286, Encoding.UTF8.GetBytes("불멸대 대기 지점") },
            { 1287, Encoding.UTF8.GetBytes("마물 수배 게시판") },
            { 1288, Encoding.UTF8.GetBytes("일기예보사") },
            { 1289, Encoding.UTF8.GetBytes("쌍검사 길드") },
            { 1290, Encoding.UTF8.GetBytes("골드 소서 도우미") },
            { 1291, Encoding.UTF8.GetBytes("성 겡리올 점성원") },
            { 1292, Encoding.UTF8.GetBytes("하늘강철 기공방") },
            { 1293, Encoding.UTF8.GetBytes("초코보 수송") },
            { 1301, Encoding.UTF8.GetBytes("메테오의 그림자") },
            { 1302, Encoding.UTF8.GetBytes("구속의 고리") },
            { 1303, Encoding.UTF8.GetBytes("라그나로크급 3번함 함체 중앙부") },
            { 1304, Encoding.UTF8.GetBytes("라그나로크급 3번함 작전실") },
            { 1305, Encoding.UTF8.GetBytes("라그나로크급 3번함 제1함교") },
            { 1306, Encoding.UTF8.GetBytes("개척된 산길") },
            { 1307, Encoding.UTF8.GetBytes("골렘의 핏길") },
            { 1308, Encoding.UTF8.GetBytes("상흔의 입구") },
            { 1309, Encoding.UTF8.GetBytes("배양기 운반기구") },
            { 1310, Encoding.UTF8.GetBytes("생체 관리 구역") },
            { 1311, Encoding.UTF8.GetBytes("생체 전송 구역") },
            { 1312, Encoding.UTF8.GetBytes("파괴된 외부 격벽") },
            { 1313, Encoding.UTF8.GetBytes("상부 갑판") },
            { 1314, Encoding.UTF8.GetBytes("주 갑판") },
            { 1315, Encoding.UTF8.GetBytes("하부 갑판") },
            { 1316, Encoding.UTF8.GetBytes("좌현 제XIV구획") },
            { 1317, Encoding.UTF8.GetBytes("우현 제XIII구획") },
            { 1318, Encoding.UTF8.GetBytes("좌현 제XII구획") },
            { 1319, Encoding.UTF8.GetBytes("우현 제XI구획") },
            { 1320, Encoding.UTF8.GetBytes("좌현 제X구획") },
            { 1321, Encoding.UTF8.GetBytes("우현 제IX구획") },
            { 1322, Encoding.UTF8.GetBytes("중추 제VIII구획") },
            { 1323, Encoding.UTF8.GetBytes("중추 제VII구획") },
            { 1324, Encoding.UTF8.GetBytes("좌현 제VI구획") },
            { 1325, Encoding.UTF8.GetBytes("우현 제V구획") },
            { 1326, Encoding.UTF8.GetBytes("좌현 제IV구획") },
            { 1327, Encoding.UTF8.GetBytes("우현 제III구획") },
            { 1328, Encoding.UTF8.GetBytes("좌현 제II구획") },
            { 1329, Encoding.UTF8.GetBytes("우현 제I구획") },
            { 1330, Encoding.UTF8.GetBytes("중추 함수 구역") },
            { 1331, Encoding.UTF8.GetBytes("거인의 방") },
            { 1332, Encoding.UTF8.GetBytes("검투사의 전당") },
            { 1333, Encoding.UTF8.GetBytes("할라탈리 수련장(어려움)") },
            { 1334, Encoding.UTF8.GetBytes("대 리바이어선 쌍동선") },
            { 1335, Encoding.UTF8.GetBytes("부패한 시가지") },
            { 1336, Encoding.UTF8.GetBytes("봉인된 동굴") },
            { 1337, Encoding.UTF8.GetBytes("제1대교각") },
            { 1338, Encoding.UTF8.GetBytes("제2대교각") },
            { 1339, Encoding.UTF8.GetBytes("수원지 샛길") },
            { 1340, Encoding.UTF8.GetBytes("침입자의 임시 다리") },
            { 1341, Encoding.UTF8.GetBytes("브레이플록스의 쓰레기장") },
            { 1342, Encoding.UTF8.GetBytes("침입자의 야영지") },
            { 1343, Encoding.UTF8.GetBytes("부패의 대로") },
            { 1344, Encoding.UTF8.GetBytes("평화의 잔재") },
            { 1345, Encoding.UTF8.GetBytes("백마도사의 탑") },
            { 1346, Encoding.UTF8.GetBytes("꿈의 궁전") },
            { 1347, Encoding.UTF8.GetBytes("봉인된 동굴") },
            { 1348, Encoding.UTF8.GetBytes("악몽의 무도회장") },
            { 1349, Encoding.UTF8.GetBytes("임시 관문") },
            { 1350, Encoding.UTF8.GetBytes("새벽의 방") },
            { 1351, Encoding.UTF8.GetBytes("브레이플록스의 야영지(어려움)") },
            { 1352, Encoding.UTF8.GetBytes("안내인: 달 회랑") },
            { 1353, Encoding.UTF8.GetBytes("배양층") },
            { 1354, Encoding.UTF8.GetBytes("관리층") },
            { 1355, Encoding.UTF8.GetBytes("주 격납고") },
            { 1356, Encoding.UTF8.GetBytes("승천의 계단") },
            { 1357, Encoding.UTF8.GetBytes("무리늑대 광장") },
            { 1358, Encoding.UTF8.GetBytes("나선 회랑") },
            { 1359, Encoding.UTF8.GetBytes("수호자의 투기장") },
            { 1360, Encoding.UTF8.GetBytes("황금 회랑") },
            { 1361, Encoding.UTF8.GetBytes("제국 극장") },
            { 1362, Encoding.UTF8.GetBytes("시황제의 옥좌") },
            { 1363, Encoding.UTF8.GetBytes("심판의 나무") },
            { 1364, Encoding.UTF8.GetBytes("쌍사당 대기 지점") },
            { 1365, Encoding.UTF8.GetBytes("불멸대 대기 지점") },
            { 1366, Encoding.UTF8.GetBytes("흑와단 대기 지점") },
            { 1367, Encoding.UTF8.GetBytes("쌍사당 전초기지") },
            { 1368, Encoding.UTF8.GetBytes("불멸대 전초기지") },
            { 1369, Encoding.UTF8.GetBytes("흑와단 전초기지") },
            { 1370, Encoding.UTF8.GetBytes("알라그 시장 유적") },
            { 1371, Encoding.UTF8.GetBytes("알라그 태양신전") },
            { 1372, Encoding.UTF8.GetBytes("알라그 주거 유적") },
            { 1373, Encoding.UTF8.GetBytes("태양광장 방위탑") },
            { 1374, Encoding.UTF8.GetBytes("카르테노 평원: 외곽 유적지대") },
            { 1375, Encoding.UTF8.GetBytes("탐타라 묘소(어려움)") },
            { 1376, Encoding.UTF8.GetBytes("돌방패 경계초소(어려움)") },
            { 1377, Encoding.UTF8.GetBytes("난파선의 섬") },
            { 1378, Encoding.UTF8.GetBytes("안개수염 일당 아지트") },
            { 1379, Encoding.UTF8.GetBytes("안개수염 보물창고") },
            { 1380, Encoding.UTF8.GetBytes("기함 '바다안개호'") },
            { 1381, Encoding.UTF8.GetBytes("생존자의 해안") },
            { 1382, Encoding.UTF8.GetBytes("작은 홀") },
            { 1383, Encoding.UTF8.GetBytes("에테라이트 광장(격투사 길드/불멸대)") },
            { 1384, Encoding.UTF8.GetBytes("에테라이트 광장(모험가 길드/목수 길드/쌍사당)") },
            { 1385, Encoding.UTF8.GetBytes("에카틀 실험장") },
            { 1386, Encoding.UTF8.GetBytes("신음하는 연못") },
            { 1387, Encoding.UTF8.GetBytes("썰물길") },
            { 1388, Encoding.UTF8.GetBytes("점거 당한 아지트") },
            { 1389, Encoding.UTF8.GetBytes("숨겨진 부두") },
            { 1390, Encoding.UTF8.GetBytes("계율의 고치") },
            { 1391, Encoding.UTF8.GetBytes("영원의 성당") },
            { 1392, Encoding.UTF8.GetBytes("로웨나 기념회관") },
            { 1393, Encoding.UTF8.GetBytes("공방 '다이아몬드 제련소'") },
            { 1394, Encoding.UTF8.GetBytes("이단자의 땅굴") },
            { 1395, Encoding.UTF8.GetBytes("고요한 얼음 동굴") },
            { 1396, Encoding.UTF8.GetBytes("눈보라 절벽") },
            { 1397, Encoding.UTF8.GetBytes("이단자의 비밀 소굴") },
            { 1398, Encoding.UTF8.GetBytes("얼음기둥 뜰") },
            { 1399, Encoding.UTF8.GetBytes("아크 아파 원형극장") },
            { 1400, Encoding.UTF8.GetBytes("임시 감옥") },
            { 1401, Encoding.UTF8.GetBytes("배수 관리실") },
            { 1403, Encoding.UTF8.GetBytes("카른의 무너진 사원(어려움)") },
            { 1404, Encoding.UTF8.GetBytes("라라푸토 IV세의 지하정원") },
            { 1405, Encoding.UTF8.GetBytes("라라푸토 I세의 안뜰") },
            { 1406, Encoding.UTF8.GetBytes("라그나로크급 6번함 함체 중앙부") },
            { 1407, Encoding.UTF8.GetBytes("라그나로크급 6번함 재생 제어 구역") },
            { 1408, Encoding.UTF8.GetBytes("라그나로크급 6번함 제1함교") },
            { 1409, Encoding.UTF8.GetBytes("바하무트 핵심부") },
            { 1410, Encoding.UTF8.GetBytes("라그나로크급 4번함 제1함교") },
            { 1411, Encoding.UTF8.GetBytes("생체 관리 구역") },
            { 1412, Encoding.UTF8.GetBytes("제VII생체 구역") },
            { 1413, Encoding.UTF8.GetBytes("제IX생체 구역") },
            { 1414, Encoding.UTF8.GetBytes("제XII생체 구역") },
            { 1415, Encoding.UTF8.GetBytes("정신 접속 구역") },
            { 1416, Encoding.UTF8.GetBytes("제I신도 구역") },
            { 1417, Encoding.UTF8.GetBytes("생체 전송 구역") },
            { 1418, Encoding.UTF8.GetBytes("재생 제어 구역 외곽") },
            { 1419, Encoding.UTF8.GetBytes("재생 제어 구역 내곽") },
            { 1420, Encoding.UTF8.GetBytes("1번함 관제 구역") },
            { 1421, Encoding.UTF8.GetBytes("8번함 관제 구역") },
            { 1422, Encoding.UTF8.GetBytes("9번함 관제 구역") },
            { 1423, Encoding.UTF8.GetBytes("4번함 관제 구역") },
            { 1424, Encoding.UTF8.GetBytes("2번함 관제 구역") },
            { 1425, Encoding.UTF8.GetBytes("구속의 고리 제어 구역") },
            { 1426, Encoding.UTF8.GetBytes("핵심 제어 구역") },
            { 1427, Encoding.UTF8.GetBytes("에델바이스 상회") },
            { 1428, Encoding.UTF8.GetBytes("선착장 창고") },
            { 1429, Encoding.UTF8.GetBytes("응접실") },
            { 1431, Encoding.UTF8.GetBytes("어둠의 세계") },
            { 1432, Encoding.UTF8.GetBytes("케르베로스의 위장") },
            { 1433, Encoding.UTF8.GetBytes("눈의 영역") },
            { 1434, Encoding.UTF8.GetBytes("용의 영역") },
            { 1435, Encoding.UTF8.GetBytes("개의 영역") },
            { 1436, Encoding.UTF8.GetBytes("어둠의 영역") },
            { 1437, Encoding.UTF8.GetBytes("케르베로스의 위장") },
            { 1438, Encoding.UTF8.GetBytes("어둠의 해변") },
            { 1439, Encoding.UTF8.GetBytes("눈의 섬") },
            { 1440, Encoding.UTF8.GetBytes("눈의 전망대") },
            { 1441, Encoding.UTF8.GetBytes("목의 섬") },
            { 1442, Encoding.UTF8.GetBytes("용의 사냥터") },
            { 1443, Encoding.UTF8.GetBytes("입의 섬") },
            { 1444, Encoding.UTF8.GetBytes("개의 대문") },
            { 1445, Encoding.UTF8.GetBytes("어둠의 전송기") },
            { 1446, Encoding.UTF8.GetBytes("어둠의 고치") },
            { 1447, Encoding.UTF8.GetBytes("옛 암다포르 성(어려움)") },
            { 1448, Encoding.UTF8.GetBytes("비탄의 앞뜰") },
            { 1449, Encoding.UTF8.GetBytes("고뇌의 방") },
            { 1450, Encoding.UTF8.GetBytes("재앙의 십자로") },
            { 1451, Encoding.UTF8.GetBytes("유혈의 무도회장") },
            { 1452, Encoding.UTF8.GetBytes("대형 원양어선") },
            { 1453, Encoding.UTF8.GetBytes("에델바이스 상회<br>(쌍검사 길드)") },
            { 1484, Encoding.UTF8.GetBytes("골드 소서") },
            { 1485, Encoding.UTF8.GetBytes("입구 광장") },
            { 1486, Encoding.UTF8.GetBytes("에테라이트 광장") },
            { 1487, Encoding.UTF8.GetBytes("카드 광장") },
            { 1488, Encoding.UTF8.GetBytes("신비의 광장") },
            { 1489, Encoding.UTF8.GetBytes("원형 광장") },
            { 1490, Encoding.UTF8.GetBytes("이벤트 광장") },
            { 1491, Encoding.UTF8.GetBytes("골드 소서 비공정 승강장") },
            { 1492, Encoding.UTF8.GetBytes("중앙 카운터") },
            { 1493, Encoding.UTF8.GetBytes("초코보 승강기") },
            { 1494, Encoding.UTF8.GetBytes("자보텐더") },
            { 1495, Encoding.UTF8.GetBytes("코렐 산") },
            { 1496, Encoding.UTF8.GetBytes("이벤트 무대") },
            { 1497, Encoding.UTF8.GetBytes("복권 추첨소") },
            { 1498, Encoding.UTF8.GetBytes("맨더빌 라운지") },
            { 1499, Encoding.UTF8.GetBytes("맨더빌 라운지") },
            { 1500, Encoding.UTF8.GetBytes("초코보 광장") },
            { 1501, Encoding.UTF8.GetBytes("초코보 경주 카운터") },
            { 1502, Encoding.UTF8.GetBytes("초코보 승강기") },
            { 1503, Encoding.UTF8.GetBytes("무너진 구조체") },
            { 1504, Encoding.UTF8.GetBytes("제국군 임시 작업장") },
            { 1505, Encoding.UTF8.GetBytes("부유가스 충전 구역") },
            { 1506, Encoding.UTF8.GetBytes("환룡의 등") },
            { 1507, Encoding.UTF8.GetBytes("묵약의 방") },
            { 1508, Encoding.UTF8.GetBytes("（?）第１障壁") },
            { 1509, Encoding.UTF8.GetBytes("（?）第2障壁") },
            { 1510, Encoding.UTF8.GetBytes("대 드래곤 쇠뇌: 플라비앵") },
            { 1511, Encoding.UTF8.GetBytes("（?）第3障壁") },
            { 1512, Encoding.UTF8.GetBytes("대 드래곤 쇠뇌: 실베트렐") },
            { 1513, Encoding.UTF8.GetBytes("（?）第4障壁") },
            { 1514, Encoding.UTF8.GetBytes("대 드래곤 쇠뇌: 할드라스") },
            { 1515, Encoding.UTF8.GetBytes("성도의 문") },
            { 1516, Encoding.UTF8.GetBytes("（?）防衛橋エリア名") },
            { 1517, Encoding.UTF8.GetBytes("에테라이트 광장") },
            { 1518, Encoding.UTF8.GetBytes("입구 광장(카드 광장)") },
            { 1519, Encoding.UTF8.GetBytes("신비의 광장 동쪽") },
            { 1520, Encoding.UTF8.GetBytes("신비의 광장 서쪽") },
            { 1521, Encoding.UTF8.GetBytes("이벤트 광장") },
            { 1522, Encoding.UTF8.GetBytes("복권 추첨소") },
            { 1523, Encoding.UTF8.GetBytes("원형 광장") },
            { 1524, Encoding.UTF8.GetBytes("초코보 광장") },
            { 1525, Encoding.UTF8.GetBytes("아래층") },
            { 1526, Encoding.UTF8.GetBytes("가운데층") },
            { 1527, Encoding.UTF8.GetBytes("위층") },
            { 1528, Encoding.UTF8.GetBytes("1층") },
            { 1529, Encoding.UTF8.GetBytes("3층") },
            { 1530, Encoding.UTF8.GetBytes("지하 1층") },
            { 1531, Encoding.UTF8.GetBytes("외곽 안뜰") },
            { 1532, Encoding.UTF8.GetBytes("기병 막사") },
            { 1533, Encoding.UTF8.GetBytes("요새 내부") },
            { 1534, Encoding.UTF8.GetBytes("연병장") },
            { 1535, Encoding.UTF8.GetBytes("작전회의실") },
            { 1536, Encoding.UTF8.GetBytes("성 겡리올 예배당") },
            { 1537, Encoding.UTF8.GetBytes("요새 외벽") },
            { 1538, Encoding.UTF8.GetBytes("결승선") },
            { 1539, Encoding.UTF8.GetBytes("뜀뛰는 돌의 섬") },
            { 1540, Encoding.UTF8.GetBytes("나무가 흔들리는 길") },
            { 1541, Encoding.UTF8.GetBytes("물에 감싸인 정원") },
            { 1542, Encoding.UTF8.GetBytes("높바람 부는 신의 섬") },
            { 1543, Encoding.UTF8.GetBytes("바람이 머무는 제단") },
            { 1544, Encoding.UTF8.GetBytes("구름이 태어나는 신전") },
            { 1545, Encoding.UTF8.GetBytes("박물함 입구") },
            { 1546, Encoding.UTF8.GetBytes("역사 전시실") },
            { 1547, Encoding.UTF8.GetBytes("병기 전시실") },
            { 1548, Encoding.UTF8.GetBytes("박물함 방위실") },
            { 1549, Encoding.UTF8.GetBytes("제III전시구역") },
            { 1550, Encoding.UTF8.GetBytes("특급 키메라 배양실") },
            { 1551, Encoding.UTF8.GetBytes("보라 관제구역") },
            { 1552, Encoding.UTF8.GetBytes("진홍 관제구역") },
            { 1553, Encoding.UTF8.GetBytes("연녹 관제구역") },
            { 1554, Encoding.UTF8.GetBytes("현실확장실") },
            { 1555, Encoding.UTF8.GetBytes("뱃머리 구조체") },
            { 1556, Encoding.UTF8.GetBytes("좌현 구조체") },
            { 1557, Encoding.UTF8.GetBytes("우현 구조체") },
            { 1558, Encoding.UTF8.GetBytes("예배당 신랑") },
            { 1559, Encoding.UTF8.GetBytes("예배당 측랑") },
            { 1560, Encoding.UTF8.GetBytes("교황청 안뜰") },
            { 1561, Encoding.UTF8.GetBytes("빙천궁") },
            { 1562, Encoding.UTF8.GetBytes("교황청 신랑") },
            { 1563, Encoding.UTF8.GetBytes("성 토르당 대성당") },
            { 1564, Encoding.UTF8.GetBytes("예배당 승강실") },
            { 1565, Encoding.UTF8.GetBytes("정원 동쪽 승강실") },
            { 1566, Encoding.UTF8.GetBytes("정원 서쪽 승강실") },
            { 1567, Encoding.UTF8.GetBytes("빙천궁 승강실") },
            { 1568, Encoding.UTF8.GetBytes("빙천궁 성소") },
            { 1570, Encoding.UTF8.GetBytes("성가대석") },
            { 1571, Encoding.UTF8.GetBytes("기사단 강당") },
            { 1572, Encoding.UTF8.GetBytes("빙천궁 예배당") },
            { 1573, Encoding.UTF8.GetBytes("외부 둥지") },
            { 1574, Encoding.UTF8.GetBytes("내부 둥지") },
            { 1575, Encoding.UTF8.GetBytes("둥지 꼭대기") },
            { 1576, Encoding.UTF8.GetBytes("중심 구조체") },
            { 1577, Encoding.UTF8.GetBytes("아크 팔 라이") },
            { 1580, Encoding.UTF8.GetBytes("텐 우르") },
            { 1581, Encoding.UTF8.GetBytes("에른 스코르") },
            { 1582, Encoding.UTF8.GetBytes("니드호그 안") },
            { 1583, Encoding.UTF8.GetBytes("파괴된 접점") },
            { 1584, Encoding.UTF8.GetBytes("바다뱀의 목구멍") },
            { 1585, Encoding.UTF8.GetBytes("봉인된 바위섬 상륙 지점") },
            { 1586, Encoding.UTF8.GetBytes("좁은길 침식곡") },
            { 1587, Encoding.UTF8.GetBytes("제비꼬리 해안") },
            { 1588, Encoding.UTF8.GetBytes("선발대 발굴지") },
            { 1589, Encoding.UTF8.GetBytes("정문") },
            { 1590, Encoding.UTF8.GetBytes("기계병기 연구동") },
            { 1591, Encoding.UTF8.GetBytes("물자 운반로") },
            { 1592, Encoding.UTF8.GetBytes("물자 분배장") },
            { 1593, Encoding.UTF8.GetBytes("생체병기 연구동") },
            { 1594, Encoding.UTF8.GetBytes("특수 경계 통로") },
            { 1595, Encoding.UTF8.GetBytes("삼투신 제어구") },
            { 1596, Encoding.UTF8.GetBytes("신경연결부") },
            { 1597, Encoding.UTF8.GetBytes("마빈 구체") },
            { 1598, Encoding.UTF8.GetBytes("견본 기체 실험고") },
            { 1599, Encoding.UTF8.GetBytes("평가시험장") },
            { 1600, Encoding.UTF8.GetBytes("제VII배양층") },
            { 1601, Encoding.UTF8.GetBytes("제VIII배양층") },
            { 1602, Encoding.UTF8.GetBytes("신경연결기관") },
            { 1603, Encoding.UTF8.GetBytes("경계병기 연구동") },
            { 1604, Encoding.UTF8.GetBytes("생체병기 연구동") },
            { 1605, Encoding.UTF8.GetBytes("삼투신 제어구") },
            { 1606, Encoding.UTF8.GetBytes("남쪽 산비탈") },
            { 1607, Encoding.UTF8.GetBytes("영봉의 혈관") },
            { 1608, Encoding.UTF8.GetBytes("불의의 산길") },
            { 1609, Encoding.UTF8.GetBytes("청록 절벽") },
            { 1610, Encoding.UTF8.GetBytes("붉은 무덤") },
            { 1611, Encoding.UTF8.GetBytes("푸른 무덤") },
            { 1612, Encoding.UTF8.GetBytes("영봉의 상처") },
            { 1613, Encoding.UTF8.GetBytes("헤스 아파") },
            { 1614, Encoding.UTF8.GetBytes("솜 알: 불의의 산길") },
            { 1615, Encoding.UTF8.GetBytes("솜 알: 영봉의 혈관") },
            { 1616, Encoding.UTF8.GetBytes("솜 알: 영봉의 상처") },
            { 1617, Encoding.UTF8.GetBytes("묵상열람실") },
            { 1618, Encoding.UTF8.GetBytes("환상서고") },
            { 1619, Encoding.UTF8.GetBytes("괴상회합실") },
            { 1620, Encoding.UTF8.GetBytes("에테르학 연구실") },
            { 1621, Encoding.UTF8.GetBytes("박물학 연구실") },
            { 1622, Encoding.UTF8.GetBytes("몽상금서고") },
            { 1623, Encoding.UTF8.GetBytes("악마서 복도") },
            { 1624, Encoding.UTF8.GetBytes("점성학 연구실") },
            { 1625, Encoding.UTF8.GetBytes("광상금서고") },
            { 1626, Encoding.UTF8.GetBytes("승강기") },
            { 1627, Encoding.UTF8.GetBytes("승강기") },
            { 1628, Encoding.UTF8.GetBytes("고르디우스의 주먹") },
            { 1629, Encoding.UTF8.GetBytes("제583 정비갱도") },
            { 1630, Encoding.UTF8.GetBytes("제262 증기기관실") },
            { 1631, Encoding.UTF8.GetBytes("제44 기공병 격납고") },
            { 1632, Encoding.UTF8.GetBytes("제8 대형 격납고") },
            { 1633, Encoding.UTF8.GetBytes("고르디우스의 손목") },
            { 1634, Encoding.UTF8.GetBytes("제542 정비갱도") },
            { 1635, Encoding.UTF8.GetBytes("제541 정비갱도") },
            { 1636, Encoding.UTF8.GetBytes("제539 정비갱도") },
            { 1637, Encoding.UTF8.GetBytes("제12 대형 격납고") },
            { 1638, Encoding.UTF8.GetBytes("고르디우스의 팔") },
            { 1639, Encoding.UTF8.GetBytes("제523 정비갱도") },
            { 1640, Encoding.UTF8.GetBytes("전략회의소 1층") },
            { 1641, Encoding.UTF8.GetBytes("전략회의소 2층") },
            { 1642, Encoding.UTF8.GetBytes("전략회의소 3층") },
            { 1643, Encoding.UTF8.GetBytes("전략회의소 4층") },
            { 1644, Encoding.UTF8.GetBytes("제9대형복수기") },
            { 1645, Encoding.UTF8.GetBytes("고르디우스의 어깨") },
            { 1648, Encoding.UTF8.GetBytes("손목 위층") },
            { 1649, Encoding.UTF8.GetBytes("손목 아래층") },
            { 1650, Encoding.UTF8.GetBytes("에테라이트 광장") },
            { 1651, Encoding.UTF8.GetBytes("잊힌 기사 주점(성 발루아양 광장)") },
            { 1652, Encoding.UTF8.GetBytes("하늘강철 기공방(성 레네트 광장)") },
            { 1653, Encoding.UTF8.GetBytes("구름안개 거리") },
            { 1654, Encoding.UTF8.GetBytes("성 겡리올 점성원(비공정 승강장)") },
            { 1655, Encoding.UTF8.GetBytes("시장(보석홀장 거리)") },
            { 1656, Encoding.UTF8.GetBytes("성 레마노 대성당") },
            { 1657, Encoding.UTF8.GetBytes("신성재판소") },
            { 1658, Encoding.UTF8.GetBytes("최후의 보루(포르탕 저택)") },
            { 1659, Encoding.UTF8.GetBytes("성도의 문(커르다스 중앙고지 방면)") },
            { 1660, Encoding.UTF8.GetBytes("개발실") },
            { 1661, Encoding.UTF8.GetBytes("나오키의 방") },
            { 1662, Encoding.UTF8.GetBytes("음악실") },
            { 1666, Encoding.UTF8.GetBytes("알렉산더 결절점") },
            { 1667, Encoding.UTF8.GetBytes("고르디우스의 매듭") },
            { 2000, Encoding.UTF8.GetBytes("고지 드라바니아") },
            { 2001, Encoding.UTF8.GetBytes("저지 드라바니아") },
            { 2002, Encoding.UTF8.GetBytes("드라바니아 구름바다") },
            { 2003, Encoding.UTF8.GetBytes("초코보 숲") },
            { 2004, Encoding.UTF8.GetBytes("연기 황야") },
            { 2005, Encoding.UTF8.GetBytes("그나스의 토굴집") },
            { 2006, Encoding.UTF8.GetBytes("쇠락한 아발로니아") },
            { 2007, Encoding.UTF8.GetBytes("솜 알 산기슭") },
            { 2008, Encoding.UTF8.GetBytes("애도의 바위굴") },
            { 2009, Encoding.UTF8.GetBytes("예술의 거리") },
            { 2010, Encoding.UTF8.GetBytes("심사의 거리") },
            { 2011, Encoding.UTF8.GetBytes("철학의 거리") },
            { 2012, Encoding.UTF8.GetBytes("솜 알 멧부리") },
            { 2013, Encoding.UTF8.GetBytes("에일 톰") },
            { 2014, Encoding.UTF8.GetBytes("지상왕의 영지") },
            { 2015, Encoding.UTF8.GetBytes("네 기둥 광장") },
            { 2016, Encoding.UTF8.GetBytes("올 탄") },
            { 2017, Encoding.UTF8.GetBytes("잔디섬") },
            { 2018, Encoding.UTF8.GetBytes("꼬리깃 마을") },
            { 2019, Encoding.UTF8.GetBytes("비탄의 폭포") },
            { 2020, Encoding.UTF8.GetBytes("지난날 강") },
            { 2021, Encoding.UTF8.GetBytes("바스의 토굴집") },
            { 2022, Encoding.UTF8.GetBytes("사룡상") },
            { 2023, Encoding.UTF8.GetBytes("병정굴") },
            { 2024, Encoding.UTF8.GetBytes("무신굴") },
            { 2025, Encoding.UTF8.GetBytes("부정한 삼탑") },
            { 2027, Encoding.UTF8.GetBytes("대너 가도") },
            { 2028, Encoding.UTF8.GetBytes("에스 다이") },
            { 2029, Encoding.UTF8.GetBytes("용의 식탁") },
            { 2030, Encoding.UTF8.GetBytes("빛무리 제단") },
            { 2031, Encoding.UTF8.GetBytes("솜 알") },
            { 2032, Encoding.UTF8.GetBytes("대공방") },
            { 2033, Encoding.UTF8.GetBytes("창조의 길") },
            { 2034, Encoding.UTF8.GetBytes("성 모샨 식물원") },
            { 2035, Encoding.UTF8.GetBytes("급류 삼각주") },
            { 2036, Encoding.UTF8.GetBytes("마토야의 동굴") },
            { 2037, Encoding.UTF8.GetBytes("석학의 길") },
            { 2038, Encoding.UTF8.GetBytes("구브라 환상도서관") },
            { 2039, Encoding.UTF8.GetBytes("살리아크 강") },
            { 2040, Encoding.UTF8.GetBytes("살리아크의 물병") },
            { 2041, Encoding.UTF8.GetBytes("기공성 알렉산더") },
            { 2042, Encoding.UTF8.GetBytes("모그모그 고향") },
            { 2043, Encoding.UTF8.GetBytes("편지집") },
            { 2044, Encoding.UTF8.GetBytes("스도엔") },
            { 2045, Encoding.UTF8.GetBytes("아사 구름다리") },
            { 2046, Encoding.UTF8.GetBytes("하얀 궁전") },
            { 2047, Encoding.UTF8.GetBytes("비룡 착륙지") },
            { 2048, Encoding.UTF8.GetBytes("살 움 카쉬") },
            { 2049, Encoding.UTF8.GetBytes("동쪽 감시탑") },
            { 2050, Encoding.UTF8.GetBytes("용의 둥지") },
            { 2051, Encoding.UTF8.GetBytes("성녀 시바 상") },
            { 2052, Encoding.UTF8.GetBytes("학문의 거리") },
            { 2053, Encoding.UTF8.GetBytes("살금걸음 오솔길") },
            { 2054, Encoding.UTF8.GetBytes("수사슴 다리") },
            { 2055, Encoding.UTF8.GetBytes("어미의 맹세 유적") },
            { 2061, Encoding.UTF8.GetBytes("부정한 마을") },
            { 2064, Encoding.UTF8.GetBytes("아네스 소") },
            { 2065, Encoding.UTF8.GetBytes("돌칼기둥 벼랑") },
            { 2066, Encoding.UTF8.GetBytes("대현자 기념비") },
            { 2067, Encoding.UTF8.GetBytes("유격수 야영지") },
            { 2068, Encoding.UTF8.GetBytes("오른 원생림") },
            { 2069, Encoding.UTF8.GetBytes("묵상의 길") },
            { 2070, Encoding.UTF8.GetBytes("아술론 옛터") },
            { 2073, Encoding.UTF8.GetBytes("확신의 길") },
            { 2074, Encoding.UTF8.GetBytes("구브라 산") },
            { 2075, Encoding.UTF8.GetBytes("외톨이 나무") },
            { 2076, Encoding.UTF8.GetBytes("그론 레이") },
            { 2077, Encoding.UTF8.GetBytes("으뜸 나무") },
            { 2078, Encoding.UTF8.GetBytes("남쪽 성벽") },
            { 2079, Encoding.UTF8.GetBytes("서쪽 샘") },
            { 2080, Encoding.UTF8.GetBytes("지상왕 상") },
            { 2081, Encoding.UTF8.GetBytes("무신의 투기장") },
            { 2082, Encoding.UTF8.GetBytes("이딜샤이어") },
            { 2083, Encoding.UTF8.GetBytes("공물 구멍") },
            { 2084, Encoding.UTF8.GetBytes("앞표지 다리") },
            { 2085, Encoding.UTF8.GetBytes("뒤표지 다리") },
            { 2086, Encoding.UTF8.GetBytes("대현자 기념비") },
            { 2087, Encoding.UTF8.GetBytes("에테라이트 광장") },
            { 2100, Encoding.UTF8.GetBytes("아발라시아 구름바다") },
            { 2101, Encoding.UTF8.GetBytes("아지스 라") },
            { 2102, Encoding.UTF8.GetBytes("구름마루") },
            { 2103, Encoding.UTF8.GetBytes("부르 시안시란") },
            { 2104, Encoding.UTF8.GetBytes("분두 오크 벤두") },
            { 2105, Encoding.UTF8.GetBytes("푸른하늘 창") },
            { 2106, Encoding.UTF8.GetBytes("수난의 섬") },
            { 2107, Encoding.UTF8.GetBytes("오크 분두 바나") },
            { 2108, Encoding.UTF8.GetBytes("오크 분두 모크") },
            { 2109, Encoding.UTF8.GetBytes("알파 구역") },
            { 2110, Encoding.UTF8.GetBytes("베타 구역") },
            { 2111, Encoding.UTF8.GetBytes("감마 구역") },
            { 2112, Encoding.UTF8.GetBytes("델타 구역") },
            { 2113, Encoding.UTF8.GetBytes("생태공원") },
            { 2114, Encoding.UTF8.GetBytes("아지스 라 기함섬") },
            { 2115, Encoding.UTF8.GetBytes("수호자호") },
            { 2116, Encoding.UTF8.GetBytes("구름마루 초소") },
            { 2117, Encoding.UTF8.GetBytes("장미의 집") },
            { 2118, Encoding.UTF8.GetBytes("오크 군두") },
            { 2119, Encoding.UTF8.GetBytes("철새 보금자리") },
            { 2120, Encoding.UTF8.GetBytes("구름웅덩이") },
            { 2121, Encoding.UTF8.GetBytes("웅변가 벤두의 집") },
            { 2122, Encoding.UTF8.GetBytes("흰고래 왕관") },
            { 2123, Encoding.UTF8.GetBytes("오크 준두") },
            { 2124, Encoding.UTF8.GetBytes("오크 분두") },
            { 2125, Encoding.UTF8.GetBytes("떨어진 깃털의 집") },
            { 2126, Encoding.UTF8.GetBytes("환상열석") },
            { 2127, Encoding.UTF8.GetBytes("헤느거의 도가니") },
            { 2128, Encoding.UTF8.GetBytes("찬바람섬") },
            { 2129, Encoding.UTF8.GetBytes("모크 우글 섬") },
            { 2130, Encoding.UTF8.GetBytes("거두지 않는 섬") },
            { 2131, Encoding.UTF8.GetBytes("나선 발착장") },
            { 2132, Encoding.UTF8.GetBytes("알파 교신탑") },
            { 2133, Encoding.UTF8.GetBytes("에테르 공급시설") },
            { 2134, Encoding.UTF8.GetBytes("제II전송고리") },
            { 2135, Encoding.UTF8.GetBytes("제III전송고리") },
            { 2136, Encoding.UTF8.GetBytes("생체 배양소") },
            { 2137, Encoding.UTF8.GetBytes("돌연변이 실험장") },
            { 2138, Encoding.UTF8.GetBytes("제IV전송고리") },
            { 2139, Encoding.UTF8.GetBytes("제V전송고리") },
            { 2140, Encoding.UTF8.GetBytes("비공전함 그라티온") },
            { 2141, Encoding.UTF8.GetBytes("비공전함 착륙 지점") },
            { 2142, Encoding.UTF8.GetBytes("카스트룸 솔루스") },
            { 2143, Encoding.UTF8.GetBytes("제VI전송고리") },
            { 2144, Encoding.UTF8.GetBytes("제VII전송고리") },
            { 2145, Encoding.UTF8.GetBytes("반려자의 책형대") },
            { 2146, Encoding.UTF8.GetBytes("에쉬 톰") },
            { 2147, Encoding.UTF8.GetBytes("마과학 연구소") },
            { 2148, Encoding.UTF8.GetBytes("무한연속 박물함") },
            { 2149, Encoding.UTF8.GetBytes("신경연결기관") },
            { 2150, Encoding.UTF8.GetBytes("특이점 반응기관") },
            { 2151, Encoding.UTF8.GetBytes("쪽빛 성역") },
            { 2152, Encoding.UTF8.GetBytes("마지막 발걸음") },
            { 2153, Encoding.UTF8.GetBytes("들소 벌판") },
            { 2154, Encoding.UTF8.GetBytes("물안개 폭포") },
            { 2156, Encoding.UTF8.GetBytes("티끌점괘 곶") },
            { 2159, Encoding.UTF8.GetBytes("부서진 등뼈") },
            { 2160, Encoding.UTF8.GetBytes("기원의 섬") },
            { 2161, Encoding.UTF8.GetBytes("크리스탈 증식로") },
            { 2162, Encoding.UTF8.GetBytes("종합 냉각소") },
            { 2164, Encoding.UTF8.GetBytes("키메라 생성 연구소") },
            { 2166, Encoding.UTF8.GetBytes("생태공원 관리국") },
            { 2170, Encoding.UTF8.GetBytes("고대 대성당") },
            { 2172, Encoding.UTF8.GetBytes("델타 수도국") },
            { 2173, Encoding.UTF8.GetBytes("큰갓털나무") },
            { 2174, Encoding.UTF8.GetBytes("삼투신 상") },
            { 2175, Encoding.UTF8.GetBytes("격리실험장") },
            { 2176, Encoding.UTF8.GetBytes("기동보급함") },
            { 2177, Encoding.UTF8.GetBytes("초성간교신탑") },
            { 2178, Encoding.UTF8.GetBytes("특이점 반응기관") },
            { 2179, Encoding.UTF8.GetBytes("마대륙 중추부") },
            { 2180, Encoding.UTF8.GetBytes("잔해섬") },
            { 2200, Encoding.UTF8.GetBytes("커르다스 서부고지") },
            { 2201, Encoding.UTF8.GetBytes("맞가람 골짜기") },
            { 2202, Encoding.UTF8.GetBytes("쌍둥이 연못") },
            { 2203, Encoding.UTF8.GetBytes("붉은 가장자리") },
            { 2204, Encoding.UTF8.GetBytes("매의 보금자리") },
            { 2205, Encoding.UTF8.GetBytes("커르다스 강") },
            { 2206, Encoding.UTF8.GetBytes("빠른물살 강") },
            { 2207, Encoding.UTF8.GetBytes("고르가뉴 목장") },
            { 2208, Encoding.UTF8.GetBytes("솔송나무 마을") },
            { 2209, Encoding.UTF8.GetBytes("맞가람 야영지") },
            { 2210, Encoding.UTF8.GetBytes("죽음의 호수") },
            { 2211, Encoding.UTF8.GetBytes("잿빛 호수") },
            { 2212, Encoding.UTF8.GetBytes("용이 잠든 섬") },
            { 2213, Encoding.UTF8.GetBytes("예티 서식지") },
            { 2214, Encoding.UTF8.GetBytes("어스름 요새") },
            { 2215, Encoding.UTF8.GetBytes("할드라스 상") },
            { 2216, Encoding.UTF8.GetBytes("모루탑") },
            { 2217, Encoding.UTF8.GetBytes("회색꼬리 폭포") },
            { 2218, Encoding.UTF8.GetBytes("이단자의 갱도") },
            { 2219, Encoding.UTF8.GetBytes("점판암 산맥") },
            { 2220, Encoding.UTF8.GetBytes("성 피네아 연대 야영지") },
            { 2221, Encoding.UTF8.GetBytes("흑철교") },
            { 2222, Encoding.UTF8.GetBytes("아홉째 홀장") },
            { 2223, Encoding.UTF8.GetBytes("고르가뉴 목초지") },
            { 2224, Encoding.UTF8.GetBytes("북녘별호") },
            { 2225, Encoding.UTF8.GetBytes("뱃밥 나루터") },
            { 2227, Encoding.UTF8.GetBytes("용숨결 온천") },
            { 2228, Encoding.UTF8.GetBytes("감시자의 뼈") },
            { 2237, Encoding.UTF8.GetBytes("창협곡 관문") },
            { 2238, Encoding.UTF8.GetBytes("부름바위") },
            { 2300, Encoding.UTF8.GetBytes("이슈가르드 하층") },
            { 2301, Encoding.UTF8.GetBytes("이슈가르드 상층") },
            { 2302, Encoding.UTF8.GetBytes("성도의 문") },
            { 2303, Encoding.UTF8.GetBytes("에테라이트 광장") },
            { 2304, Encoding.UTF8.GetBytes("성 발루아양 광장") },
            { 2305, Encoding.UTF8.GetBytes("성 레네트 광장") },
            { 2306, Encoding.UTF8.GetBytes("성 발루아양 거리") },
            { 2307, Encoding.UTF8.GetBytes("청빈의 개선문") },
            { 2308, Encoding.UTF8.GetBytes("할로네의 자비") },
            { 2309, Encoding.UTF8.GetBytes("구름안개 거리") },
            { 2310, Encoding.UTF8.GetBytes("여인숙 '아홉 구름'") },
            { 2311, Encoding.UTF8.GetBytes("잊힌 기사 주점") },
            { 2312, Encoding.UTF8.GetBytes("신전기사단 본부") },
            { 2313, Encoding.UTF8.GetBytes("나풀깃 투기장") },
            { 2314, Encoding.UTF8.GetBytes("하늘강철 기공방") },
            { 2315, Encoding.UTF8.GetBytes("초코보 대여소") },
            { 2316, Encoding.UTF8.GetBytes("성도 대축사") },
            { 2317, Encoding.UTF8.GetBytes("보석홀장 거리") },
            { 2318, Encoding.UTF8.GetBytes("뒤랑데르 저택") },
            { 2319, Encoding.UTF8.GetBytes("아유나르트 저택") },
            { 2320, Encoding.UTF8.GetBytes("포르탕 저택") },
            { 2321, Encoding.UTF8.GetBytes("제멜 저택") },
            { 2322, Encoding.UTF8.GetBytes("성 겡리올 점성원") },
            { 2323, Encoding.UTF8.GetBytes("비공정 승강장") },
            { 2324, Encoding.UTF8.GetBytes("보렐 저택") },
            { 2325, Encoding.UTF8.GetBytes("신성재판소") },
            { 2326, Encoding.UTF8.GetBytes("둥근방패 대광장") },
            { 2327, Encoding.UTF8.GetBytes("이슈가르드 교황청") },
            { 2328, Encoding.UTF8.GetBytes("성 레마노 대성당") },
            { 2329, Encoding.UTF8.GetBytes("건국 열두 기사상") },
            { 2330, Encoding.UTF8.GetBytes("최후의 보루") },
            { 2331, Encoding.UTF8.GetBytes("가경자의 개선문") },
            { 2332, Encoding.UTF8.GetBytes("에딘 소광장") },
            { 2333, Encoding.UTF8.GetBytes("서쪽 주랑") },
            { 2334, Encoding.UTF8.GetBytes("동쪽 주랑") },
            { 2335, Encoding.UTF8.GetBytes("신전기사단 총장실") },
            { 2336, Encoding.UTF8.GetBytes("결투재판장") },
            { 2337, Encoding.UTF8.GetBytes("성 앙달림 신학원") },
            { 2338, Encoding.UTF8.GetBytes("나풀깃 투기장") },
        };
    }
}
