using System.Collections.Generic;
using System.Text;

namespace FFChat
{
    static partial class FFData
    {
        public static readonly IDictionary<int, byte[]> Weather = new Dictionary<int, byte[]>
        {
            { 1, Encoding.UTF8.GetBytes("쾌청") },
            { 2, Encoding.UTF8.GetBytes("맑음") },
            { 3, Encoding.UTF8.GetBytes("흐림") },
            { 4, Encoding.UTF8.GetBytes("안개") },
            { 5, Encoding.UTF8.GetBytes("바람") },
            { 6, Encoding.UTF8.GetBytes("강풍") },
            { 7, Encoding.UTF8.GetBytes("비") },
            { 8, Encoding.UTF8.GetBytes("폭우") },
            { 9, Encoding.UTF8.GetBytes("번개") },
            { 10, Encoding.UTF8.GetBytes("뇌우") },
            { 11, Encoding.UTF8.GetBytes("모래먼지") },
            { 12, Encoding.UTF8.GetBytes("모래폭풍") },
            { 13, Encoding.UTF8.GetBytes("열파") },
            { 14, Encoding.UTF8.GetBytes("작열파") },
            { 15, Encoding.UTF8.GetBytes("눈") },
            { 16, Encoding.UTF8.GetBytes("눈보라") },
            { 17, Encoding.UTF8.GetBytes("요마의 안개") },
            { 18, Encoding.UTF8.GetBytes("오로라") },
            { 19, Encoding.UTF8.GetBytes("어둠") },
            { 20, Encoding.UTF8.GetBytes("투기") },
            { 21, Encoding.UTF8.GetBytes("흐림") },
            { 22, Encoding.UTF8.GetBytes("뇌운") },
            { 23, Encoding.UTF8.GetBytes("파랑") },
            { 24, Encoding.UTF8.GetBytes("파랑") },
            { 25, Encoding.UTF8.GetBytes("먹구름") },
            { 26, Encoding.UTF8.GetBytes("작열파") },
            { 27, Encoding.UTF8.GetBytes("요마의 안개") },
            { 28, Encoding.UTF8.GetBytes("강풍") },
            { 29, Encoding.UTF8.GetBytes("분화") },
            { 30, Encoding.UTF8.GetBytes("맑음") },
            { 31, Encoding.UTF8.GetBytes("맑음") },
            { 32, Encoding.UTF8.GetBytes("맑음") },
            { 33, Encoding.UTF8.GetBytes("맑음") },
            { 34, Encoding.UTF8.GetBytes("맑음") },
            { 35, Encoding.UTF8.GetBytes("극광") },
            { 36, Encoding.UTF8.GetBytes("용핵") },
            { 37, Encoding.UTF8.GetBytes("용핵") },
            { 38, Encoding.UTF8.GetBytes("용핵") },
            { 39, Encoding.UTF8.GetBytes("용핵") },
            { 40, Encoding.UTF8.GetBytes("떼구름") },
            { 41, Encoding.UTF8.GetBytes("떼구름") },
            { 42, Encoding.UTF8.GetBytes("떼구름") },
            { 43, Encoding.UTF8.GetBytes("떼구름") },
            { 44, Encoding.UTF8.GetBytes("섭리") },
            { 45, Encoding.UTF8.GetBytes("섭리") },
            { 46, Encoding.UTF8.GetBytes("섭리") },
            { 47, Encoding.UTF8.GetBytes("섭리") },
            { 48, Encoding.UTF8.GetBytes("섭리") },
            { 49, Encoding.UTF8.GetBytes("그림자바람") },
            { 50, Encoding.UTF8.GetBytes("방전") },
            { 51, Encoding.UTF8.GetBytes("연무") },
            { 52, Encoding.UTF8.GetBytes("맑음") },
            { 53, Encoding.UTF8.GetBytes("야수번개") },
            { 54, Encoding.UTF8.GetBytes("번개파동") },
            { 55, Encoding.UTF8.GetBytes("야수번개") },
        };
    }
}
